import { z } from 'zod'; import { ResendClient } from './client.js'; import { authorize,email,id,pagination,untrusted,Risk } from './core.js';
export type ToolDef={name:string,description:string,risk:Risk,approval:boolean,schema:z.ZodTypeAny,run:(a:any,c:ResendClient)=>Promise<any>};
const listQuery=(a:any)=>{const q=new URLSearchParams({limit:String(a.limit)});if(a.after)q.set('after',a.after);if(a.before)q.set('before',a.before);return q.toString()};
export const tools:ToolDef[]=[
{name:'resend.email.list',description:'List sent emails',risk:'READ',approval:false,schema:pagination,run:async(a,c)=>untrusted(await c.request('GET',`/emails?${listQuery(a)}`))},
{name:'resend.email.get',description:'Get one email and delivery metadata',risk:'READ',approval:false,schema:z.object({id}),run:async(a,c)=>untrusted(await c.request('GET',`/emails/${encodeURIComponent(a.id)}`))},
{name:'resend.email.send',description:'Send an external email',risk:'HIGH_RISK',approval:true,schema:z.object({from:z.string().min(3).max(320),to:z.array(email).min(1).max(50),subject:z.string().min(1).max(998),html:z.string().max(2_000_000).optional(),text:z.string().max(2_000_000).optional(),reply_to:email.optional(),approved:z.literal(true)}).refine(x=>x.html||x.text,'html or text is required'),run:async(a,c)=>{authorize('HIGH_RISK',a.approved);const {approved,...body}=a;return c.request('POST','/emails',body)}},
{name:'resend.email.cancel',description:'Cancel a scheduled email',risk:'HIGH_RISK',approval:true,schema:z.object({id,approved:z.literal(true)}),run:async(a,c)=>{authorize('HIGH_RISK',a.approved);return c.request('POST',`/emails/${encodeURIComponent(a.id)}/cancel`)}},
{name:'resend.contact.list',description:'List contacts',risk:'READ',approval:false,schema:pagination,run:async(a,c)=>untrusted(await c.request('GET',`/contacts?${listQuery(a)}`))},
{name:'resend.contact.get',description:'Get a contact',risk:'READ',approval:false,schema:z.object({id}),run:async(a,c)=>untrusted(await c.request('GET',`/contacts/${encodeURIComponent(a.id)}`))},
{name:'resend.contact.create',description:'Create a contact',risk:'WRITE',approval:true,schema:z.object({email,first_name:z.string().max(128).optional(),last_name:z.string().max(128).optional(),unsubscribed:z.boolean().optional(),approved:z.literal(true)}),run:async(a,c)=>{authorize('WRITE',a.approved);const {approved,...body}=a;return c.request('POST','/contacts',body)}},
{name:'resend.contact.update',description:'Update a contact',risk:'WRITE',approval:true,schema:z.object({id,first_name:z.string().max(128).optional(),last_name:z.string().max(128).optional(),unsubscribed:z.boolean().optional(),approved:z.literal(true)}),run:async(a,c)=>{authorize('WRITE',a.approved);const {id:cid,approved,...body}=a;return c.request('PATCH',`/contacts/${encodeURIComponent(cid)}`,body)}},
{name:'resend.domain.list',description:'List sender domains',risk:'READ',approval:false,schema:pagination,run:async(a,c)=>untrusted(await c.request('GET',`/domains?${listQuery(a)}`))},
{name:'resend.domain.get',description:'Get sender-domain status and DNS records',risk:'READ',approval:false,schema:z.object({id}),run:async(a,c)=>untrusted(await c.request('GET',`/domains/${encodeURIComponent(a.id)}`))},
{name:'resend.domain.verify',description:'Request verification of a sender domain',risk:'WRITE',approval:true,schema:z.object({id,approved:z.literal(true)}),run:async(a,c)=>{authorize('WRITE',a.approved);return c.request('POST',`/domains/${encodeURIComponent(a.id)}/verify`)}},
{name:'resend.webhook.list',description:'List webhook endpoints',risk:'READ',approval:false,schema:z.object({}),run:async(_a,c)=>untrusted(await c.request('GET','/webhooks'))}
];
export async function invoke(name:string,args:unknown,client:ResendClient){const t=tools.find(x=>x.name===name);if(!t)throw new Error('Unknown tool');return t.run(t.schema.parse(args),client)}
