import { Server } from '@modelcontextprotocol/sdk/server/index.js'; import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'; import { CallToolRequestSchema, ListToolsRequestSchema } from '@modelcontextprotocol/sdk/types.js';
import { loadConfig } from '../auth/config.js'; import { AirbyteClient,AirbyteError } from '../client/airbyte-client.js'; import { sanitize } from '../models/sanitize.js'; import { TOOL_DEFINITIONS,payloadWithoutApproval } from '../tools/definitions.js'; import { authorize } from '../tools/policy.js'; import { validateToolArgs } from '../tools/validate.js';
export function createServer({config=loadConfig(),client=null}={}) {
  const api=client||new AirbyteClient(config); const server=new Server({name:'airbyte-safe-connector',version:'1.0.0'},{capabilities:{tools:{}}});
  server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:TOOL_DEFINITIONS}));
  server.setRequestHandler(CallToolRequestSchema,async(req,extra)=>{ const name=req.params.name; try { const args=validateToolArgs(name,req.params.arguments||{}); const payload=payloadWithoutApproval(args); authorize(config,name,payload,args.approval_token); const s=extra?.signal; let result;
    switch(name){case'airbyte.workspace.list':result=await api.listWorkspaces(withPage(payload),s);break;case'airbyte.source.list':result=await api.listSources(withPage(payload),s);break;case'airbyte.source.get':result=await api.getSource(payload,s);break;case'airbyte.destination.list':result=await api.listDestinations(withPage(payload),s);break;case'airbyte.destination.get':result=await api.getDestination(payload,s);break;case'airbyte.connection.list':result=await api.listConnections(withPage(payload),s);break;case'airbyte.connection.get':result=await api.getConnection(payload,s);break;case'airbyte.stream.list':result=await api.listStreams({...payload,ignoreCache:payload.ignoreCache??false},s);break;case'airbyte.job.list':result=await api.listJobs(withPage(payload),s);break;case'airbyte.job.get':result=await api.getJob(payload,s);break;case'airbyte.job.sync':result=await api.createJob(payload.connectionId,'sync',s);break;case'airbyte.job.reset':result=await api.createJob(payload.connectionId,'reset',s);break;case'airbyte.job.cancel':result=await api.cancelJob(payload.jobId,s);break;default:throw new Error(`Unknown tool: ${name}`);}
    const clean=sanitize(result); return {content:[{type:'text',text:JSON.stringify({untrusted_provider_data:true,data:clean},null,2)}],structuredContent:{untrusted_provider_data:true,data:clean}};
  } catch(e){return {isError:true,content:[{type:'text',text:JSON.stringify(normalize(e))}]};} }); return server;
}
function withPage(a){return {...a,limit:a.limit??20,offset:a.offset??0};} function normalize(e){if(e instanceof AirbyteError)return{error:e.message,status:e.status,code:e.code,retryAfter:e.retryAfter,retryable:e.status===429||e.status>=500};return{error:e?.message||String(e),retryable:false};}
if(import.meta.url===`file://${process.argv[1]}`){const server=createServer();await server.connect(new StdioServerTransport());}
