export type Method='GET'|'POST'|'PUT'|'PATCH'|'DELETE';
export class FusionAuthError extends Error{constructor(public status:number,public body:unknown,public retryAfter?:number){super(`FusionAuth API error ${status}`)}}
export interface ClientOptions{baseUrl:string;apiKey:string;tenantId?:string;timeoutMs?:number;maxRetries?:number;fetchFn?:typeof fetch}
export class FusionAuthClient{
 private f:typeof fetch; constructor(private o:ClientOptions){if(!/^https?:\/\//.test(o.baseUrl))throw new Error('FUSIONAUTH_BASE_URL must be an absolute http(s) URL');if(!o.apiKey)throw new Error('FUSIONAUTH_API_KEY is required');this.f=o.fetchFn??fetch}
 async request<T>(method:Method,path:string,body?:unknown,query?:Record<string,string|number|undefined>,signal?:AbortSignal):Promise<T>{
  const u=new URL(path,this.o.baseUrl.endsWith('/')?this.o.baseUrl:this.o.baseUrl+'/'); for(const [k,v] of Object.entries(query??{}))if(v!==undefined)u.searchParams.set(k,String(v));
  const max=this.o.maxRetries??2; for(let attempt=0;;attempt++){const c=new AbortController();const timer=setTimeout(()=>c.abort(),this.o.timeoutMs??10000);const onAbort=()=>c.abort();signal?.addEventListener('abort',onAbort,{once:true});
   try{const r=await this.f(u,{method,headers:{Authorization:this.o.apiKey,'Content-Type':'application/json',...(this.o.tenantId?{'X-FusionAuth-TenantId':this.o.tenantId}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:c.signal});const text=await r.text();const data=text?JSON.parse(text):{};if(r.ok)return data as T;const retryAfter=Number(r.headers.get('retry-after')??0);if((r.status===429||r.status>=500)&&attempt<max&&method!=='DELETE'){await new Promise(x=>setTimeout(x,retryAfter?retryAfter*1000:250*2**attempt));continue}throw new FusionAuthError(r.status,data,retryAfter||undefined)}catch(e){if(e instanceof FusionAuthError)throw e;if(attempt<max&&method==='GET'){await new Promise(x=>setTimeout(x,250*2**attempt));continue}throw e}finally{clearTimeout(timer);signal?.removeEventListener('abort',onAbort)}}}
}
export function clientFromEnv(fetchFn?:typeof fetch){return new FusionAuthClient({baseUrl:process.env.FUSIONAUTH_BASE_URL??'',apiKey:process.env.FUSIONAUTH_API_KEY??'',tenantId:process.env.FUSIONAUTH_TENANT_ID||undefined,timeoutMs:Number(process.env.FUSIONAUTH_TIMEOUT_MS??10000),maxRetries:Number(process.env.FUSIONAUTH_MAX_RETRIES??2),fetchFn})}
