import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';import {z} from 'zod';import {VantaClient,id,pageSize,requireApproval} from './core.js';
export function createServer(client=new VantaClient()){const s=new McpServer({name:'vanta-connector',version:'1.0.0'});const out=(v:unknown)=>({content:[{type:'text' as const,text:JSON.stringify({source:'Vanta',untrusted_provider_data:true,data:v})}]});
s.tool('vanta.people.list','List personnel records. READ.',{pageSize:pageSize.optional(),pageCursor:z.string().max(1000).optional(),search:z.string().max(200).optional()},async a=>{const q=new URLSearchParams();if(a.pageSize)q.set('pageSize',String(a.pageSize));if(a.pageCursor)q.set('pageCursor',a.pageCursor);if(a.search)q.set('search',a.search);return out(await client.request(`/people?${q}`));});
s.tool('vanta.people.offboard','Offboard former personnel. HIGH_RISK; explicit approval required.',{personIds:z.array(id).min(1).max(1000),approved:z.boolean().optional()},async a=>{requireApproval('HIGH_RISK',a.approved);return out(await client.request('/people/offboard',{method:'POST',body:JSON.stringify({personIds:a.personIds})},false));});
s.tool('vanta.document.uploads.list','List evidence uploads for a document. READ.',{documentId:id,pageSize:pageSize.optional(),pageCursor:z.string().max(1000).optional()},async a=>{const q=new URLSearchParams();if(a.pageSize)q.set('pageSize',String(a.pageSize));if(a.pageCursor)q.set('pageCursor',a.pageCursor);return out(await client.request(`/documents/${encodeURIComponent(a.documentId)}/uploads?${q}`));});
s.tool('vanta.document.submit','Submit existing draft document evidence for auditor visibility. WRITE; approval required.',{documentId:id,approved:z.boolean().optional()},async a=>{requireApproval('WRITE',a.approved);return out(await client.request(`/documents/${encodeURIComponent(a.documentId)}/submit`,{method:'POST'},false));});
s.tool('vanta.integration.resource_kinds.list','List resource kinds exposed by a connected integration. READ.',{integrationId:id},async a=>out(await client.request(`/integrations/${encodeURIComponent(a.integrationId)}/resource-kinds`)));
s.tool('vanta.trust_center.access_request.approve','Approve external Trust Center access. HIGH_RISK; explicit approval required.',{slugId:id,accessRequestId:id,expirationDate:z.string().datetime().optional(),isNdaRequired:z.boolean().default(true),resourceIds:z.array(id).max(100).optional(),accessLevel:z.enum(['FULL_ACCESS','PARTIAL_ACCESS']).optional(),approved:z.boolean().optional()},async a=>{requireApproval('HIGH_RISK',a.approved);const {approved,...body}=a;return out(await client.request(`/trust-centers/${encodeURIComponent(a.slugId)}/access-requests/${encodeURIComponent(a.accessRequestId)}/approve`,{method:'POST',body:JSON.stringify(body)},false));});return s;}
if(process.env.NODE_ENV!=='test'){const s=createServer();await s.connect(new StdioServerTransport());}
