const id={type:'string',minLength:1,maxLength:200,pattern:'^[A-Za-z0-9_-]+$'};const approval={type:'string',minLength:64,maxLength:64,pattern:'^[a-f0-9]{64}$'};const componentStatus={type:'string',enum:['operational','degraded_performance','partial_outage','major_outage','under_maintenance']};const incidentStatus={type:'string',enum:['investigating','identified','monitoring','resolved']};
const componentPatch={type:'object',additionalProperties:false,minProperties:1,properties:{name:{type:'string',minLength:1,maxLength:255},description:{type:'string',maxLength:5000},status:componentStatus,showcase:{type:'boolean'},only_show_if_degraded:{type:'boolean'},group_id:{anyOf:[id,{type:'null'}]},start_date:{type:'string',format:'date'}}};
const incidentBody={type:'object',additionalProperties:false,minProperties:1,properties:{name:{type:'string',minLength:1,maxLength:255},status:incidentStatus,body:{type:'string',maxLength:20000},component_ids:{type:'array',maxItems:1000,items:id,uniqueItems:true},components:{type:'object',maxProperties:1000,additionalProperties:componentStatus},deliver_notifications:{type:'boolean'},auto_transition_deliver_notifications_at_end:{type:'boolean'},auto_transition_deliver_notifications_at_start:{type:'boolean'},auto_transition_to_maintenance_state:{type:'boolean'},auto_transition_to_operational_state:{type:'boolean'},scheduled_for:{type:'string',format:'date-time'},scheduled_until:{type:'string',format:'date-time'},scheduled_remind_prior:{type:'boolean'}}};
export const TOOL_DEFINITIONS=[
{name:'statuspage.page.get',description:'Get page metadata. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,required:['page_id'],properties:{page_id:id}}},
{name:'statuspage.component.list',description:'List page components with bounded pagination. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,required:['page_id'],properties:{page_id:id,page:{type:'integer',minimum:1,maximum:100000,default:1},per_page:{type:'integer',minimum:1,maximum:100,default:100}}}},
{name:'statuspage.component.get',description:'Get one page component. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,required:['page_id','component_id'],properties:{page_id:id,component_id:id}}},
{name:'statuspage.component.update',description:'Update component metadata or service status. Risk: WRITE. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['page_id','component_id','component','approval_token'],properties:{page_id:id,component_id:id,component:componentPatch,approval_token:approval}}},
{name:'statuspage.incident.list',description:'List/search incidents. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,required:['page_id'],properties:{page_id:id,q:{type:'string',maxLength:500},limit:{type:'integer',minimum:1,maximum:100,default:100},page:{type:'integer',minimum:1,maximum:100000,default:1}}}},
{name:'statuspage.incident.get',description:'Get one incident. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,required:['page_id','incident_id'],properties:{page_id:id,incident_id:id}}},
{name:'statuspage.incident.create',description:'Create a public/customer-facing incident or scheduled maintenance. Risk: HIGH_RISK because it can publish notifications. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['page_id','incident','approval_token'],properties:{page_id:id,incident:incidentBody,approval_token:approval}}},
{name:'statuspage.incident.update',description:'Update an incident, including status/body/components and notification behavior. Risk: HIGH_RISK. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['page_id','incident_id','incident','approval_token'],properties:{page_id:id,incident_id:id,incident:incidentBody,approval_token:approval}}},
{name:'statuspage.incident.delete',description:'Delete an incident. Risk: DESTRUCTIVE. Disabled by default and explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['page_id','incident_id','approval_token'],properties:{page_id:id,incident_id:id,approval_token:approval}}}
];
export function withoutApproval(args={}){const {approval_token:_ignore,...rest}=args;return rest;}
