import{z}from"zod";import{FastmailClient}from"./client.js";import{authorize,Risk}from"./security.js";
export type Def={name:string;description:string;risk:Risk;schema:z.ZodTypeAny;run:(a:any,c:FastmailClient)=>Promise<unknown>};const approved=z.boolean().optional(),eid=z.string().min(1),mid=z.string().min(1);
export const tools:Def[]=[
{name:"fastmail.session.get",description:"Get JMAP session metadata and advertised capabilities.",risk:"READ",schema:z.object({}).strict(),run:(_,c)=>c.getSession()},
{name:"fastmail.mailbox.list",description:"List mailboxes.",risk:"READ",schema:z.object({limit:z.number().int().min(1).max(200).default(100)}).strict(),run:async(a,c)=>{const accountId=await c.mailAccount();return c.call([["Mailbox/get",{accountId,ids:null},"m"]])}},
{name:"fastmail.email.search",description:"Search email using JMAP filters.",risk:"READ",schema:z.object({text:z.string().max(500).optional(),inMailbox:mid.optional(),from:z.string().max(320).optional(),to:z.string().max(320).optional(),limit:z.number().int().min(1).max(100).default(25),position:z.number().int().min(0).default(0)}).strict(),run:async(a,c)=>{const accountId=await c.mailAccount();const filter:any={};for(const k of["text","inMailbox","from","to"])if(a[k]!==undefined)filter[k]=a[k];return c.call([["Email/query",{accountId,filter,position:a.position,limit:a.limit,calculateTotal:true},"q"]])}},
{name:"fastmail.email.get",description:"Read selected email metadata and body values.",risk:"READ",schema:z.object({ids:z.array(eid).min(1).max(50)}).strict(),run:async(a,c)=>{const accountId=await c.mailAccount();return c.call([["Email/get",{accountId,ids:a.ids,properties:["id","blobId","threadId","mailboxIds","keywords","receivedAt","from","to","cc","bcc","subject","preview","textBody","htmlBody","bodyValues"]},"g"]])}},
{name:"fastmail.email.create_draft",description:"Create a draft email without sending it.",risk:"WRITE",schema:z.object({draftMailboxId:mid,to:z.array(z.object({email:z.string().email(),name:z.string().max(200).optional()}).strict()).min(1).max(50),subject:z.string().max(998),text:z.string().max(200000),approved}).strict(),run:async(a,c)=>{authorize("WRITE",a.approved);const accountId=await c.mailAccount();return c.call([["Email/set",{accountId,create:{draft:{mailboxIds:{[a.draftMailboxId]:true},keywords:{"$draft":true},to:a.to,subject:a.subject,bodyValues:{body:{value:a.text,isTruncated:false}},textBody:[{partId:"body",type:"text/plain"}]}}},"d"]],false)}},
{name:"fastmail.email.mark_read",description:"Mark email as read or unread.",risk:"WRITE",schema:z.object({id:eid,read:z.boolean(),approved}).strict(),run:async(a,c)=>{authorize("WRITE",a.approved);const accountId=await c.mailAccount();return c.call([["Email/set",{accountId,update:{[a.id]:{[`keywords/$seen`]:a.read}}},"r"]],false)}},
{name:"fastmail.email.move",description:"Move email from one mailbox to another.",risk:"WRITE",schema:z.object({id:eid,fromMailboxId:mid,toMailboxId:mid,approved}).strict(),run:async(a,c)=>{authorize("WRITE",a.approved);const accountId=await c.mailAccount();return c.call([["Email/set",{accountId,update:{[a.id]:{[`mailboxIds/${a.fromMailboxId}`]:null,[`mailboxIds/${a.toMailboxId}`]:true}}},"mv"]],false)}},
{name:"fastmail.email.send",description:"Send an existing draft via JMAP EmailSubmission.",risk:"HIGH_RISK",schema:z.object({emailId:eid,identityId:z.string().min(1),approved}).strict(),run:async(a,c)=>{authorize("HIGH_RISK",a.approved);const s=await c.getSession();const accountId=s.primaryAccounts["urn:ietf:params:jmap:submission"];if(!accountId)throw new Error("JMAP submission capability unavailable");return c.call([["EmailSubmission/set",{accountId,create:{send:{identityId:a.identityId,emailId:a.emailId}}},"s"]],false)}},
{name:"fastmail.email.delete",description:"Permanently destroy an email by id.",risk:"DESTRUCTIVE",schema:z.object({id:eid,approved}).strict(),run:async(a,c)=>{authorize("DESTRUCTIVE",a.approved);const accountId=await c.mailAccount();return c.call([["Email/set",{accountId,destroy:[a.id]},"x"]],false)}}];
export async function execute(name:string,input:unknown,client=new FastmailClient()){const t=tools.find(x=>x.name===name);if(!t)throw new Error("Unknown tool");return t.run(t.schema.parse(input),client)}