import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js'; import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js'; import {z} from 'zod'; import {PagerTreeClient} from './client.js';
export const client=new PagerTreeClient(process.env.PAGERTREE_API_KEY||'',process.env.PAGERTREE_BASE_URL||'https://api.pagertree.com/api/v4',Number(process.env.PAGERTREE_TIMEOUT_MS||15000));
export const server=new McpServer({name:'pagertree-connector',version:'1.0.0'}); const out=(x:unknown)=>({content:[{type:'text' as const,text:JSON.stringify({untrusted_provider_data:true,data:x},null,2)}]});
const id=z.string().min(1).max(128).regex(/^[A-Za-z0-9_-]+$/); const page={limit:z.number().int().min(1).max(100).optional(),offset:z.number().int().min(0).optional()}; const q=(a:any)=>{const p=new URLSearchParams();if(a.limit)p.set('limit',String(a.limit));if(a.offset!==undefined)p.set('offset',String(a.offset));return p.size?'?'+p:''}; const approval=z.string().min(8).max(256);
function approve(token:string){if(process.env.PAGERTREE_ALLOW_WRITE!=='true')throw new Error('WRITE tools are disabled');if(!process.env.PAGERTREE_APPROVAL_TOKEN||token!==process.env.PAGERTREE_APPROVAL_TOKEN)throw new Error('Explicit human approval required');}
server.tool('pagertree.alert.list','READ: list alerts with bounded pagination',page,async a=>out(await client.request('/alerts'+q(a))));
server.tool('pagertree.alert.get','READ: retrieve an alert',{alertId:id},async a=>out(await client.request(`/alerts/${a.alertId}`)));
server.tool('pagertree.alert.comment.list','READ: list alert comments',{alertId:id},async a=>out(await client.request(`/alerts/${a.alertId}/comments`)));
server.tool('pagertree.team.list','READ: list teams',page,async a=>out(await client.request('/teams'+q(a))));
server.tool('pagertree.team.get','READ: retrieve team',{teamId:id},async a=>out(await client.request(`/teams/${a.teamId}`)));
server.tool('pagertree.team.current_oncall','READ: retrieve current on-call attendees',{teamId:id},async a=>out(await client.request(`/teams/${a.teamId}/current_oncall`)));
server.tool('pagertree.team.alert.list','READ: list alerts assigned to team',{teamId:id,...page},async a=>out(await client.request(`/teams/${a.teamId}/alerts${q(a)}`)));
server.tool('pagertree.schedule.list','READ: list on-call schedules',page,async a=>out(await client.request('/schedules'+q(a))));
server.tool('pagertree.escalation_policy.list','READ: list escalation policies',page,async a=>out(await client.request('/escalation_policies'+q(a))));
server.tool('pagertree.alert.create','HIGH_RISK WRITE: create and route an alert',{title:z.string().min(1).max(200),description:z.string().max(10000).optional(),urgency:z.enum(['low','medium','high','critical']),destinationTeamIds:z.array(id).max(20).optional(),destinationRouterIds:z.array(id).max(20).optional(),destinationAccountUserIds:z.array(id).max(20).optional(),tags:z.array(z.string().min(1).max(64)).max(20).optional(),approvalToken:approval},async a=>{approve(a.approvalToken);if(!(a.destinationTeamIds?.length||a.destinationRouterIds?.length||a.destinationAccountUserIds?.length))throw new Error('At least one destination is required');const {approvalToken,destinationTeamIds,destinationRouterIds,destinationAccountUserIds,...rest}=a;return out(await client.request('/alerts',{method:'POST',body:JSON.stringify({...rest,destination_team_ids:destinationTeamIds,destination_router_ids:destinationRouterIds,destination_account_user_ids:destinationAccountUserIds})},false));});
for(const [name,action] of [['pagertree.alert.acknowledge','acknowledge'],['pagertree.alert.resolve','resolve']] as const) server.tool(name,`WRITE: ${action} alert; explicit approval required`,{alertId:id,approvalToken:approval},async a=>{approve(a.approvalToken);return out(await client.request(`/alerts/${a.alertId}/${action}`,{method:'POST'},false));});
server.tool('pagertree.alert.comment.create','WRITE: add an external alert comment',{alertId:id,body:z.string().min(1).max(5000),approvalToken:approval},async a=>{approve(a.approvalToken);return out(await client.request(`/alerts/${a.alertId}/comments`,{method:'POST',body:JSON.stringify({body:a.body})},false));});
if(import.meta.url===`file://${process.argv[1]}`) await server.connect(new StdioServerTransport());