import {z} from 'zod';
import type {TypesenseClient} from './client.js';
import type {Risk} from './policy.js';
export type ToolDef={name:string;description:string;risk:Risk;permissions:string[];schema:Record<string,z.ZodTypeAny>;run:(a:any)=>Promise<unknown>};
const name=z.string().min(1).max(255).regex(/^[A-Za-z0-9_.-]+$/);const id=z.string().min(1).max(512);const approved=z.boolean().optional();
const obj=z.record(z.string(),z.unknown());
export function buildTools(api:TypesenseClient):ToolDef[]{return[
{name:'typesense.health.get',description:'Check Typesense node health',risk:'READ',permissions:['health:get'],schema:{},run:()=>api.request('GET','/health')},
{name:'typesense.collection.list',description:'List collection schemas',risk:'READ',permissions:['collections:get'],schema:{},run:()=>api.request('GET','/collections')},
{name:'typesense.collection.get',description:'Get one collection schema',risk:'READ',permissions:['collections:get'],schema:{collection:name},run:a=>api.request('GET',`/collections/${encodeURIComponent(a.collection)}`)},
{name:'typesense.collection.create',description:'Create a collection with an explicit Typesense schema',risk:'WRITE',permissions:['collections:create'],schema:{schema:z.object({name,fields:z.array(z.object({name:z.string().min(1).max(255),type:z.string().min(1).max(32),facet:z.boolean().optional(),optional:z.boolean().optional(),index:z.boolean().optional(),store:z.boolean().optional(),sort:z.boolean().optional()}).strict()).min(1).max(200),default_sorting_field:z.string().max(255).optional(),enable_nested_fields:z.boolean().optional()}).strict(),approved},run:a=>api.request('POST','/collections',a.schema)},
{name:'typesense.document.search',description:'Search documents in a collection',risk:'READ',permissions:['documents:search'],schema:{collection:name,q:z.string().max(10000),query_by:z.string().min(1).max(4000),filter_by:z.string().max(10000).optional(),sort_by:z.string().max(4000).optional(),facet_by:z.string().max(4000).optional(),page:z.number().int().min(1).max(100000).optional(),per_page:z.number().int().min(1).max(250).optional()},run:a=>{const{collection,...q}=a;return api.request('GET',`/collections/${encodeURIComponent(collection)}/documents/search`,undefined,q)}},
{name:'typesense.document.get',description:'Retrieve a document by id',risk:'READ',permissions:['documents:get'],schema:{collection:name,id,include_fields:z.string().max(4000).optional(),exclude_fields:z.string().max(4000).optional()},run:a=>api.request('GET',`/collections/${encodeURIComponent(a.collection)}/documents/${encodeURIComponent(a.id)}`,undefined,{include_fields:a.include_fields,exclude_fields:a.exclude_fields})},
{name:'typesense.document.export',description:'Export matching documents as provider-returned JSONL',risk:'READ',permissions:['documents:export'],schema:{collection:name,filter_by:z.string().max(10000).optional(),include_fields:z.string().max(4000).optional(),exclude_fields:z.string().max(4000).optional()},run:a=>api.request('GET',`/collections/${encodeURIComponent(a.collection)}/documents/export`,undefined,{filter_by:a.filter_by,include_fields:a.include_fields,exclude_fields:a.exclude_fields})},
{name:'typesense.document.create',description:'Create one document',risk:'WRITE',permissions:['documents:create'],schema:{collection:name,document:obj,approved},run:a=>api.request('POST',`/collections/${encodeURIComponent(a.collection)}/documents`,a.document)},
{name:'typesense.document.update',description:'Partially update one existing document',risk:'WRITE',permissions:['documents:update'],schema:{collection:name,id,changes:obj,approved},run:a=>api.request('PATCH',`/collections/${encodeURIComponent(a.collection)}/documents/${encodeURIComponent(a.id)}`,a.changes)},
{name:'typesense.document.delete',description:'Delete one document by id',risk:'DESTRUCTIVE',permissions:['documents:delete'],schema:{collection:name,id,ignore_not_found:z.boolean().optional(),approved},run:a=>api.request('DELETE',`/collections/${encodeURIComponent(a.collection)}/documents/${encodeURIComponent(a.id)}`,undefined,{ignore_not_found:a.ignore_not_found})}
]}
