import { z } from 'zod';
import { BrevoClient } from './client.js';
import { assertAllowed, assertPublicHttpsUrl, type Risk } from './policy.js';

const email = z.string().email().max(254);
const page = { limit:z.number().int().min(1).max(500).default(50), offset:z.number().int().min(0).default(0) };
const id = z.union([z.string().min(1).max(320), z.number().int().positive()]);

export type ToolDef = { name:string; description:string; risk:Risk; schema:Record<string,z.ZodTypeAny>; run:(args:any,c:BrevoClient)=>Promise<any> };

export const tools:ToolDef[] = [
  { name:'brevo.account.get', description:'Get Brevo account metadata for the authenticated account.', risk:'READ', schema:{}, run:(_,c)=>c.request('/account') },
  { name:'brevo.contact.list', description:'List contacts with bounded offset pagination.', risk:'READ', schema:page, run:(a,c)=>c.request('/contacts',{query:{limit:a.limit,offset:a.offset}}) },
  { name:'brevo.contact.get', description:'Get one contact by email, contact ID, EXT_ID, phone, WhatsApp, or landline identifier.', risk:'READ', schema:{identifier:id,identifierType:z.enum(['email_id','phone_id','contact_id','ext_id','whatsapp_id','landline_number_id']).optional()}, run:(a,c)=>c.request(`/contacts/${encodeURIComponent(String(a.identifier))}`,{query:{identifierType:a.identifierType}}) },
  { name:'brevo.contact.create', description:'Create a contact. Host-side WRITE approval is required.', risk:'WRITE', schema:{email,attributes:z.record(z.unknown()).optional(),listIds:z.array(z.number().int().positive()).max(100).optional(),updateEnabled:z.boolean().default(false)}, run:(a,c)=>c.request('/contacts',{method:'POST',body:a,retryable:false}) },
  { name:'brevo.contact.update', description:'Update attributes/list membership for an existing contact. Host-side WRITE approval is required.', risk:'WRITE', schema:{identifier:id,attributes:z.record(z.unknown()).optional(),listIds:z.array(z.number().int().positive()).max(100).optional(),unlinkListIds:z.array(z.number().int().positive()).max(100).optional()}, run:(a,c)=>{const {identifier,...body}=a; return c.request(`/contacts/${encodeURIComponent(String(identifier))}`,{method:'PUT',body,retryable:false});} },
  { name:'brevo.contact.delete', description:'Delete a contact. Disabled by default; requires host-side DESTRUCTIVE approval.', risk:'DESTRUCTIVE', schema:{identifier:id}, run:(a,c)=>c.request(`/contacts/${encodeURIComponent(String(a.identifier))}`,{method:'DELETE',retryable:false}) },
  { name:'brevo.campaign.list', description:'List email campaigns with bounded pagination.', risk:'READ', schema:{...page,status:z.enum(['suspended','archive','sent','queued','draft']).optional()}, run:(a,c)=>c.request('/emailCampaigns',{query:{limit:a.limit,offset:a.offset,status:a.status}}) },
  { name:'brevo.campaign.get', description:'Get an email campaign by numeric ID.', risk:'READ', schema:{campaignId:z.number().int().positive()}, run:(a,c)=>c.request(`/emailCampaigns/${a.campaignId}`) },
  { name:'brevo.campaign.create', description:'Create a draft email campaign without sending it. Host-side WRITE approval is required.', risk:'WRITE', schema:{name:z.string().min(1).max(200),subject:z.string().min(1).max(998),sender:z.object({name:z.string().max(200).optional(),email:email.optional(),id:z.number().int().positive().optional()}),htmlContent:z.string().min(1).max(2_000_000),recipients:z.object({listIds:z.array(z.number().int().positive()).max(50).optional(),exclusionListIds:z.array(z.number().int().positive()).max(50).optional(),segmentIds:z.array(z.number().int().positive()).max(50).optional()})}, run:(a,c)=>c.request('/emailCampaigns',{method:'POST',body:a,retryable:false}) },
  { name:'brevo.campaign.send', description:'Send an existing Brevo email campaign to external recipients. Explicit host-side HIGH_RISK approval is required.', risk:'HIGH_RISK', schema:{campaignId:z.number().int().positive()}, run:(a,c)=>c.request(`/emailCampaigns/${a.campaignId}/sendNow`,{method:'POST',retryable:false}) },
  { name:'brevo.email.send', description:'Send a transactional email to external recipients. Explicit host-side HIGH_RISK approval is required.', risk:'HIGH_RISK', schema:{sender:z.object({name:z.string().max(200).optional(),email}),to:z.array(z.object({email,name:z.string().max(200).optional()})).min(1).max(50),subject:z.string().min(1).max(998),htmlContent:z.string().max(2_000_000).optional(),textContent:z.string().max(2_000_000).optional(),replyTo:z.object({email,name:z.string().max(200).optional()}).optional(),tags:z.array(z.string().min(1).max(128)).max(20).optional()}, run:(a,c)=>{if(!a.htmlContent&&!a.textContent) throw new Error('htmlContent or textContent is required.'); return c.request('/smtp/email',{method:'POST',body:a,retryable:false});} },
  { name:'brevo.sender.list', description:'List configured sender identities.', risk:'READ', schema:{ip:z.string().max(64).optional(),domain:z.string().max(253).optional()}, run:(a,c)=>c.request('/senders',{query:a}) },
  { name:'brevo.webhook.list', description:'List webhook configurations.', risk:'READ', schema:{type:z.enum(['transactional','marketing']).optional(),sort:z.enum(['asc','desc']).optional()}, run:(a,c)=>c.request('/webhooks',{query:a}) },
  { name:'brevo.webhook.create', description:'Create an HTTPS webhook to a public host. HIGH_RISK approval is required because it sends account events externally.', risk:'HIGH_RISK', schema:{url:z.string().url().max(2048),description:z.string().max(200).optional(),events:z.array(z.string().min(1).max(64)).min(1).max(50),type:z.enum(['transactional','marketing']).default('transactional')}, run:(a,c)=>{assertPublicHttpsUrl(a.url); return c.request('/webhooks',{method:'POST',body:a,retryable:false});} },
  { name:'brevo.webhook.delete', description:'Delete a webhook. Disabled by default; requires host-side DESTRUCTIVE approval.', risk:'DESTRUCTIVE', schema:{webhookId:z.number().int().positive()}, run:(a,c)=>c.request(`/webhooks/${a.webhookId}`,{method:'DELETE',retryable:false}) },
];

export async function invoke(tool:ToolDef,args:any,client:BrevoClient){ assertAllowed(tool.risk); const parsed=z.object(tool.schema).strict().parse(args); return tool.run(parsed,client); }
