import {z} from 'zod';import type {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';import type {Config} from './config.js';import {FreshBooksClient} from './client.js';import {authorize,assertId} from './security.js';
const page=z.object({page:z.number().int().min(1).default(1),per_page:z.number().int().min(1).max(100).default(50)});const id=z.object({id:z.string().min(1).max(128)});const approval=z.string().optional();const output=(v:unknown)=>({content:[{type:'text' as const,text:JSON.stringify({untrusted_provider_data:true,data:v},null,2)}]});
export function registerTools(s:McpServer,c:FreshBooksClient,cfg:Config){
s.tool('freshbooks.client.list','List FreshBooks clients (READ).',{page:z.number().int().min(1).default(1),per_page:z.number().int().min(1).max(100).default(50)},async a=>output(await c.listClients(a.page,a.per_page)));
s.tool('freshbooks.client.get','Get a client (READ).',{id:z.string()},async a=>output(await c.getClient(assertId(a.id,'client id'))));
s.tool('freshbooks.client.create','Create a client (WRITE).',{client:z.record(z.unknown()),approval},async a=>{authorize(cfg,'WRITE',a.approval);return output(await c.createClient(a.client));});
s.tool('freshbooks.client.update','Update a client (WRITE).',{id:z.string(),client:z.record(z.unknown()),approval},async a=>{authorize(cfg,'WRITE',a.approval);return output(await c.updateClient(assertId(a.id,'client id'),a.client));});
s.tool('freshbooks.invoice.list','List invoices (READ).',{page:z.number().int().min(1).default(1),per_page:z.number().int().min(1).max(100).default(50)},async a=>output(await c.listInvoices(a.page,a.per_page)));
s.tool('freshbooks.invoice.get','Get an invoice (READ).',{id:z.string()},async a=>output(await c.getInvoice(assertId(a.id,'invoice id'))));
s.tool('freshbooks.invoice.create','Create a draft invoice (WRITE).',{invoice:z.record(z.unknown()),approval},async a=>{authorize(cfg,'WRITE',a.approval);const clean={...a.invoice,action_email:false,action_mark_as_sent:false};return output(await c.createInvoice(clean));});
s.tool('freshbooks.invoice.update','Update an invoice without sending it (WRITE).',{id:z.string(),invoice:z.record(z.unknown()),approval},async a=>{authorize(cfg,'WRITE',a.approval);const clean={...a.invoice,action_email:false};return output(await c.updateInvoice(assertId(a.id,'invoice id'),clean));});
s.tool('freshbooks.invoice.send','Send an existing invoice by email (HIGH_RISK; human approval required).',{id:z.string(),email_recipients:z.array(z.string().email()).min(1).max(20),approval:z.string()},async a=>{authorize(cfg,'HIGH_RISK',a.approval);return output(await c.updateInvoice(assertId(a.id,'invoice id'),{action_email:true,email_recipients:a.email_recipients}));});
s.tool('freshbooks.expense.list','List expenses (READ).',{page:z.number().int().min(1).default(1),per_page:z.number().int().min(1).max(100).default(50)},async a=>output(await c.listExpenses(a.page,a.per_page)));
s.tool('freshbooks.expense.get','Get an expense (READ).',{id:z.string()},async a=>output(await c.getExpense(assertId(a.id,'expense id'))));
s.tool('freshbooks.expense.create','Create an expense (WRITE).',{expense:z.record(z.unknown()),approval},async a=>{authorize(cfg,'WRITE',a.approval);return output(await c.createExpense(a.expense));});
s.tool('freshbooks.expense.update','Update an expense (WRITE).',{id:z.string(),expense:z.record(z.unknown()),approval},async a=>{authorize(cfg,'WRITE',a.approval);return output(await c.updateExpense(assertId(a.id,'expense id'),a.expense));});}
