import {z} from "zod"; import {DataPacket_Kind,LiveKitClient} from "./client.js"; import {loadConfig,type Config} from "./config.js"; import {enforceApproval,type Risk} from "./policy.js";
const id=z.string().min(1).max(255),meta=z.string().max(524288),approval=z.string().length(64).optional(); const s=(d:string,m=255)=>({type:"string",minLength:1,maxLength:m,description:d}); const a={approvalId:{type:"string",minLength:64,maxLength:64}}; const o=(p:any,r:string[]=[])=>({type:"object",additionalProperties:false,properties:p,required:r}); export type ToolDef={name:string;description:string;risk:Risk;inputSchema:any};
export const toolDefs:ToolDef[]=[
{name:"livekit.room.list",risk:"READ",description:"List active rooms.",inputSchema:o({names:{type:"array",maxItems:50,items:s("Room name")}})},
{name:"livekit.room.create",risk:"WRITE",description:"Create a room.",inputSchema:o({name:s("Room name"),emptyTimeout:{type:"integer",minimum:0,maximum:86400},maxParticipants:{type:"integer",minimum:1,maximum:10000},metadata:{type:"string",maxLength:524288},...a},["name"])},
{name:"livekit.room.metadata.update",risk:"WRITE",description:"Replace room metadata.",inputSchema:o({room:s("Room name"),metadata:{type:"string",maxLength:524288},...a},["room","metadata"])},
{name:"livekit.room.delete",risk:"DESTRUCTIVE",description:"Delete a room and disconnect participants.",inputSchema:o({room:s("Room name"),...a},["room","approvalId"])},
{name:"livekit.participant.list",risk:"READ",description:"List room participants.",inputSchema:o({room:s("Room name")},["room"])},
{name:"livekit.participant.get",risk:"READ",description:"Get a participant by identity.",inputSchema:o({room:s("Room name"),identity:s("Participant identity")},["room","identity"])},
{name:"livekit.participant.permissions.update",risk:"HIGH_RISK",description:"Change participant media/data permissions.",inputSchema:o({room:s("Room name"),identity:s("Participant identity"),canPublish:{type:"boolean"},canSubscribe:{type:"boolean"},canPublishData:{type:"boolean"},...a},["room","identity","approvalId"])},
{name:"livekit.participant.remove",risk:"HIGH_RISK",description:"Force-disconnect a participant.",inputSchema:o({room:s("Room name"),identity:s("Participant identity"),...a},["room","identity","approvalId"])},
{name:"livekit.track.mute",risk:"HIGH_RISK",description:"Mute or unmute a published track.",inputSchema:o({room:s("Room name"),identity:s("Participant identity"),trackSid:s("Track SID"),muted:{type:"boolean"},...a},["room","identity","trackSid","muted","approvalId"])},
{name:"livekit.data.send",risk:"HIGH_RISK",description:"Send UTF-8 data into a room.",inputSchema:o({room:s("Room name"),text:{type:"string",maxLength:65536},reliable:{type:"boolean"},destinationIdentities:{type:"array",maxItems:100,items:s("Identity")},topic:{type:"string",maxLength:255},...a},["room","text","approvalId"])},
{name:"livekit.access_token.issue",risk:"HIGH_RISK",description:"Mint a short-lived participant join token.",inputSchema:o({room:s("Room name"),identity:s("Identity"),ttlSeconds:{type:"integer",minimum:60,maximum:86400},name:{type:"string",maxLength:255},metadata:{type:"string",maxLength:524288},canPublish:{type:"boolean"},canSubscribe:{type:"boolean"},canPublishData:{type:"boolean"},...a},["room","identity","approvalId"])},
{name:"livekit.webhook.verify",risk:"READ",description:"Verify and decode a raw LiveKit webhook using the official SDK.",inputSchema:o({rawBody:{type:"string",maxLength:1048576},authorization:{type:"string",minLength:1,maxLength:8192}},["rawBody","authorization"])}];
const v:Record<string,z.ZodTypeAny>={
"livekit.room.list":z.object({names:z.array(id).max(50).optional()}).strict(),"livekit.room.create":z.object({name:id,emptyTimeout:z.number().int().min(0).max(86400).optional(),maxParticipants:z.number().int().min(1).max(10000).optional(),metadata:meta.optional(),approvalId:approval}).strict(),"livekit.room.metadata.update":z.object({room:id,metadata:meta,approvalId:approval}).strict(),"livekit.room.delete":z.object({room:id,approvalId:approval}).strict(),"livekit.participant.list":z.object({room:id}).strict(),"livekit.participant.get":z.object({room:id,identity:id}).strict(),"livekit.participant.permissions.update":z.object({room:id,identity:id,canPublish:z.boolean().optional(),canSubscribe:z.boolean().optional(),canPublishData:z.boolean().optional(),approvalId:approval}).strict().refine(x=>x.canPublish!==undefined||x.canSubscribe!==undefined||x.canPublishData!==undefined,"At least one permission must be specified"),"livekit.participant.remove":z.object({room:id,identity:id,approvalId:approval}).strict(),"livekit.track.mute":z.object({room:id,identity:id,trackSid:id,muted:z.boolean(),approvalId:approval}).strict(),"livekit.data.send":z.object({room:id,text:z.string().max(65536),reliable:z.boolean().default(true),destinationIdentities:z.array(id).max(100).optional(),topic:z.string().max(255).optional(),approvalId:approval}).strict(),"livekit.access_token.issue":z.object({room:id,identity:id,ttlSeconds:z.number().int().min(60).max(86400).default(3600),name:z.string().max(255).optional(),metadata:meta.optional(),canPublish:z.boolean().default(true),canSubscribe:z.boolean().default(true),canPublishData:z.boolean().default(true),approvalId:approval}).strict(),"livekit.webhook.verify":z.object({rawBody:z.string().max(1048576),authorization:z.string().min(1).max(8192)}).strict()};
export class ToolRouter{constructor(private client=new LiveKitClient(loadConfig()),private config:Config=loadConfig()){} async execute(name:string,raw:unknown){const d=toolDefs.find(x=>x.name===name);if(!d)throw new Error("Unknown tool");const i:any=v[name].parse(raw??{});enforceApproval(this.config,d.risk,name,i);switch(name){case"livekit.room.list":return this.client.room.listRooms(i.names);case"livekit.room.create":return this.client.room.createRoom({name:i.name,emptyTimeout:i.emptyTimeout,maxParticipants:i.maxParticipants,metadata:i.metadata});case"livekit.room.metadata.update":return this.client.room.updateRoomMetadata(i.room,i.metadata);case"livekit.room.delete":return this.client.room.deleteRoom(i.room);case"livekit.participant.list":return this.client.room.listParticipants(i.room);case"livekit.participant.get":return this.client.room.getParticipant(i.room,i.identity);case"livekit.participant.permissions.update":return this.client.room.updateParticipant(i.room,i.identity,undefined,{canPublish:i.canPublish,canSubscribe:i.canSubscribe,canPublishData:i.canPublishData});case"livekit.participant.remove":return this.client.room.removeParticipant(i.room,i.identity);case"livekit.track.mute":return this.client.room.mutePublishedTrack(i.room,i.identity,i.trackSid,i.muted);case"livekit.data.send":return this.client.room.sendData(i.room,new TextEncoder().encode(i.text),i.reliable?DataPacket_Kind.RELIABLE:DataPacket_Kind.LOSSY,i.destinationIdentities,i.topic);case"livekit.access_token.issue":return this.client.issueJoinToken(i);case"livekit.webhook.verify":return this.client.verifyWebhook(i.rawBody,i.authorization);default:throw new Error("Tool not implemented");}}}
