import { z } from "zod";import type { Risk } from "./policy.js";
const key=z.string().min(1).max(400),page=z.number().int().min(1).max(100000).optional(),pageSize=z.number().int().min(1).max(500).optional();const obj=(properties:Record<string,unknown>,required:string[]=[])=>({type:"object",additionalProperties:false,properties,...(required.length?{required}:{})});export type ToolDef={name:string;upstream:string;risk:Risk;description:string;schema:z.ZodTypeAny;inputSchema:Record<string,unknown>};
export const TOOLS:ToolDef[]=[
{name:"sonarqube.project.search",upstream:"search_my_sonarqube_projects",risk:"READ",description:"Search projects visible to the user.",schema:z.object({q:z.string().max(200).optional(),pageIndex:page,pageSize}).strict(),inputSchema:obj({q:{type:"string",maxLength:200},pageIndex:{type:"integer",minimum:1},pageSize:{type:"integer",minimum:1,maximum:500}})},
{name:"sonarqube.branch.list",upstream:"list_branches",risk:"READ",description:"List analyzed branches.",schema:z.object({projectKey:key,branchTypes:z.enum(["ALL","LONG","SHORT"]).optional()}).strict(),inputSchema:obj({projectKey:{type:"string"},branchTypes:{type:"string",enum:["ALL","LONG","SHORT"]}},["projectKey"])},
{name:"sonarqube.pull_request.list",upstream:"list_pull_requests",risk:"READ",description:"List analyzed pull requests.",schema:z.object({projectKey:key}).strict(),inputSchema:obj({projectKey:{type:"string"}},["projectKey"])},
{name:"sonarqube.issue.search",upstream:"search_sonar_issues_in_projects",risk:"READ",description:"Search issues.",schema:z.object({projectKeys:z.array(key).max(50).optional(),branch:z.string().max(300).optional(),pullRequest:z.string().max(100).optional(),severities:z.array(z.enum(["INFO","LOW","MEDIUM","HIGH","BLOCKER"])).max(5).optional(),impactSoftwareQualities:z.array(z.enum(["MAINTAINABILITY","RELIABILITY","SECURITY"])).max(3).optional(),issueStatuses:z.array(z.enum(["OPEN","CONFIRMED","FALSE_POSITIVE","ACCEPTED","FIXED","IN_SANDBOX"])).max(6).optional(),issueKey:key.optional(),inNewCodePeriod:z.boolean().optional(),pageIndex:page,pageSize}).strict(),inputSchema:obj({projectKeys:{type:"array",maxItems:50,items:{type:"string"}},branch:{type:"string"},pullRequest:{type:"string"},severities:{type:"array",items:{type:"string",enum:["INFO","LOW","MEDIUM","HIGH","BLOCKER"]}},impactSoftwareQualities:{type:"array",items:{type:"string",enum:["MAINTAINABILITY","RELIABILITY","SECURITY"]}},issueStatuses:{type:"array",items:{type:"string",enum:["OPEN","CONFIRMED","FALSE_POSITIVE","ACCEPTED","FIXED","IN_SANDBOX"]}},issueKey:{type:"string"},inNewCodePeriod:{type:"boolean"},pageIndex:{type:"integer",minimum:1},pageSize:{type:"integer",minimum:1,maximum:500}})},
{name:"sonarqube.issue.status.change",upstream:"change_sonar_issue_status",risk:"WRITE",description:"Accept, mark false-positive, or reopen an issue.",schema:z.object({key,status:z.enum(["accept","falsepositive","reopen"]),comment:z.string().max(1000).optional()}).strict(),inputSchema:obj({key:{type:"string"},status:{type:"string",enum:["accept","falsepositive","reopen"]},comment:{type:"string",maxLength:1000}},["key","status"])},
{name:"sonarqube.security_hotspot.search",upstream:"search_security_hotspots",risk:"READ",description:"Search security hotspots.",schema:z.object({projectKey:key,hotspotKeys:z.array(key).max(50).optional(),branch:z.string().max(300).optional(),pullRequest:z.string().max(100).optional(),files:z.array(z.string().min(1).max(1000)).max(100).optional(),status:z.enum(["TO_REVIEW","REVIEWED"]).optional(),resolution:z.enum(["FIXED","SAFE","ACKNOWLEDGED"]).optional(),sinceLeakPeriod:z.boolean().optional(),onlyMine:z.boolean().optional(),pageIndex:page,pageSize}).strict(),inputSchema:obj({projectKey:{type:"string"},hotspotKeys:{type:"array",maxItems:50,items:{type:"string"}},branch:{type:"string"},pullRequest:{type:"string"},files:{type:"array",maxItems:100,items:{type:"string"}},status:{type:"string",enum:["TO_REVIEW","REVIEWED"]},resolution:{type:"string",enum:["FIXED","SAFE","ACKNOWLEDGED"]},sinceLeakPeriod:{type:"boolean"},onlyMine:{type:"boolean"},pageIndex:{type:"integer",minimum:1},pageSize:{type:"integer",minimum:1,maximum:500}},["projectKey"])},
{name:"sonarqube.security_hotspot.get",upstream:"show_security_hotspot",risk:"READ",description:"Get one security hotspot.",schema:z.object({hotspotKey:key}).strict(),inputSchema:obj({hotspotKey:{type:"string"}},["hotspotKey"])},
{name:"sonarqube.security_hotspot.status.change",upstream:"change_security_hotspot_status",risk:"HIGH_RISK",description:"Review or reopen a security hotspot.",schema:z.object({hotspotKey:key,status:z.enum(["TO_REVIEW","REVIEWED"]),resolution:z.enum(["FIXED","SAFE","ACKNOWLEDGED"]).optional(),comment:z.string().max(1000).optional()}).strict().superRefine((v,c)=>{if(v.status==="REVIEWED"&&!v.resolution)c.addIssue({code:z.ZodIssueCode.custom,message:"resolution is required when status is REVIEWED",path:["resolution"]});}),inputSchema:obj({hotspotKey:{type:"string"},status:{type:"string",enum:["TO_REVIEW","REVIEWED"]},resolution:{type:"string",enum:["FIXED","SAFE","ACKNOWLEDGED"]},comment:{type:"string",maxLength:1000}},["hotspotKey","status"])},
{name:"sonarqube.measure.get",upstream:"get_component_measures",risk:"READ",description:"Get project/component measures.",schema:z.object({projectKey:key,branch:z.string().max(300).optional(),metricKeys:z.array(z.string().min(1).max(100)).max(100).optional(),pullRequest:z.string().max(100).optional()}).strict(),inputSchema:obj({projectKey:{type:"string"},branch:{type:"string"},metricKeys:{type:"array",maxItems:100,items:{type:"string"}},pullRequest:{type:"string"}},["projectKey"])},
{name:"sonarqube.metric.search",upstream:"search_metrics",risk:"READ",description:"Search metrics.",schema:z.object({pageIndex:page,pageSize}).strict(),inputSchema:obj({pageIndex:{type:"integer",minimum:1},pageSize:{type:"integer",minimum:1,maximum:500}})},
{name:"sonarqube.quality_gate.status.get",upstream:"get_project_quality_gate_status",risk:"READ",description:"Get quality gate status.",schema:z.object({projectKey:key.optional(),projectId:key.optional(),analysisId:key.optional(),branch:z.string().max(300).optional(),pullRequest:z.string().max(100).optional()}).strict().refine(v=>Object.keys(v).length>0,"At least one selector is required."),inputSchema:obj({projectKey:{type:"string"},projectId:{type:"string"},analysisId:{type:"string"},branch:{type:"string"},pullRequest:{type:"string"}})},
{name:"sonarqube.quality_gate.list",upstream:"list_quality_gates",risk:"READ",description:"List quality gates.",schema:z.object({}).strict(),inputSchema:obj({})},
{name:"sonarqube.rule.get",upstream:"show_rule",risk:"READ",description:"Get rule details.",schema:z.object({key}).strict(),inputSchema:obj({key:{type:"string"}},["key"])},
{name:"sonarqube.language.list",upstream:"list_languages",risk:"READ",description:"List supported languages.",schema:z.object({q:z.string().max(100).optional()}).strict(),inputSchema:obj({q:{type:"string",maxLength:100}})},
{name:"sonarqube.duplication.file.search",upstream:"search_duplicated_files",risk:"READ",description:"Search duplicated files with bounded pagination.",schema:z.object({projectKey:key,branch:z.string().max(300).optional(),pullRequest:z.string().max(100).optional(),pageIndex:z.number().int().min(1).optional(),pageSize:z.number().int().min(1).max(500).default(100)}).strict(),inputSchema:obj({projectKey:{type:"string"},branch:{type:"string"},pullRequest:{type:"string"},pageIndex:{type:"integer",minimum:1},pageSize:{type:"integer",minimum:1,maximum:500}},["projectKey"])},
{name:"sonarqube.duplication.get",upstream:"get_duplications",risk:"READ",description:"Get duplication blocks for a file/component.",schema:z.object({key,branch:z.string().max(300).optional(),pullRequest:z.string().max(100).optional()}).strict(),inputSchema:obj({key:{type:"string"},branch:{type:"string"},pullRequest:{type:"string"}},["key"])}];export const TOOL_MAP=new Map(TOOLS.map(t=>[t.name,t]));
