const APPROVAL={type:'string',pattern:'^[a-f0-9]{64}$',minLength:64,maxLength:64};
const DOC_ID={type:'string',minLength:1,maxLength:512};
const WORKSPACE={type:'string',minLength:1,maxLength:200};
export const TOOL_DEFINITIONS=[
{name:'sanity.content.query',description:'Execute a GROQ query. Primary: official Sanity MCP query_documents; SDK fallback. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,required:['query'],properties:{query:{type:'string',minLength:1,maxLength:50000},params:{type:'object',maxProperties:200,additionalProperties:true},perspective:{enum:['raw','published','drafts'],default:'raw'}}}},
{name:'sanity.document.get',description:'Fetch one document by exact ID. Primary: official MCP get_document; SDK fallback. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,required:['documentId'],properties:{documentId:DOC_ID}}},
{name:'sanity.schema.get',description:'Fetch a deployed workspace schema through official Sanity MCP. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,properties:{workspaceName:WORKSPACE,schemaId:{type:'string',minLength:1,maxLength:500}}}},
{name:'sanity.schema.list',description:'List deployed schemas for configured project/dataset through official Sanity MCP. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,properties:{workspaceName:WORKSPACE}}},
{name:'sanity.release.list',description:'List content releases through official Sanity MCP. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,properties:{state:{enum:['active','scheduled','published','archived']}}}},
{name:'sanity.document.create_draft',description:'Create draft documents through official Sanity MCP. Risk: WRITE. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['documents','approval_token'],properties:{documents:{type:'array',minItems:1,maxItems:50,items:{type:'object',required:['_type'],additionalProperties:true}},approval_token:APPROVAL}}},
{name:'sanity.document.patch',description:'Apply structured patches through official Sanity MCP. Risk: WRITE. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['patches','approval_token'],properties:{patches:{type:'array',minItems:1,maxItems:50,items:{type:'object',additionalProperties:true}},approval_token:APPROVAL}}},
{name:'sanity.document.publish',description:'Publish draft documents. Risk: HIGH_RISK. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['documentIds','approval_token'],properties:{documentIds:{type:'array',minItems:1,maxItems:50,items:DOC_ID},approval_token:APPROVAL}}},
{name:'sanity.document.unpublish',description:'Unpublish live documents. Risk: HIGH_RISK. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['documentIds','approval_token'],properties:{documentIds:{type:'array',minItems:1,maxItems:50,items:DOC_ID},approval_token:APPROVAL}}},
{name:'sanity.document.discard_draft',description:'Discard draft documents. Risk: DESTRUCTIVE. Disabled by default and explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['documentIds','approval_token'],properties:{documentIds:{type:'array',minItems:1,maxItems:50,items:DOC_ID},approval_token:APPROVAL}}}
];
export function stripApproval(args={}){const{approval_token:_,...rest}=args;return rest;}
