import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema,ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { loadConfig } from "./config.js";
import { TokenProvider,VaultRestClient } from "./vault-core.js";
import { OfficialMcpTransport } from "./upstream.js";
import { authorize } from "./policy.js";
import { TOOLS,stripApproval } from "./tools.js";
const ROUTES={"vault.mount.list":["list_mounts",()=>({})],"vault.mount.create":["create_mount",p=>p],"vault.mount.delete":["delete_mount",p=>p],"vault.secret.list":["list_secrets",p=>p],"vault.secret.write":["write_secret",p=>p],"vault.secret.delete":["delete_secret",p=>p],"vault.pki.enable":["enable_pki",p=>p],"vault.pki.issuer.list":["list_pki_issuers",p=>p],"vault.pki.issuer.read":["read_pki_issuer",p=>p],"vault.pki.issuer.create":["create_pki_issuer",p=>p],"vault.pki.role.list":["list_pki_roles",p=>p],"vault.pki.role.read":["read_pki_role",p=>p],"vault.pki.role.create":["create_pki_role",p=>p],"vault.pki.role.delete":["delete_pki_role",p=>p],"vault.pki.certificate.issue":["issue_pki_certificate",p=>({...p,...(Array.isArray(p.altNames)?{altNames:p.altNames.join(",")}:{}) ,...(Array.isArray(p.ipSans)?{ipSans:p.ipSans.join(",")}:{})})]};
export function createServer({config=loadConfig(),tokens,rest,upstream}={}){const tp=tokens||new TokenProvider(config),r=rest||new VaultRestClient(config,tp),m=upstream||new OfficialMcpTransport(config,tp),s=new Server({name:"hashicorp-vault-safe-connector",version:"1.0.0"},{capabilities:{tools:{}}});s.setRequestHandler(ListToolsRequestSchema,async()=>({tools:TOOLS}));s.setRequestHandler(CallToolRequestSchema,async(req,extra)=>{const name=req.params.name,args=req.params.arguments||{},payload=stripApproval(args);try{authorize(config,name,payload,args.approval_token);let data,transport;if(name==="vault.system.health"){data=await r.health(extra?.signal);transport="rest";}else if(name==="vault.permission.check"){data=await r.capabilities(payload.paths,extra?.signal);transport="rest";}else{const route=ROUTES[name];if(!route)throw new Error(`Unknown tool: ${name}`);data=await m.call(route[0],route[1](payload));transport="official-mcp";}const out={untrusted_provider_data:true,upstream_transport:transport,secret_values_exposed:false,data};return{content:[{type:"text",text:JSON.stringify(out,null,2)}],structuredContent:out};}catch(e){const out={error:{type:e?.status===429?"RATE_LIMIT":e?.status===401||e?.status===403?"AUTHORIZATION":e?.status>=500?"PROVIDER_UNAVAILABLE":"CONNECTOR",status:e?.status,retryAfter:e?.retryAfter,retryable:e?.status===429||e?.status>=500,message:e?.message||String(e)}};return{isError:true,content:[{type:"text",text:JSON.stringify(out)}]};}});return s;}
if(import.meta.url===`file://${process.argv[1]}`){const s=createServer();await s.connect(new StdioServerTransport());}
