const PATH={type:"string",minLength:1,maxLength:1000,pattern:"^[A-Za-z0-9._~/-]+$"},NAME={type:"string",minLength:1,maxLength:255,pattern:"^[A-Za-z0-9._-]+$"},APPROVAL={type:"string",minLength:64,maxLength:64,pattern:"^[a-f0-9]{64}$"};
export const TOOLS=[
{name:"vault.system.health",description:"Get Vault health/seal status via official HTTP API. READ.",inputSchema:{type:"object",additionalProperties:false,properties:{}}},
{name:"vault.permission.check",description:"Check current token capabilities for explicit Vault paths. READ.",inputSchema:{type:"object",additionalProperties:false,required:["paths"],properties:{paths:{type:"array",minItems:1,maxItems:50,items:PATH}}}},
{name:"vault.mount.list",description:"List Vault mounts through official Vault MCP. READ.",inputSchema:{type:"object",additionalProperties:false,properties:{}}},
{name:"vault.mount.create",description:"Create KV v1/v2 mount through official Vault MCP. HIGH_RISK; approval required.",inputSchema:{type:"object",additionalProperties:false,required:["type","path","approval_token"],properties:{type:{enum:["kv","kv2"]},path:PATH,description:{type:"string",maxLength:1000},approval_token:APPROVAL}}},
{name:"vault.mount.delete",description:"Delete an entire mount. DESTRUCTIVE; disabled by default and approval required.",inputSchema:{type:"object",additionalProperties:false,required:["path","approval_token"],properties:{path:PATH,approval_token:APPROVAL}}},
{name:"vault.secret.list",description:"List KV secret paths without reading values via official Vault MCP. READ.",inputSchema:{type:"object",additionalProperties:false,required:["mount"],properties:{mount:PATH,path:PATH}}},
{name:"vault.secret.write",description:"Write one KV key/value via official Vault MCP. WRITE; approval required.",inputSchema:{type:"object",additionalProperties:false,required:["mount","path","key","value","approval_token"],properties:{mount:PATH,path:PATH,key:NAME,value:{type:"string",maxLength:1048576},approval_token:APPROVAL}}},
{name:"vault.secret.delete",description:"Delete a KV secret or one key. DESTRUCTIVE; disabled by default and approval required.",inputSchema:{type:"object",additionalProperties:false,required:["mount","path","approval_token"],properties:{mount:PATH,path:PATH,key:NAME,approval_token:APPROVAL}}},
{name:"vault.pki.enable",description:"Enable PKI engine via official Vault MCP. HIGH_RISK; approval required.",inputSchema:{type:"object",additionalProperties:false,required:["path","approval_token"],properties:{path:PATH,description:{type:"string",maxLength:1000},approval_token:APPROVAL}}},
{name:"vault.pki.issuer.list",description:"List PKI issuers via official Vault MCP. READ.",inputSchema:{type:"object",additionalProperties:false,required:["mount"],properties:{mount:PATH}}},
{name:"vault.pki.issuer.read",description:"Read PKI issuer metadata via official Vault MCP. READ.",inputSchema:{type:"object",additionalProperties:false,required:["mount","name"],properties:{mount:PATH,name:NAME}}},
{name:"vault.pki.issuer.create",description:"Create PKI issuer via official Vault MCP. HIGH_RISK; approval required.",inputSchema:{type:"object",additionalProperties:false,required:["mount","name","certificate","privateKey","approval_token"],properties:{mount:PATH,name:NAME,certificate:{type:"string",minLength:1,maxLength:1048576},privateKey:{type:"string",minLength:1,maxLength:1048576},approval_token:APPROVAL}}},
{name:"vault.pki.role.list",description:"List PKI roles via official Vault MCP. READ.",inputSchema:{type:"object",additionalProperties:false,required:["mount"],properties:{mount:PATH}}},
{name:"vault.pki.role.read",description:"Read PKI role via official Vault MCP. READ.",inputSchema:{type:"object",additionalProperties:false,required:["mount","name"],properties:{mount:PATH,name:NAME}}},
{name:"vault.pki.role.create",description:"Create/update PKI role via official Vault MCP. HIGH_RISK; approval required.",inputSchema:{type:"object",additionalProperties:false,required:["mount","name","config","approval_token"],properties:{mount:PATH,name:NAME,config:{type:"object",minProperties:1,maxProperties:100,additionalProperties:true},approval_token:APPROVAL}}},
{name:"vault.pki.role.delete",description:"Delete PKI role via official Vault MCP. DESTRUCTIVE; disabled by default and approval required.",inputSchema:{type:"object",additionalProperties:false,required:["mount","name","approval_token"],properties:{mount:PATH,name:NAME,approval_token:APPROVAL}}},
{name:"vault.pki.certificate.issue",description:"Issue certificate via official Vault MCP. HIGH_RISK; approval required.",inputSchema:{type:"object",additionalProperties:false,required:["mount","role","commonName","approval_token"],properties:{mount:PATH,role:NAME,commonName:{type:"string",minLength:1,maxLength:255},altNames:{type:"array",maxItems:50,items:{type:"string",maxLength:255}},ipSans:{type:"array",maxItems:50,items:{type:"string",maxLength:64}},ttl:{type:"string",maxLength:64},approval_token:APPROVAL}}}
];
export function stripApproval(args={}){const {approval_token:_a,...payload}=args;return payload;}
