const RETRYABLE=new Set([429,502,503,504]);

export class TokenProvider {
  constructor(config,fetchImpl=globalThis.fetch){this.config=config;this.fetch=fetchImpl;this.cached=null;}
  async getToken(){if(this.config.staticToken)return this.config.staticToken;if(this.cached&&this.cached.expires>Date.now()+30000)return this.cached.token;const c=new AbortController(),t=setTimeout(()=>c.abort(),this.config.timeoutMs);try{const r=await this.fetch(`${this.config.vaultAddr}/v1/auth/${encodeURIComponent(this.config.approleMount)}/login`,{method:"POST",headers:{"Content-Type":"application/json",...(this.config.namespace?{"X-Vault-Namespace":this.config.namespace}:{})},body:JSON.stringify({role_id:this.config.roleId,secret_id:this.config.secretId}),signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.auth?.client_token)throw new Error(d?.errors?.join("; ")||`Vault AppRole login failed with HTTP ${r.status}`);this.cached={token:d.auth.client_token,expires:Date.now()+Math.max(60,Number(d.auth.lease_duration||300))*1000};return this.cached.token;}finally{clearTimeout(t);}}
}
export class VaultRestClient {
  constructor(config,tokens,fetchImpl=globalThis.fetch){this.config=config;this.tokens=tokens;this.fetch=fetchImpl;}
  async request(method,path,{body,signal,unauth=false}={}){let attempt=0;while(true){const token=unauth?"":await this.tokens.getToken();const timeout=AbortSignal.timeout(this.config.timeoutMs),combined=signal?AbortSignal.any([signal,timeout]):timeout;let r;try{r=await this.fetch(`${this.config.vaultAddr}${path}`,{method,headers:{Accept:"application/json",...(body!==undefined?{"Content-Type":"application/json"}:{}),...(token?{"X-Vault-Token":token}:{}),...(this.config.namespace?{"X-Vault-Namespace":this.config.namespace}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:combined});}catch(e){if(attempt>=this.config.maxRetries||combined.aborted)throw e;await new Promise(res=>setTimeout(res,Math.min(250*2**attempt,4000)));attempt++;continue;}const text=await r.text();let d=null;if(text){try{d=JSON.parse(text)}catch{d={raw:text}}}if(r.ok)return d;if(RETRYABLE.has(r.status)&&attempt<this.config.maxRetries){const ra=r.headers.get("retry-after"),ms=ra&&/^\d+$/.test(ra)?Math.min(Number(ra)*1000,10000):Math.min(250*2**attempt,4000);await new Promise(res=>setTimeout(res,ms));attempt++;continue;}const e=new Error(d?.errors?.join("; ")||`Vault HTTP ${r.status}`);e.status=r.status;e.retryAfter=r.headers.get("retry-after")||undefined;throw e;}}
  health(signal){return this.request("GET","/v1/sys/health",{signal,unauth:true});}
  capabilities(paths,signal){return this.request("POST","/v1/sys/capabilities-self",{body:{paths},signal});}
}
