import crypto from 'node:crypto';

export type Risk='READ'|'WRITE'|'DESTRUCTIVE';
export class ConnectorError extends Error { constructor(public code:string,message:string,public status?:number,public retryAfter?:number){super(message)} }
export type Config={publicKey:string;secretKey:string;baseUrl:string;timeoutMs:number;maxRetries:number;allowWrites:boolean;allowDestructive:boolean};
export function loadConfig(env=process.env):Config { const publicKey=env.UPLOADCARE_PUBLIC_KEY?.trim(),secretKey=env.UPLOADCARE_SECRET_KEY?.trim(); if(!publicKey||!secretKey) throw new ConnectorError('AUTH_CONFIG','UPLOADCARE_PUBLIC_KEY and UPLOADCARE_SECRET_KEY are required'); const baseUrl=env.UPLOADCARE_API_BASE||'https://api.uploadcare.com'; const u=new URL(baseUrl); if(u.protocol!=='https:'||u.hostname!=='api.uploadcare.com') throw new ConnectorError('CONFIG','UPLOADCARE_API_BASE must be https://api.uploadcare.com'); return {publicKey,secretKey,baseUrl:u.origin,timeoutMs:num(env.UPLOADCARE_TIMEOUT_MS,15000,1000,60000),maxRetries:num(env.UPLOADCARE_MAX_RETRIES,3,0,5),allowWrites:env.UPLOADCARE_ALLOW_WRITES==='true',allowDestructive:env.UPLOADCARE_ALLOW_DESTRUCTIVE==='true'} }
function num(v:string|undefined,d:number,min:number,max:number){const n=v?Number(v):d;if(!Number.isInteger(n)||n<min||n>max)throw new ConnectorError('CONFIG','Invalid numeric configuration');return n}
export function requireRisk(c:Config,r:Risk,approved=false){if(r==='WRITE'&&!c.allowWrites)throw new ConnectorError('PERMISSION_DENIED','Writes are disabled');if(r==='DESTRUCTIVE'&&(!c.allowDestructive||!approved))throw new ConnectorError('APPROVAL_REQUIRED','Destructive action requires enablement and explicit approval')}
export function uuid(v:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v))throw new ConnectorError('VALIDATION','Invalid file UUID');return v}
export class UploadcareClient { constructor(public config:Config,private fetcher:typeof fetch=fetch){}
 private headers(method:string,path:string,body:string){const date=new Date().toUTCString(),ct='application/json',md5=crypto.createHash('md5').update(body).digest('hex'),sign=[method,md5,ct,date,path].join('\n'),sig=crypto.createHmac('sha1',this.config.secretKey).update(sign).digest('hex');return {'Accept':'application/vnd.uploadcare-v0.7+json','Content-Type':ct,'Date':date,'Authorization':`Uploadcare ${this.config.publicKey}:${sig}`}}
 async request(method:string,path:string,body?:unknown,risk:Risk='READ',approved=false){requireRisk(this.config,risk,approved);if(!path.startsWith('/')||path.includes('://'))throw new ConnectorError('VALIDATION','Invalid provider path');const payload=body===undefined?'':JSON.stringify(body);for(let attempt=0;;attempt++){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),this.config.timeoutMs);try{const res=await this.fetcher(this.config.baseUrl+path,{method,headers:this.headers(method,path,payload),body:payload||undefined,signal:ctl.signal});const text=await res.text();const data=text?safeJson(text):null;if(res.ok)return data;const ra=parseRetry(res.headers.get('retry-after'));if((res.status===429||res.status>=500)&&attempt<this.config.maxRetries&&risk==='READ'){await sleep(ra??Math.min(250*2**attempt,2000));continue}throw new ConnectorError(mapStatus(res.status),`Uploadcare request failed (${res.status})`,res.status,ra)}catch(e){if(e instanceof ConnectorError)throw e;if(attempt<this.config.maxRetries&&risk==='READ'){await sleep(Math.min(250*2**attempt,2000));continue}throw new ConnectorError(e instanceof Error&&e.name==='AbortError'?'TIMEOUT':'NETWORK',e instanceof Error?e.message:'Network error')}finally{clearTimeout(timer)}}}
}
function safeJson(s:string){try{return JSON.parse(s)}catch{return {raw:s}}} function parseRetry(v:string|null){if(!v)return undefined;const n=Number(v);if(Number.isFinite(n))return Math.max(0,n*1000);const d=Date.parse(v);return Number.isNaN(d)?undefined:Math.max(0,d-Date.now())} function mapStatus(s:number){return s===401?'AUTHENTICATION':s===403?'PERMISSION_DENIED':s===404?'NOT_FOUND':s===429?'RATE_LIMITED':s>=500?'UPSTREAM':'PROVIDER_ERROR'} const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
