import {z} from 'zod';import {MapboxClient,coord,coords} from './client.js';
const point=z.object({longitude:z.number().min(-180).max(180),latitude:z.number().min(-90).max(90)}).strict();
const profile=z.enum(['driving','driving-traffic','walking','cycling']);
export type ToolDef={name:string;description:string;schema:Record<string,z.ZodTypeAny>;run:(c:MapboxClient,a:any)=>Promise<any>};
export const tools:ToolDef[]=[
{name:'mapbox.geocoding.forward',description:'Forward geocode text.',schema:{query:z.string().min(1).max(256),limit:z.number().int().min(1).max(10).default(5),language:z.string().max(100).optional(),country:z.string().max(80).optional(),autocomplete:z.boolean().default(false)},run:(c,a)=>c.get('/search/geocode/v6/forward',{q:a.query,limit:a.limit,language:a.language,country:a.country,autocomplete:a.autocomplete})},
{name:'mapbox.geocoding.reverse',description:'Reverse geocode coordinates.',schema:{...point.shape,language:z.string().max(100).optional()},run:(c,a)=>c.get('/search/geocode/v6/reverse',{longitude:a.longitude,latitude:a.latitude,language:a.language})},
{name:'mapbox.directions.route',description:'Get a route between coordinates.',schema:{profile,points:z.array(point).min(2).max(25),alternatives:z.boolean().default(false),steps:z.boolean().default(false)},run:(c,a)=>c.get(`/directions/v5/mapbox/${a.profile}/${coords(a.points)}`,{alternatives:a.alternatives,steps:a.steps,geometries:'geojson',overview:'simplified'})},
{name:'mapbox.matrix.calculate',description:'Calculate travel-time/distance matrix.',schema:{profile,points:z.array(point).min(2).max(25)},run:(c,a)=>{if(a.profile==='driving-traffic'&&a.points.length>10)throw new Error('driving-traffic matrix supports at most 10 coordinates');return c.get(`/directions-matrix/v1/mapbox/${a.profile}/${coords(a.points)}`,{annotations:'duration,distance'})}},
{name:'mapbox.isochrone.calculate',description:'Calculate reachable-area contours.',schema:{profile,origin:point,minutes:z.array(z.number().int().min(1).max(60)).min(1).max(4)},run:(c,a)=>c.get(`/isochrone/v1/mapbox/${a.profile}/${coord(a.origin)}`,{contours_minutes:a.minutes.join(','),polygons:true})},
{name:'mapbox.optimization.trip',description:'Optimize waypoint order.',schema:{profile,points:z.array(point).min(2).max(12),roundtrip:z.boolean().default(true)},run:(c,a)=>c.get(`/optimized-trips/v1/mapbox/${a.profile}/${coords(a.points)}`,{roundtrip:a.roundtrip,geometries:'geojson',overview:'simplified'})},
{name:'mapbox.map_matching.match',description:'Snap a GPS trace to roads/paths.',schema:{profile,points:z.array(point).min(2).max(100)},run:(c,a)=>c.get(`/matching/v5/mapbox/${a.profile}/${coords(a.points)}`,{geometries:'geojson',overview:'simplified'})},
{name:'mapbox.tilequery.query',description:'Query vector-tile features near a coordinate.',schema:{tileset:z.string().regex(/^[A-Za-z0-9_.-]+$/).max(200),location:point,limit:z.number().int().min(1).max(50).default(10),radius:z.number().min(0).max(10000).optional()},run:(c,a)=>c.get(`/v4/${a.tileset}/tilequery/${coord(a.location)}.json`,{limit:a.limit,radius:a.radius})}
];
export const risk:Record<string,{permission:'READ';approval:false}>=Object.fromEntries(tools.map(t=>[t.name,{permission:'READ',approval:false}]));
