import { UnleashClient } from "./client.js";
import { OfficialMcpBridge } from "./official-mcp.js";
import { approve, flagName, id, limit, page, type Risk, ValidationError } from "./security.js";
type Spec={name:string;description:string;risk:Risk;inputSchema:any;annotations:any};
const obj=(properties:any,required:string[]=[])=>({type:"object",additionalProperties:false,properties,required}); const str=(d:string)=>({type:"string",description:d}); const grant={approvalId:str("Opaque host-supplied approval grant; never a provider credential.")};
export const tools:Spec[]=[
{name:"unleash.project.list",risk:"READ",description:"READ: list projects visible to the configured token.",inputSchema:obj({}),annotations:{readOnlyHint:true}},
{name:"unleash.flag.list",risk:"READ",description:"READ: list feature flags in a project with bounded pagination.",inputSchema:obj({projectId:str("Project ID"),page:{type:"integer",minimum:1},limit:{type:"integer",minimum:1,maximum:100},archived:{type:"boolean"}},["projectId"]),annotations:{readOnlyHint:true}},
{name:"unleash.flag.get",risk:"READ",description:"READ: get feature flag metadata and configuration.",inputSchema:obj({projectId:str("Project ID"),featureName:str("Feature flag name")},["projectId","featureName"]),annotations:{readOnlyHint:true}},
{name:"unleash.flag.create",risk:"WRITE",description:"WRITE: create a feature flag disabled by default.",inputSchema:obj({projectId:str("Project ID"),featureName:str("Unique flag name"),description:{type:"string",maxLength:1000},type:{type:"string",enum:["release","experiment","operational","kill-switch","permission","sunset"]},...grant},["projectId","featureName"]),annotations:{readOnlyHint:false}},
{name:"unleash.flag.environment.get",risk:"READ",description:"READ: get one flag's state and strategies in an environment.",inputSchema:obj({projectId:str("Project ID"),featureName:str("Flag"),environment:str("Environment")},["projectId","featureName","environment"]),annotations:{readOnlyHint:true}},
{name:"unleash.flag.environment.enable",risk:"HIGH_RISK",description:"HIGH_RISK: enable a flag in an environment; production exposure requires explicit human approval.",inputSchema:obj({projectId:str("Project ID"),featureName:str("Flag"),environment:str("Environment"),...grant},["projectId","featureName","environment","approvalId"]),annotations:{readOnlyHint:false}},
{name:"unleash.flag.environment.disable",risk:"HIGH_RISK",description:"HIGH_RISK: disable a flag in an environment; may change live behavior.",inputSchema:obj({projectId:str("Project ID"),featureName:str("Flag"),environment:str("Environment"),...grant},["projectId","featureName","environment","approvalId"]),annotations:{readOnlyHint:false}},
{name:"unleash.strategy.list",risk:"READ",description:"READ: list activation strategies for a flag environment.",inputSchema:obj({projectId:str("Project ID"),featureName:str("Flag"),environment:str("Environment")},["projectId","featureName","environment"]),annotations:{readOnlyHint:true}},
{name:"unleash.strategy.add",risk:"HIGH_RISK",description:"HIGH_RISK: add a bounded activation strategy. For flexibleRollout, rollout is 0-100 and stickiness is explicit.",inputSchema:obj({projectId:str("Project ID"),featureName:str("Flag"),environment:str("Environment"),strategy:{type:"string",enum:["default","userWithId","remoteAddress","applicationHostname","flexibleRollout"]},rollout:{type:"integer",minimum:0,maximum:100},stickiness:{type:"string",enum:["default","random","userId","sessionId"]},...grant},["projectId","featureName","environment","strategy","approvalId"]),annotations:{readOnlyHint:false}},
{name:"unleash.strategy.remove",risk:"HIGH_RISK",description:"HIGH_RISK: remove an activation strategy; may change live traffic exposure.",inputSchema:obj({projectId:str("Project ID"),featureName:str("Flag"),environment:str("Environment"),strategyId:str("Strategy UUID"),...grant},["projectId","featureName","environment","strategyId","approvalId"]),annotations:{readOnlyHint:false}},
{name:"unleash.flag.archive.validate",risk:"READ",description:"READ/recommend: validate archive impact before execution.",inputSchema:obj({projectId:str("Project ID"),features:{type:"array",minItems:1,maxItems:50,uniqueItems:true,items:{type:"string"}}},["projectId","features"]),annotations:{readOnlyHint:true}},
{name:"unleash.flag.archive",risk:"HIGH_RISK",description:"HIGH_RISK: archive flags after impact review.",inputSchema:obj({projectId:str("Project ID"),features:{type:"array",minItems:1,maxItems:50,uniqueItems:true,items:{type:"string"}},...grant},["projectId","features","approvalId"]),annotations:{readOnlyHint:false}},
{name:"unleash.flag.delete",risk:"DESTRUCTIVE",description:"DESTRUCTIVE: permanently delete already archived flags; disabled by default.",inputSchema:obj({projectId:str("Project ID"),features:{type:"array",minItems:1,maxItems:50,uniqueItems:true,items:{type:"string"}},...grant},["projectId","features","approvalId"]),annotations:{readOnlyHint:false,destructiveHint:true}}
];
const enc=(x:string)=>encodeURIComponent(x); const ids=(a:any)=>({p:enc(id(a.projectId,"projectId")),f:enc(flagName(a.featureName)),e:a.environment?enc(id(a.environment,"environment")):""});
export class ToolRouter { constructor(private api=new UnleashClient(),private mcp=new OfficialMcpBridge()){} async execute(name:string,a:any){ const spec=tools.find(t=>t.name===name); if(!spec)throw new ValidationError("Unknown tool."); approve(spec.risk,a?.approvalId);
 switch(name){
 case "unleash.project.list": {const m=await this.mcp.call("list_projects",{}); if(m.handled)return m.data; return this.api.get("/projects");}
 case "unleash.flag.list": {const {p}=ids(a); const q=new URLSearchParams({page:String(page(a.page)),limit:String(limit(a.limit))}); if(a.archived!=null)q.set("archived",String(Boolean(a.archived))); const m=await this.mcp.call("list_flags",{projectId:a.projectId}); if(m.handled&&!a.page&&!a.limit&&a.archived==null)return m.data; return this.api.get(`/projects/${p}/features?${q}`);}
 case "unleash.flag.get": {const {p,f}=ids(a); return this.api.get(`/projects/${p}/features/${f}`);}
 case "unleash.flag.create": {const {p}=ids(a); const args={projectId:a.projectId,name:flagName(a.featureName),description:a.description,type:a.type}; const m=await this.mcp.call("create_flag",Object.fromEntries(Object.entries(args).filter(([,v])=>v!==undefined))); if(m.handled)return m.data; return this.api.post(`/projects/${p}/features`,{name:args.name,...(a.description?{description:String(a.description)}:{}),...(a.type?{type:a.type}:{})});}
 case "unleash.flag.environment.get": {const {p,f,e}=ids(a); const m=await this.mcp.call("get_flag_state",{projectId:a.projectId,flagName:a.featureName,environment:a.environment}); if(m.handled)return m.data; return this.api.get(`/projects/${p}/features/${f}/environments/${e}`);}
 case "unleash.flag.environment.enable": case "unleash.flag.environment.disable": {const {p,f,e}=ids(a); const enabled=name.endsWith("enable"); const m=await this.mcp.call("toggle_flag_environment",{projectId:a.projectId,flagName:a.featureName,environment:a.environment,enabled}); if(m.handled)return m.data; return this.api.post(`/projects/${p}/features/${f}/environments/${e}/${enabled?"on":"off"}`);}
 case "unleash.strategy.list": {const {p,f,e}=ids(a); return this.api.get(`/projects/${p}/features/${f}/environments/${e}/strategies`);}
 case "unleash.strategy.add": {const {p,f,e}=ids(a); const parameters=a.strategy==="flexibleRollout"?{rollout:String(a.rollout??100),stickiness:a.stickiness||"default",groupId:a.featureName}:undefined; return this.api.post(`/projects/${p}/features/${f}/environments/${e}/strategies`,{name:a.strategy,...(parameters?{parameters}:{})});}
 case "unleash.strategy.remove": {const {p,f,e}=ids(a); const m=await this.mcp.call("remove_flag_strategy",{projectId:a.projectId,flagName:a.featureName,environment:a.environment,strategyId:a.strategyId}); if(m.handled)return m.data; return this.api.delete(`/projects/${p}/features/${f}/environments/${e}/strategies/${enc(id(a.strategyId,"strategyId"))}`);}
 case "unleash.flag.archive.validate": {const {p}=ids(a); return this.api.post(`/projects/${p}/archive/validate`,{features:a.features.map(flagName)});}
 case "unleash.flag.archive": {const {p}=ids(a); return this.api.post(`/projects/${p}/archive`,{features:a.features.map(flagName)});}
 case "unleash.flag.delete": {const {p}=ids(a); return this.api.post(`/projects/${p}/delete`,{features:a.features.map(flagName)});}
 default: throw new ValidationError("Tool not implemented."); }
 }}
