const VALUE_KEYS = new Set(['secretValue','value','secretValueHidden']);
function sanitize(v){if(Array.isArray(v))return v.map(sanitize);if(!v||typeof v!=='object')return v;const o={};for(const [k,c] of Object.entries(v)){if(VALUE_KEYS.has(k))continue;o[k]=sanitize(c);}return o;}
function sanitizeSecret(v){const o=sanitize(v);if(o&&typeof o==='object'&&!Array.isArray(o))o.secretValueExposed=false;return o;}

export class InfisicalClient {
  constructor(config,sdk=null){this.config=config;this.sdk=sdk;this.authenticated=false;this.loginPromise=null;}
  async ensureSdk(){if(this.sdk)return this.sdk;const {InfisicalSDK}=await import('@infisical/sdk');this.sdk=new InfisicalSDK({siteUrl:this.config.siteUrl});return this.sdk;}
  async ensureAuth(){if(this.authenticated)return;await this.ensureSdk();if(!this.loginPromise)this.loginPromise=this.sdk.auth().universalAuth.login({clientId:this.config.clientId,clientSecret:this.config.clientSecret}).then(()=>{this.authenticated=true;}).finally(()=>{this.loginPromise=null;});await this.loginPromise;}
  async timed(fn){let t;try{return await Promise.race([fn(),new Promise((_,r)=>{t=setTimeout(()=>r(new Error(`Infisical operation timed out after ${this.config.timeoutMs}ms`)),this.config.timeoutMs);t.unref?.();})]);}finally{if(t)clearTimeout(t);}}
  async authStatus(){await this.timed(()=>this.ensureAuth());return{authenticated:true,siteUrl:this.config.siteUrl,credentialType:'machine_identity_universal_auth',credentialsExposed:false};}
  async list(args,imports=false){await this.ensureAuth();const r=await this.timed(()=>this.sdk.secrets().listSecrets({projectId:args.projectId,environment:args.environment,secretPath:args.secretPath||'/',recursive:args.recursive||false,includeImports:imports,expandSecretReferences:false,viewSecretValue:false,...(args.tagFilters?.length?{tagFilters:args.tagFilters}:{})}));return sanitize(r);}
  async get(args){await this.ensureAuth();const r=await this.timed(()=>this.sdk.secrets().getSecret({projectId:args.projectId,environment:args.environment,secretName:args.secretName,secretPath:args.secretPath||'/',type:args.type||'shared',includeImports:args.includeImports||false,expandSecretReferences:false,viewSecretValue:false,...(args.version?{version:args.version}:{})}));return sanitizeSecret(r);}
  async exists(args){try{return{exists:true,secretName:args.secretName,metadata:await this.get(args)}}catch(e){const s=e?.status??e?.statusCode??e?.response?.status;if(s===404||String(e?.message||'').toLowerCase().includes('not found'))return{exists:false,secretName:args.secretName};throw e;}}
  async create(args){await this.ensureAuth();const r=await this.timed(()=>this.sdk.secrets().createSecret(args.secretName,{projectId:args.projectId,environment:args.environment,secretValue:args.secretValue,secretPath:args.secretPath||'/',type:args.type||'shared',...(args.secretComment!==undefined?{secretComment:args.secretComment}:{}),...(args.tagIds?.length?{tagIds:args.tagIds}:{}),...(args.metadata!==undefined?{metadata:args.metadata}:{})}));return sanitizeSecret(r);}
  async update(args){await this.ensureAuth();const o={projectId:args.projectId,environment:args.environment,secretPath:args.secretPath||'/',type:args.type||'shared'};for(const k of ['secretValue','newSecretName','secretComment','tagIds','metadata'])if(Object.prototype.hasOwnProperty.call(args,k))o[k]=args[k];const r=await this.timed(()=>this.sdk.secrets().updateSecret(args.secretName,o));return sanitizeSecret(r);}
  async delete(args){await this.ensureAuth();const r=await this.timed(()=>this.sdk.secrets().deleteSecret(args.secretName,{projectId:args.projectId,environment:args.environment,secretPath:args.secretPath||'/',type:args.type||'shared'}));return sanitizeSecret(r);}
}
