const scope={projectId:{type:'string',minLength:1,maxLength:200},environment:{type:'string',minLength:1,maxLength:100,pattern:'^[A-Za-z0-9._-]+$'},secretPath:{type:'string',minLength:1,maxLength:1000,pattern:'^/'}};
const name={type:'string',minLength:1,maxLength:500};const approval={type:'string',minLength:64,maxLength:64,pattern:'^[a-f0-9]{64}$'};
export const TOOL_DEFINITIONS=[
{name:'infisical.auth.status',description:'Verify connector authentication without revealing credentials. Risk READ.',inputSchema:{type:'object',additionalProperties:false,properties:{}}},
{name:'infisical.secret.list_metadata',description:'List secret metadata with values hidden. Risk READ.',inputSchema:{type:'object',additionalProperties:false,required:['projectId','environment'],properties:{...scope,recursive:{type:'boolean'},tagFilters:{type:'array',maxItems:50,items:{type:'string',maxLength:200}}}}},
{name:'infisical.secret.list_imported_metadata',description:'List secret metadata including imports, never values. Risk READ.',inputSchema:{type:'object',additionalProperties:false,required:['projectId','environment'],properties:{...scope,recursive:{type:'boolean'},tagFilters:{type:'array',maxItems:50,items:{type:'string',maxLength:200}}}}},
{name:'infisical.secret.get_metadata',description:'Get one secret metadata record without its value. Risk READ.',inputSchema:{type:'object',additionalProperties:false,required:['projectId','environment','secretName'],properties:{...scope,secretName:name,type:{enum:['shared','personal']},includeImports:{type:'boolean'},version:{type:'integer',minimum:1}}}},
{name:'infisical.secret.exists',description:'Check whether a secret exists without returning its value. Risk READ.',inputSchema:{type:'object',additionalProperties:false,required:['projectId','environment','secretName'],properties:{...scope,secretName:name,type:{enum:['shared','personal']},includeImports:{type:'boolean'}}}},
{name:'infisical.secret.create',description:'Create a secret. Response value is stripped. Risk WRITE; explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['projectId','environment','secretName','secretValue','approval_token'],properties:{...scope,secretName:name,secretValue:{type:'string',maxLength:1048576},secretComment:{type:'string',maxLength:10000},type:{enum:['shared','personal']},tagIds:{type:'array',maxItems:50,items:{type:'string',maxLength:200}},metadata:{type:'object',maxProperties:50,additionalProperties:true},approval_token:approval}}},
{name:'infisical.secret.update',description:'Update secret value/name/metadata. Response value is stripped. Risk WRITE; explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['projectId','environment','secretName','approval_token'],properties:{...scope,secretName:name,secretValue:{type:'string',maxLength:1048576},newSecretName:name,secretComment:{type:'string',maxLength:10000},type:{enum:['shared','personal']},tagIds:{type:'array',maxItems:50,items:{type:'string',maxLength:200}},metadata:{type:'object',maxProperties:50,additionalProperties:true},approval_token:approval}}},
{name:'infisical.secret.delete',description:'Delete a secret. Risk DESTRUCTIVE; disabled by default and explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['projectId','environment','secretName','approval_token'],properties:{...scope,secretName:name,type:{enum:['shared','personal']},approval_token:approval}}}
];
export function withoutApproval(args={}){const {approval_token:_x,...payload}=args;return payload;}
