export type RequestOptions={method?:'GET'|'POST';query?:Record<string,string|number|boolean|undefined>;body?:unknown;signal?:AbortSignal;retry?:boolean};
export class FactorialError extends Error{constructor(public status:number,public code:string,message:string,public retryAfter?:number){super(message)}}
export class FactorialClient{
 private base='https://api.factorialhr.com'; private version:string; private timeout:number;
 constructor(private env:NodeJS.ProcessEnv=process.env,private fetcher:typeof fetch=fetch){this.version=env.FACTORIAL_API_VERSION||'2026-07-01';this.timeout=Number(env.FACTORIAL_TIMEOUT_MS||15000);if(!env.FACTORIAL_TOKEN&&!env.FACTORIAL_API_KEY)throw new Error('Set FACTORIAL_TOKEN or FACTORIAL_API_KEY');}
 private headers(){const h:Record<string,string>={'accept':'application/json','content-type':'application/json'};if(this.env.FACTORIAL_TOKEN)h.authorization=`Bearer ${this.env.FACTORIAL_TOKEN}`;else h['x-api-key']=this.env.FACTORIAL_API_KEY!;return h}
 async request<T>(path:string,o:RequestOptions={}):Promise<T>{const u=new URL(`${this.base}/api/${this.version}/resources/${path}`);for(const[k,v]of Object.entries(o.query||{}))if(v!==undefined)u.searchParams.set(k,String(v));let last:unknown;
  for(let attempt=0;attempt<3;attempt++){const c=new AbortController();const timer=setTimeout(()=>c.abort(),this.timeout);const onAbort=()=>c.abort();o.signal?.addEventListener('abort',onAbort,{once:true});try{const r=await this.fetcher(u,{method:o.method||'GET',headers:this.headers(),body:o.body===undefined?undefined:JSON.stringify(o.body),signal:c.signal});const text=await r.text();const data=text?JSON.parse(text):{};if(r.ok)return data as T;const retryAfter=Number(r.headers.get('retry-after')||0)||undefined;if([401,403,404,422].includes(r.status))throw new FactorialError(r.status,'provider_error',data?.message||text||r.statusText,retryAfter);if((r.status===429||r.status>=500)&&o.retry!==false&&attempt<2){await new Promise(x=>setTimeout(x,retryAfter?retryAfter*1000:250*2**attempt));continue}throw new FactorialError(r.status,'provider_error',data?.message||text||r.statusText,retryAfter)}catch(e){last=e;if(e instanceof FactorialError)throw e;if(attempt===2||o.retry===false)throw e;await new Promise(x=>setTimeout(x,250*2**attempt))}finally{clearTimeout(timer);o.signal?.removeEventListener('abort',onAbort)}}throw last}
}
export function approvalRequired(env:NodeJS.ProcessEnv=process.env){return (env.FACTORIAL_REQUIRE_WRITE_APPROVAL??'true').toLowerCase()!=='false'}
export function assertApproved(approved:boolean|undefined,env:NodeJS.ProcessEnv=process.env){if(approvalRequired(env)&&approved!==true)throw new Error('Human approval required for this WRITE operation')}
