import {z} from 'zod';import {FactorialClient,assertApproved} from './client.js';
const id=z.coerce.number().int().positive(), date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/), page=z.object({cursor:z.string().max(512).optional(),limit:z.number().int().min(1).max(100).default(50)});
const q=(v:Record<string,unknown>)=>Object.fromEntries(Object.entries(v).filter(([,x])=>x!==undefined).map(([k,x])=>[k,Array.isArray(x)?x.join(','):x])) as Record<string,string|number|boolean|undefined>;
export type ToolDef={name:string;description:string;risk:'READ'|'WRITE';approval:boolean;schema:z.ZodTypeAny;run:(a:any,c:FactorialClient)=>Promise<unknown>};
export const tools:ToolDef[]=[
{name:'factorial.employee.list',description:'List/search employees visible to the authenticated principal.',risk:'READ',approval:false,schema:page.extend({full_text_name:z.string().max(200).optional(),only_active:z.boolean().default(true),only_managers:z.boolean().default(false)}),run:(a,c)=>c.request('employees/employees',{query:q(a)})},
{name:'factorial.employee.get',description:'Read one employee by ID.',risk:'READ',approval:false,schema:z.object({id}),run:(a,c)=>c.request(`employees/employees/${a.id}`)},
{name:'factorial.location.list',description:'List company locations.',risk:'READ',approval:false,schema:page.extend({main:z.boolean().optional()}),run:(a,c)=>c.request('locations/locations',{query:q(a)})},
{name:'factorial.timeoff.leave.list',description:'List leave requests in a bounded date/filter window.',risk:'READ',approval:false,schema:page.extend({employee_id:id.optional(),from:date.optional(),to:date.optional(),only_active:z.boolean().optional(),approved:z.boolean().optional(),include_pending:z.boolean().optional()}),run:(a,c)=>c.request('timeoff/leaves',{query:q(a)})},
{name:'factorial.attendance.shift.list',description:'List attendance shifts.',risk:'READ',approval:false,schema:page.extend({employee_id:id.optional(),start_on:date.optional(),end_on:date.optional(),latest_shift:z.boolean().optional()}),run:(a,c)=>c.request('attendance/shifts',{query:q(a)})},
{name:'factorial.attendance.open_shift.list',description:'List currently open attendance shifts.',risk:'READ',approval:false,schema:z.object({employee_ids:z.array(id).min(1).max(50)}),run:(a,c)=>c.request('attendance/open_shifts',{query:{'employee_ids[]':a.employee_ids.join(',')}})},
{name:'factorial.project.time_record.list',description:'List project time records.',risk:'READ',approval:false,schema:page.extend({month:z.number().int().min(1).max(12).optional(),year:z.number().int().min(2000).max(2200).optional(),updated_after:z.string().datetime().optional()}),run:(a,c)=>c.request('project_management/time_records',{query:q(a)})},
{name:'factorial.webhook.list',description:'List webhook subscriptions visible to the principal.',risk:'READ',approval:false,schema:page.extend({enabled:z.boolean().optional(),type:z.string().max(200).optional()}),run:(a,c)=>c.request('api_public/webhook_subscriptions',{query:q(a)})},
{name:'factorial.webhook.get',description:'Read one webhook subscription.',risk:'READ',approval:false,schema:z.object({id}),run:(a,c)=>c.request(`api_public/webhook_subscriptions/${a.id}`)},
{name:'factorial.timeoff.leave.create',description:'Create a leave request. WRITE; explicit approval is required by default.',risk:'WRITE',approval:true,schema:z.object({employee_id:id,leave_type_id:id.optional(),description:z.string().max(1000).optional(),start_on:date,finish_on:date.optional(),half_day:z.enum(['beggining_of_day','end_of_day']).optional(),start_time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional(),hours_amount_in_cents:z.number().int().min(1).max(2400).optional(),approved_by_human:z.boolean().optional()}),run:(a,c)=>{assertApproved(a.approved_by_human);const{approved_by_human,...body}=a;return c.request('timeoff/leaves',{method:'POST',body,retry:false})}}
];
export const byName=new Map(tools.map(t=>[t.name,t]));
