import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';import {z} from 'zod';import {UpdownClient} from './client.js';import {recipientId,requireApproval,safeUrl,token} from './security.js';
const c=new UpdownClient(),s=new McpServer({name:'updown-io',version:'1.0.0'});const out=(x:unknown)=>({content:[{type:'text' as const,text:JSON.stringify({data:x,untrusted_provider_content:true})}]});
const approval=z.boolean().default(false);const t=z.string().min(2).max(128);const checks=z.array(t).min(1).max(100);const checkBody=z.object({url:z.string().url().optional(),type:z.enum(['https','http','icmp','pulse','tcp','tcps']).optional(),period:z.number().int().min(15).max(2592000).optional(),apdex_t:z.enum([0.125,0.25,0.5,1,2,4,8]).optional(),enabled:z.boolean().optional(),published:z.boolean().optional(),alias:z.string().max(200).optional(),string_match:z.string().max(2000).optional(),mute_until:z.string().max(64).optional(),http_verb:z.enum(['GET/HEAD','POST','PUT','PATCH','DELETE','OPTIONS']).optional(),http_body:z.string().max(100000).optional(),disabled_locations:z.array(z.enum(['lan','mia','tor','rbx','fra','cap','hel','sin','tok','syd'])).max(10).optional(),recipients:z.array(z.string()).max(50).optional(),custom_headers:z.record(z.string()).optional()}).strict();
function reg(name:string,desc:string,shape:any,fn:(a:any)=>Promise<any>){s.tool(name,desc,shape,async a=>out(await fn(a)))}
reg('updown.check.list','READ: list checks',{},async()=>c.get('/checks'));reg('updown.check.get','READ: get check',{token:t,metrics:z.boolean().optional(),results:z.boolean().optional()},async a=>c.get(`/checks/${token(a.token)}`,{metrics:a.metrics,results:a.results}));reg('updown.check.downtimes','READ: list downtime history',{token:t,page:z.number().int().min(1).max(10000).default(1),results:z.boolean().optional()},async a=>c.get(`/checks/${token(a.token)}/downtimes`,{page:a.page,results:a.results}));reg('updown.check.metrics','READ: get aggregated metrics',{token:t,from:z.string().optional(),to:z.string().optional(),group:z.enum(['time','host']).optional()},async a=>c.get(`/checks/${token(a.token)}/metrics`,{from:a.from,to:a.to,group:a.group}));
reg('updown.check.create','WRITE: create monitor',{input:checkBody,approved:approval},async a=>{requireApproval('WRITE',a.approved);if(a.input.url)a.input.url=safeUrl(a.input.url);return c.post('/checks',a.input)});reg('updown.check.update','WRITE: update monitor',{token:t,input:checkBody,approved:approval},async a=>{requireApproval('WRITE',a.approved);if(a.input.url)a.input.url=safeUrl(a.input.url);return c.put(`/checks/${token(a.token)}`,a.input)});reg('updown.check.delete','DESTRUCTIVE: delete monitor',{token:t,approved:approval},async a=>{requireApproval('DESTRUCTIVE',a.approved);return c.del(`/checks/${token(a.token)}`)});
reg('updown.node.list','READ: list monitoring nodes',{},async()=>c.get('/nodes'));reg('updown.recipient.list','READ: list alert recipients',{},async()=>c.get('/recipients'));reg('updown.recipient.create','HIGH_RISK: create external alert recipient',{type:z.enum(['email','sms','webhook','slack_compatible','msteams']),value:z.string().min(1).max(2048),name:z.string().max(200).optional(),selected:z.boolean().optional(),approved:approval},async a=>{requireApproval('HIGH_RISK',a.approved);const{approved,...b}=a;if(b.type==='webhook')safeUrl(b.value);return c.post('/recipients',b)});reg('updown.recipient.delete','DESTRUCTIVE: delete alert recipient',{id:z.string(),approved:approval},async a=>{requireApproval('DESTRUCTIVE',a.approved);return c.del(`/recipients/${encodeURIComponent(recipientId(a.id))}`)});
reg('updown.status_page.list','READ: list status pages',{},async()=>c.get('/status_pages'));const pageBody=z.object({checks,name:z.string().max(200).optional(),description:z.string().max(10000).optional(),visibility:z.enum(['public','protected','private']).optional(),access_key:z.string().min(8).max(256).optional()}).strict();reg('updown.status_page.create','HIGH_RISK: publish/create status page',{input:pageBody,approved:approval},async a=>{requireApproval('HIGH_RISK',a.approved);return c.post('/status_pages',a.input)});reg('updown.status_page.update','HIGH_RISK: modify status page',{token:t,input:pageBody.partial(),approved:approval},async a=>{requireApproval('HIGH_RISK',a.approved);return c.put(`/status_pages/${token(a.token)}`,a.input)});reg('updown.status_page.delete','DESTRUCTIVE: delete status page',{token:t,approved:approval},async a=>{requireApproval('DESTRUCTIVE',a.approved);return c.del(`/status_pages/${token(a.token)}`)});
await s.connect(new StdioServerTransport());
