export type Risk = 'READ'|'WRITE'|'HIGH_RISK'|'DESTRUCTIVE';
export class ConnectorError extends Error { constructor(public code:string,message:string,public status?:number,public retryAfter?:number){super(message);} }
export type Config={appId:string;apiKey?:string;region:'us'|'eu';timeoutMs:number;maxRetries:number;autoApproveWrite:boolean;enableDestructive:boolean};
export function loadConfig(env:NodeJS.ProcessEnv=process.env):Config{const appId=env.HEAP_APP_ID?.trim();if(!appId)throw new Error('HEAP_APP_ID is required');const region=env.HEAP_REGION==='eu'?'eu':'us';return{appId,apiKey:env.HEAP_API_KEY?.trim(),region,timeoutMs:Math.max(1000,Number(env.HEAP_TIMEOUT_MS||10000)),maxRetries:Math.min(5,Math.max(0,Number(env.HEAP_MAX_RETRIES||2))),autoApproveWrite:env.HEAP_AUTO_APPROVE_WRITE==='true',enableDestructive:env.HEAP_ENABLE_DESTRUCTIVE==='true'};}
export function requireApproval(cfg:Config,risk:Risk,approved:boolean){if(risk==='READ')return;if(risk==='WRITE'&&(cfg.autoApproveWrite||approved))return;if(risk==='HIGH_RISK'&&approved)return;if(risk==='DESTRUCTIVE'){if(!cfg.enableDestructive)throw new ConnectorError('DESTRUCTIVE_DISABLED','Destructive tools are disabled; set HEAP_ENABLE_DESTRUCTIVE=true after review.');if(approved)return;}throw new ConnectorError('APPROVAL_REQUIRED',`${risk} operation requires explicit approval.`);}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
export class HeapClient{private base:string;constructor(public cfg:Config,private fetchFn:typeof fetch=fetch){this.base=cfg.region==='eu'?'https://c.eu.heap-api.com':'https://heapanalytics.com';}
 private async request(path:string,init:RequestInit,retry=true){for(let i=0;;i++){const c=new AbortController();const t=setTimeout(()=>c.abort(),this.cfg.timeoutMs);try{const r=await this.fetchFn(this.base+path,{...init,signal:c.signal,headers:{'content-type':'application/json',...(init.headers||{})}});const retryAfter=Number(r.headers.get('retry-after')||0);if((r.status===429||r.status>=500)&&retry&&i<this.cfg.maxRetries){await sleep((retryAfter?retryAfter*1000:250*2**i)+Math.floor(Math.random()*100));continue;}const text=await r.text();let body:any={};try{body=text?JSON.parse(text):{};}catch{body={raw:text};}if(!r.ok)throw new ConnectorError(r.status===401?'AUTHENTICATION_FAILED':r.status===403?'PERMISSION_DENIED':r.status===429?'RATE_LIMITED':'PROVIDER_ERROR',body?.message||body?.error||`Heap HTTP ${r.status}`,r.status,retryAfter||undefined);return body;}catch(e){if(e instanceof ConnectorError)throw e;if(i<this.cfg.maxRetries&&retry){await sleep(250*2**i);continue;}throw new ConnectorError(e instanceof DOMException&&e.name==='AbortError'?'TIMEOUT':'NETWORK_ERROR',String(e));}finally{clearTimeout(t);}}}
 async track(input:{identity?:string;user_id?:string;event:string;properties?:Record<string,unknown>;timestamp?:string}){return this.request('/api/track',{method:'POST',body:JSON.stringify({app_id:this.cfg.appId,...input})});}
 async trackBatch(events:Array<Record<string,unknown>>){return this.request('/api/track',{method:'POST',body:JSON.stringify({app_id:this.cfg.appId,events})});}
 async addUserProperties(identity:string,properties:Record<string,unknown>){return this.request('/api/add_user_properties',{method:'POST',body:JSON.stringify({app_id:this.cfg.appId,identity,properties})});}
 async identify(user_id:string,identity:string,timestamp?:string){return this.request('/api/v1/identify',{method:'POST',body:JSON.stringify({app_id:this.cfg.appId,user_id,identity,...(timestamp?{timestamp}:{})})});}
 private async privacyToken(){if(!this.cfg.apiKey)throw new ConnectorError('AUTH_CONFIGURATION','HEAP_API_KEY is required for privacy deletion tools.');const basic=Buffer.from(`${this.cfg.appId}:${this.cfg.apiKey}`).toString('base64');const x=await this.request('/api/public/v0/auth_token',{method:'POST',headers:{authorization:`Basic ${basic}`}},false);if(!x.access_token)throw new ConnectorError('AUTHENTICATION_FAILED','Heap did not return a privacy access token.');return x.access_token as string;}
 async requestDeletion(users:Array<{user_id?:string|number;identity?:string}>){const token=await this.privacyToken();return this.request('/api/public/v0/user_deletion',{method:'POST',headers:{authorization:`Bearer ${token}`},body:JSON.stringify({users})},false);}
 async deletionStatus(id:string){const token=await this.privacyToken();return this.request(`/api/public/v0/deletion_status/${encodeURIComponent(id)}`,{method:'GET',headers:{authorization:`Bearer ${token}`}},false);}
}
export function validateIdentityChoice(v:{identity?:string;user_id?:string}){if(Boolean(v.identity)===Boolean(v.user_id))throw new ConnectorError('VALIDATION_ERROR','Exactly one of identity or user_id is required.');}
