import { z } from "zod";
import type { Risk } from "./policy.js";

const id = z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,35}$/);
const empty = z.object({}).strict();
const list = z.object({ queries: z.array(z.string().max(4096)).max(100).optional(), total: z.boolean().optional() }).strict();
const obj = (properties: Record<string, unknown>, required: string[] = []) => ({ type: "object", additionalProperties: false, properties, required });
export type ToolDef = { name: string; risk: Risk; purpose: string; upstream?: string; schema: z.ZodTypeAny; inputSchema: Record<string, unknown> };

export const TOOLS: ToolDef[] = [
  { name: "appwrite.context.get", risk: "READ", purpose: "Read workspace/project context using the official Appwrite MCP server.", schema: z.object({ includeServices: z.boolean().optional() }).strict(), inputSchema: obj({ includeServices: { type: "boolean" } }) },
  { name: "appwrite.docs.search", risk: "READ", purpose: "Search current Appwrite documentation using official MCP semantic search.", schema: z.object({ query: z.string().min(2).max(500) }).strict(), inputSchema: obj({ query: { type: "string", minLength: 2, maxLength: 500 } }, ["query"]) },
  { name: "appwrite.user.list", risk: "READ", purpose: "List project users.", upstream: "users_list", schema: list, inputSchema: obj({ queries: { type: "array", maxItems: 100, items: { type: "string" } }, total: { type: "boolean" } }) },
  { name: "appwrite.user.get", risk: "READ", purpose: "Get a user by ID.", upstream: "users_get", schema: z.object({ userId: id }).strict(), inputSchema: obj({ userId: { type: "string" } }, ["userId"]) },
  { name: "appwrite.user.create", risk: "WRITE", purpose: "Create a project user.", upstream: "users_create", schema: z.object({ userId: id, email: z.string().email().optional(), phone: z.string().regex(/^\+[1-9]\d{6,14}$/).optional(), password: z.string().min(8).max(256).optional(), name: z.string().max(128).optional() }).strict().refine(v => Boolean(v.email || v.phone), "email or phone is required"), inputSchema: obj({ userId: { type: "string" }, email: { type: "string", format: "email" }, phone: { type: "string" }, password: { type: "string", minLength: 8, maxLength: 256 }, name: { type: "string", maxLength: 128 } }, ["userId"]) },
  { name: "appwrite.user.update_name", risk: "WRITE", purpose: "Update a user's display name.", upstream: "users_update_name", schema: z.object({ userId: id, name: z.string().min(1).max(128) }).strict(), inputSchema: obj({ userId: { type: "string" }, name: { type: "string", minLength: 1, maxLength: 128 } }, ["userId", "name"]) },
  { name: "appwrite.user.delete", risk: "DESTRUCTIVE", purpose: "Permanently delete a project user.", upstream: "users_delete", schema: z.object({ userId: id }).strict(), inputSchema: obj({ userId: { type: "string" } }, ["userId"]) },
  { name: "appwrite.storage.bucket.list", risk: "READ", purpose: "List storage buckets.", upstream: "storage_list_buckets", schema: list, inputSchema: obj({ queries: { type: "array", maxItems: 100, items: { type: "string" } }, total: { type: "boolean" } }) },
  { name: "appwrite.storage.bucket.get", risk: "READ", purpose: "Get a storage bucket.", upstream: "storage_get_bucket", schema: z.object({ bucketId: id }).strict(), inputSchema: obj({ bucketId: { type: "string" } }, ["bucketId"]) },
  { name: "appwrite.storage.bucket.create", risk: "WRITE", purpose: "Create a storage bucket with secure defaults.", upstream: "storage_create_bucket", schema: z.object({ bucketId: id, name: z.string().min(1).max(128), fileSecurity: z.boolean().default(true), enabled: z.boolean().default(true) }).strict(), inputSchema: obj({ bucketId: { type: "string" }, name: { type: "string", maxLength: 128 }, fileSecurity: { type: "boolean" }, enabled: { type: "boolean" } }, ["bucketId", "name"]) },
  { name: "appwrite.storage.bucket.delete", risk: "DESTRUCTIVE", purpose: "Delete a storage bucket and its files.", upstream: "storage_delete_bucket", schema: z.object({ bucketId: id }).strict(), inputSchema: obj({ bucketId: { type: "string" } }, ["bucketId"]) },
  { name: "appwrite.function.list", risk: "READ", purpose: "List functions.", upstream: "functions_list", schema: list, inputSchema: obj({ queries: { type: "array", maxItems: 100, items: { type: "string" } }, total: { type: "boolean" } }) },
  { name: "appwrite.function.get", risk: "READ", purpose: "Get function configuration/status.", upstream: "functions_get", schema: z.object({ functionId: id }).strict(), inputSchema: obj({ functionId: { type: "string" } }, ["functionId"]) },
  { name: "appwrite.function.create", risk: "WRITE", purpose: "Create a disabled-by-default function definition.", upstream: "functions_create", schema: z.object({ functionId: id, name: z.string().min(1).max(128), runtime: z.string().min(1).max(80), entrypoint: z.string().min(1).max(512), enabled: z.boolean().default(false) }).strict(), inputSchema: obj({ functionId: { type: "string" }, name: { type: "string" }, runtime: { type: "string" }, entrypoint: { type: "string" }, enabled: { type: "boolean" } }, ["functionId", "name", "runtime", "entrypoint"]) },
  { name: "appwrite.function.execution.create", risk: "HIGH_RISK", purpose: "Execute an Appwrite function through the official REST API; explicit human approval is always required.", schema: z.object({ functionId: id, body: z.string().max(100000).default(""), async: z.boolean().default(true), path: z.string().max(2048).default("/") }).strict(), inputSchema: obj({ functionId: { type: "string" }, body: { type: "string", maxLength: 100000 }, async: { type: "boolean" }, path: { type: "string", maxLength: 2048 } }, ["functionId"]) },
  { name: "appwrite.function.delete", risk: "DESTRUCTIVE", purpose: "Delete a function.", upstream: "functions_delete", schema: z.object({ functionId: id }).strict(), inputSchema: obj({ functionId: { type: "string" } }, ["functionId"]) }
];

export const TOOL_MAP = new Map(TOOLS.map(t => [t.name, t]));
