import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';import {z} from 'zod';import {KitClient} from './client.js';import {authorize,cursorQuery,safeEmail,safeId} from './policy.js';
export function buildServer(client=new KitClient(process.env.KIT_API_KEY||'')){
 const s=new McpServer({name:'kit-connector',version:'1.0.0'}); const out=(x:unknown)=>({content:[{type:'text' as const,text:JSON.stringify({data:x,trust:'UNTRUSTED_PROVIDER_DATA'})}]});
 s.tool('kit.subscriber.list','List subscribers with cursor pagination',{after:z.string().optional(),per_page:z.number().int().min(1).max(1000).default(50)},async a=>{authorize('READ');return out(await client.request('GET','/subscribers',undefined,cursorQuery(a.after,a.per_page)))});
 s.tool('kit.subscriber.get','Get a subscriber',{id:z.number().int().positive()},async a=>{authorize('READ');return out(await client.request('GET',`/subscribers/${safeId(a.id)}`))});
 s.tool('kit.subscriber.upsert','Create or update subscriber identity/profile',{email_address:z.string().email(),first_name:z.string().max(255).optional(),fields:z.record(z.string()).optional()},async a=>{authorize('WRITE');return out(await client.request('POST','/subscribers',{email_address:safeEmail(a.email_address),first_name:a.first_name,fields:a.fields}))});
 s.tool('kit.tag.list','List tags',{after:z.string().optional(),per_page:z.number().int().min(1).max(1000).default(50)},async a=>{authorize('READ');return out(await client.request('GET','/tags',undefined,cursorQuery(a.after,a.per_page)))});
 s.tool('kit.subscriber.tag','Apply an existing tag to an existing subscriber',{tag_id:z.number().int().positive(),subscriber_id:z.number().int().positive()},async a=>{authorize('WRITE');return out(await client.request('POST',`/tags/${safeId(a.tag_id)}/subscribers/${safeId(a.subscriber_id)}`,{}))});
 s.tool('kit.sequence.list','List sequences',{after:z.string().optional(),per_page:z.number().int().min(1).max(1000).default(50)},async a=>{authorize('READ');return out(await client.request('GET','/sequences',undefined,cursorQuery(a.after,a.per_page)))});
 s.tool('kit.subscriber.sequence_add','Add an existing subscriber to a sequence',{sequence_id:z.number().int().positive(),subscriber_id:z.number().int().positive()},async a=>{authorize('WRITE');return out(await client.request('POST',`/sequences/${safeId(a.sequence_id)}/subscribers/${safeId(a.subscriber_id)}`,{}))});
 s.tool('kit.broadcast.list','List broadcasts',{after:z.string().optional(),per_page:z.number().int().min(1).max(1000).default(50)},async a=>{authorize('READ');return out(await client.request('GET','/broadcasts',undefined,cursorQuery(a.after,a.per_page)))});
 s.tool('kit.broadcast.get','Get broadcast details',{id:z.number().int().positive()},async a=>{authorize('READ');return out(await client.request('GET',`/broadcasts/${safeId(a.id)}`))});
 s.tool('kit.broadcast.draft_create','Create a private unscheduled broadcast draft; sending/publishing is intentionally unavailable',{subject:z.string().min(1).max(255),content:z.string().min(1).max(1000000),description:z.string().max(500).default('AI prepared draft'),preview_text:z.string().max(255).default('')},async a=>{authorize('WRITE');return out(await client.request('POST','/broadcasts',{subject:a.subject,content:a.content,description:a.description,preview_text:a.preview_text,public:false,published_at:new Date().toISOString(),send_at:null,subscriber_filter:[]}))});
 s.tool('kit.account.growth_stats','Get account growth statistics',{starting:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),ending:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional()},async a=>{authorize('READ');return out(await client.request('GET','/account/growth_stats',undefined,a))}); return s;
}
if(process.env.NODE_ENV!=='test'){const server=buildServer();await server.connect(new StdioServerTransport())}
