import {z} from 'zod';import type {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';import {UmamiClient} from './client.js';import type {Config} from './config.js';import {assertRange,assertUuid,requirePermission} from './security.js';
const out=(x:unknown)=>({content:[{type:'text' as const,text:JSON.stringify({untrusted_provider_data:true,data:x})}]});
const id=z.string().uuid();const time={startAt:z.number().int().nonnegative(),endAt:z.number().int().positive()};
export function registerTools(s:McpServer,c:UmamiClient,cfg:Config){
 s.tool('umami.website.list','List accessible websites',{page:z.number().int().min(1).default(1),pageSize:z.number().int().min(1).max(100).default(20),query:z.string().max(200).optional()},async a=>out(await c.listWebsites(a.page,a.pageSize,a.query)));
 s.tool('umami.website.get','Get website metadata',{websiteId:id},async a=>{assertUuid(a.websiteId);return out(await c.getWebsite(a.websiteId))});
 s.tool('umami.website.active','Get active visitors in the last five minutes',{websiteId:id},async a=>out(await c.active(a.websiteId)));
 s.tool('umami.analytics.stats','Get aggregate website statistics',{websiteId:id,...time},async a=>{assertRange(a.startAt,a.endAt);return out(await c.stats(a.websiteId,a.startAt,a.endAt))});
 s.tool('umami.analytics.pageviews','Get pageview time series',{websiteId:id,...time,unit:z.enum(['minute','hour','day','month','year']),timezone:z.string().max(100).optional()},async a=>{assertRange(a.startAt,a.endAt);return out(await c.pageviews(a.websiteId,a.startAt,a.endAt,a.unit,a.timezone))});
 s.tool('umami.analytics.metrics','Get ranked analytics metrics',{websiteId:id,...time,type:z.enum(['path','entry','exit','title','query','referrer','channel','domain','country','region','city','browser','os','device','language','screen','event','hostname','tag','distinctId']),limit:z.number().int().min(1).max(500).default(100),offset:z.number().int().nonnegative().default(0)},async a=>{assertRange(a.startAt,a.endAt);return out(await c.metrics(a.websiteId,a.startAt,a.endAt,a.type,a.limit,a.offset))});
 s.tool('umami.event.list','List website event details',{websiteId:id,...time,page:z.number().int().min(1).default(1),pageSize:z.number().int().min(1).max(100).default(20),search:z.string().max(200).optional()},async a=>{assertRange(a.startAt,a.endAt);return out(await c.events(a.websiteId,a.startAt,a.endAt,a.page,a.pageSize,a.search))});
 s.tool('umami.event.stats','Get aggregate event statistics',{websiteId:id,...time,compare:z.enum(['prev','yoy']).optional()},async a=>{assertRange(a.startAt,a.endAt);return out(await c.eventStats(a.websiteId,a.startAt,a.endAt,a.compare))});
 s.tool('umami.realtime.get','Get realtime website analytics for the last 30 minutes',{websiteId:id},async a=>out(await c.realtime(a.websiteId)));
 s.tool('umami.website.create','Create a website. WRITE; explicit approval required.',{name:z.string().min(1).max(200),domain:z.string().min(1).max(253),shareId:z.string().max(200).optional(),approved:z.literal(true)},async a=>{requirePermission(cfg,'WRITE',a.approved);return out(await c.createWebsite(a.name,a.domain,a.shareId))});
 s.tool('umami.website.update','Update website metadata. WRITE; explicit approval required.',{websiteId:id,name:z.string().min(1).max(200).optional(),domain:z.string().min(1).max(253).optional(),shareId:z.string().max(200).nullable().optional(),approved:z.literal(true)},async a=>{requirePermission(cfg,'WRITE',a.approved);if(a.name===undefined&&a.domain===undefined&&a.shareId===undefined)throw new Error('At least one field is required');return out(await c.updateWebsite(a.websiteId,{name:a.name,domain:a.domain,shareId:a.shareId}))});
 s.tool('umami.website.delete','Delete a website and its analytics data. DESTRUCTIVE; disabled by default and explicit approval required.',{websiteId:id,confirmWebsiteId:id,approved:z.literal(true)},async a=>{requirePermission(cfg,'DESTRUCTIVE',a.approved);if(a.websiteId!==a.confirmWebsiteId)throw new Error('confirmWebsiteId must exactly match websiteId');return out(await c.deleteWebsite(a.websiteId))});
}
