import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { AirbrakeClient } from "./client.js";
import { boundedLimit, boundedPage, positiveId, requireApproval } from "./security.js";
const api = new AirbrakeClient();
const server = new McpServer({ name: "airbrake-connector", version: "1.0.0" });
const out = (v: unknown) => ({ content: [{ type: "text" as const, text: JSON.stringify(v) }] });
const projectId = z.number().int().positive(); const groupId = z.number().int().positive();
server.tool("airbrake.project.list", "READ: list projects", { page:z.number().int().positive().default(1), limit:z.number().int().min(1).max(100).default(20) }, async a => out(await api.request("/projects","GET",{page:boundedPage(a.page),limit:boundedLimit(a.limit)})));
server.tool("airbrake.project.get", "READ: get project", { projectId }, async a => out(await api.request(`/projects/${positiveId(a.projectId,"projectId")}`)));
server.tool("airbrake.group.list", "READ: list error groups", { projectId, page:z.number().int().positive().default(1), limit:z.number().int().min(1).max(100).default(20), order:z.enum(["last_notice","notice_count","weight","created"]).optional(), archived:z.boolean().optional(), muted:z.boolean().optional() }, async a => out(await api.request(`/projects/${a.projectId}/groups`,"GET",{page:a.page,limit:a.limit,order:a.order,archived:a.archived,muted:a.muted})));
server.tool("airbrake.group.get", "READ: get error group", { projectId, groupId }, async a => out(await api.request(`/projects/${a.projectId}/groups/${a.groupId}`)));
server.tool("airbrake.notice.list", "READ: list group occurrences", { projectId, groupId, page:z.number().int().positive().default(1), limit:z.number().int().min(1).max(100).default(20), version:z.string().max(200).optional() }, async a => out(await api.request(`/projects/${a.projectId}/groups/${a.groupId}/notices`,"GET",{page:a.page,limit:a.limit,version:a.version})));
server.tool("airbrake.notice.status", "READ: get notice processing status", { projectId, noticeUuid:z.string().uuid() }, async a => out(await api.request(`/projects/${a.projectId}/notice-status/${encodeURIComponent(a.noticeUuid)}`)));
server.tool("airbrake.deploy.list", "READ: list deploys", { projectId, page:z.number().int().positive().default(1), limit:z.number().int().min(1).max(100).default(20) }, async a => out(await api.request(`/projects/${a.projectId}/deploys`,"GET",{page:a.page,limit:a.limit})));
server.tool("airbrake.deploy.get", "READ: get deploy", { projectId, deployId:z.number().int().positive() }, async a => out(await api.request(`/projects/${a.projectId}/deploys/${a.deployId}`)));
server.tool("airbrake.activity.list", "READ: list project activities", { projectId, page:z.number().int().positive().default(1), limit:z.number().int().min(1).max(100).default(20) }, async a => out(await api.request(`/projects/${a.projectId}/activities`,"GET",{page:a.page,limit:a.limit})));
server.tool("airbrake.group.mute", "WRITE: mute an error group and notifications; approval required", { projectId, groupId, approved:z.literal(true) }, async a => { requireApproval(a.approved); return out(await api.request(`/projects/${a.projectId}/groups/${a.groupId}/muted`,"PUT")); });
server.tool("airbrake.group.unmute", "WRITE: unmute an error group; approval required", { projectId, groupId, approved:z.literal(true) }, async a => { requireApproval(a.approved); return out(await api.request(`/projects/${a.projectId}/groups/${a.groupId}/unmuted`,"PUT")); });
server.tool("airbrake.deploy.create", "WRITE: register a deploy; approval required", { projectId, environment:z.string().min(1).max(100), username:z.string().max(200).optional(), email:z.string().email().optional(), repository:z.string().url().max(1000).optional(), revision:z.string().max(200).optional(), version:z.string().max(200).optional(), approved:z.literal(true) }, async a => { requireApproval(a.approved); const {projectId,approved,...body}=a; return out(await api.request(`/projects/${projectId}/deploys`,"POST",{},body,true)); });
await server.connect(new StdioServerTransport());
