import { z } from 'zod';
import { MailgunClient } from './client.js';
import { assertPermission, type Risk } from './policy.js';
import { config, domainSchema, emailSchema, webhookTypeSchema } from './config.js';

export type ToolSpec = { name:string; description:string; risk:Risk; schema:z.ZodTypeAny; run:(input:any, client:MailgunClient)=>Promise<any> };
const domain = (v?: string) => domainSchema.parse(v ?? config.defaultDomain);
const approval = z.object({ approved: z.boolean().default(false) });

export const tools: ToolSpec[] = [
 { name:'mailgun.domain.list', description:'List sending domains.', risk:'READ', schema:z.object({ limit:z.number().int().min(1).max(1000).default(100), skip:z.number().int().min(0).default(0), state:z.enum(['active','unverified','disabled']).optional() }), run:(i,c)=>c.request('/v4/domains',{query:i}) },
 { name:'mailgun.domain.get', description:'Get one sending domain and DNS configuration.', risk:'READ', schema:z.object({ domain:domainSchema }), run:(i,c)=>c.request(`/v4/domains/${encodeURIComponent(i.domain)}`) },
 { name:'mailgun.domain.verify', description:'Trigger DNS verification for a domain.', risk:'WRITE', schema:z.object({ domain:domainSchema }), run:(i,c)=>c.request(`/v4/domains/${encodeURIComponent(i.domain)}/verify`,{method:'PUT',retryable:false}) },
 { name:'mailgun.event.list', description:'Read message delivery/engagement events.', risk:'READ', schema:z.object({ domain:domainSchema.optional(), begin:z.string().optional(), end:z.string().optional(), ascending:z.enum(['yes','no']).optional(), limit:z.number().int().min(1).max(300).default(100), event:z.string().max(80).optional(), recipient:emailSchema.optional(), subject:z.string().max(998).optional(), tags:z.string().max(256).optional(), severity:z.enum(['temporary','permanent']).optional() }), run:(i,c)=>{const d=domain(i.domain); const {domain:_,...q}=i; return c.request(`/v3/${encodeURIComponent(d)}/events`,{query:q});} },
 { name:'mailgun.message.send', description:'Send an external email through a configured Mailgun domain.', risk:'HIGH_RISK', schema:z.object({ domain:domainSchema.optional(), from:z.string().min(3).max(320), to:z.array(emailSchema).min(1).max(100), cc:z.array(emailSchema).max(100).optional(), bcc:z.array(emailSchema).max(100).optional(), subject:z.string().min(1).max(998), text:z.string().max(1000000).optional(), html:z.string().max(2000000).optional(), tags:z.array(z.string().min(1).max(128)).max(3).optional(), approved:z.boolean().default(false) }).refine(v=>Boolean(v.text||v.html),{message:'text or html is required'}), run:(i,c)=>{const d=domain(i.domain); const {domain:_,approved:__,tags,...rest}=i; return c.request(`/v3/${encodeURIComponent(d)}/messages`,{method:'POST',form:{...rest,'o:tag':tags},retryable:false});} },
 { name:'mailgun.template.list', description:'List domain templates.', risk:'READ', schema:z.object({ domain:domainSchema.optional(), page:z.enum(['first','last','next','previous']).default('first'), limit:z.number().int().min(1).max(100).default(100), p:z.string().max(500).optional() }), run:(i,c)=>{const d=domain(i.domain); const {domain:_,...q}=i; return c.request(`/v3/${encodeURIComponent(d)}/templates`,{query:q});} },
 { name:'mailgun.template.get', description:'Get a domain template.', risk:'READ', schema:z.object({ domain:domainSchema.optional(), name:z.string().min(1).max(128), active:z.enum(['yes','no']).default('yes') }), run:(i,c)=>{const d=domain(i.domain); return c.request(`/v3/${encodeURIComponent(d)}/templates/${encodeURIComponent(i.name)}`,{query:{active:i.active}});} },
 { name:'mailgun.webhook.list', description:'List configured webhooks for a domain.', risk:'READ', schema:z.object({ domain:domainSchema.optional() }), run:(i,c)=>c.request(`/v3/domains/${encodeURIComponent(domain(i.domain))}/webhooks`) },
 { name:'mailgun.webhook.get', description:'Get webhook URLs for an event type.', risk:'READ', schema:z.object({ domain:domainSchema.optional(), type:webhookTypeSchema }), run:(i,c)=>c.request(`/v3/domains/${encodeURIComponent(domain(i.domain))}/webhooks/${i.type}`) },
 { name:'mailgun.webhook.set', description:'Create or replace webhook URLs for an event type.', risk:'HIGH_RISK', schema:approval.extend({ domain:domainSchema.optional(), type:webhookTypeSchema, urls:z.array(z.string().url().refine(v=>v.startsWith('https://'), 'HTTPS required')).min(1).max(3) }), run:(i,c)=>c.request(`/v3/domains/${encodeURIComponent(domain(i.domain))}/webhooks/${i.type}`,{method:'PUT',form:{url:i.urls},retryable:false}) },
 { name:'mailgun.webhook.delete', description:'Delete a domain webhook event configuration.', risk:'DESTRUCTIVE', schema:approval.extend({ domain:domainSchema.optional(), type:webhookTypeSchema }), run:(i,c)=>c.request(`/v3/domains/${encodeURIComponent(domain(i.domain))}/webhooks/${i.type}`,{method:'DELETE',retryable:false}) }
];

export async function invoke(spec:ToolSpec,input:unknown,client:MailgunClient){ const parsed=spec.schema.parse(input); assertPermission(spec.risk, Boolean((parsed as any).approved)); return spec.run(parsed,client); }
