import type{HashnodeClient}from'./client.js';import{authorize,type Risk,type Policy}from'./policy.js';
export type ToolDef={name:string;description:string;risk:Risk;schema:Record<string,unknown>;run:(a:any)=>Promise<unknown>};const obj=(props:Record<string,unknown>,required:string[]=[])=>({type:'object',properties:props,required,additionalProperties:false});const s={type:'string'};const b={type:'boolean'};const i={type:'integer',minimum:1,maximum:100};
function reqString(a:any,k:string){if(typeof a?.[k]!=='string'||!a[k].trim())throw new Error(`INVALID_${k.toUpperCase()}`);return a[k].trim()}
export function buildTools(c:HashnodeClient,p:Policy):ToolDef[]{const out:ToolDef[]=[];const add=(x:ToolDef)=>out.push(x);const approve={approved:b};
add({name:'hashnode.post.get',description:'Read a post by ID.',risk:'READ',schema:obj({id:s},['id']),run:a=>c.gql('query($id:ID!){post(id:$id){id title subtitle slug url brief readTimeInMinutes content{markdown html} author{username name} tags{name slug} publishedAt faq{question answer}}}',{id:reqString(a,'id')})});
add({name:'hashnode.feed.list',description:'List the global feed with cursor pagination.',risk:'READ',schema:obj({first:i,after:s},['first']),run:a=>c.gql('query($first:Int!,$after:String){feed(first:$first,after:$after){edges{cursor node{id title brief url publishedAt author{username}}}pageInfo{hasNextPage endCursor}}}',{first:a.first,after:a.after})});
add({name:'hashnode.user.get',description:'Read a public user profile.',risk:'READ',schema:obj({username:s},['username']),run:a=>c.gql('query($username:String!){user(username:$username){id username name tagline followersCount followingsCount socialMediaLinks{twitter github website}}}',{username:reqString(a,'username')})});
add({name:'hashnode.tag.get',description:'Read tag metadata by slug.',risk:'READ',schema:obj({slug:s},['slug']),run:a=>c.gql('query($slug:String!){tag(slug:$slug){id name slug followersCount postsCount}}',{slug:reqString(a,'slug')})});
add({name:'hashnode.publication.get',description:'Read publication metadata by host. Pro-gated by Hashnode.',risk:'READ',schema:obj({host:s,first:i},['host']),run:a=>c.gql('query($host:String!,$first:Int!){publication(host:$host){id title url isTeam followersCount seo{title description} posts(first:$first){edges{node{id title slug url}}pageInfo{hasNextPage endCursor}}}}',{host:reqString(a,'host'),first:a.first||20})});
add({name:'hashnode.publication.search_posts',description:'Search posts inside a publication. Pro-gated.',risk:'READ',schema:obj({publicationId:s,query:s,first:i,after:s},['publicationId']),run:a=>c.gql('query($first:Int!,$after:String,$filter:SearchPostsOfPublicationFilter!){searchPostsOfPublication(first:$first,after:$after,filter:$filter){edges{node{id title slug url brief publishedAt}}pageInfo{hasNextPage endCursor}}}',{first:a.first||20,after:a.after,filter:{publicationId:reqString(a,'publicationId'),query:a.query}})});
add({name:'hashnode.draft.get',description:'Read an authorized draft. Requires PAT and Pro publication.',risk:'READ',schema:obj({id:s},['id']),run:a=>c.gql('query($id:ObjectId!){draft(id:$id){id title subtitle slug content{markdown} tags{name slug}}}',{id:reqString(a,'id')})});
add({name:'hashnode.post.publish',description:'Publish a new post. Public publishing requires explicit approval.',risk:'HIGH_RISK',schema:obj({publicationId:s,title:s,contentMarkdown:s,tags:{type:'array',maxItems:15,items:obj({slug:s,name:s},['slug'])},approved:b},['publicationId','title','contentMarkdown']),run:async a=>{authorize('HIGH_RISK',a.approved,p);return c.gql('mutation($input:PublishPostInput!){publishPost(input:$input){post{id title slug url}}}',{input:{publicationId:reqString(a,'publicationId'),title:reqString(a,'title'),contentMarkdown:reqString(a,'contentMarkdown'),tags:a.tags}})}});
add({name:'hashnode.post.update',description:'Update an existing post.',risk:'WRITE',schema:obj({id:s,title:s,contentMarkdown:s,subtitle:s,approved:b},['id']),run:async a=>{authorize('WRITE',a.approved,p);const input:any={id:reqString(a,'id')};for(const k of['title','contentMarkdown','subtitle'])if(a[k]!==undefined)input[k]=a[k];return c.gql('mutation($input:UpdatePostInput!){updatePost(input:$input){post{id title slug url}}}',{input})}});
add({name:'hashnode.post.remove',description:'Soft-delete a post from listings.',risk:'DESTRUCTIVE',schema:obj({id:s,...approve},['id']),run:async a=>{authorize('DESTRUCTIVE',a.approved,p);return c.gql('mutation($input:RemovePostInput!){removePost(input:$input){post{id title slug}}}',{input:{id:reqString(a,'id')}})}});
add({name:'hashnode.draft.create',description:'Create a draft.',risk:'WRITE',schema:obj({publicationId:s,title:s,contentMarkdown:s,approved:b},['publicationId']),run:async a=>{authorize('WRITE',a.approved,p);return c.gql('mutation($input:CreateDraftInput!){createDraft(input:$input){draft{id title}}}',{input:{publicationId:reqString(a,'publicationId'),title:a.title,contentMarkdown:a.contentMarkdown}})}});
add({name:'hashnode.draft.update',description:'Update a draft.',risk:'WRITE',schema:obj({draftId:s,title:s,contentMarkdown:s,approved:b},['draftId']),run:async a=>{authorize('WRITE',a.approved,p);const input:any={draftId:reqString(a,'draftId')};if(a.title!==undefined)input.title=a.title;if(a.contentMarkdown!==undefined)input.contentMarkdown=a.contentMarkdown;return c.gql('mutation($input:UpdateDraftInput!){updateDraft(input:$input){draft{id title}}}',{input})}});
add({name:'hashnode.draft.publish',description:'Publish an existing draft. Public publishing requires explicit approval.',risk:'HIGH_RISK',schema:obj({draftId:s,approved:b},['draftId']),run:async a=>{authorize('HIGH_RISK',a.approved,p);return c.gql('mutation($input:PublishDraftInput!){publishDraft(input:$input){post{id slug url}}}',{input:{draftId:reqString(a,'draftId')}})}});
add({name:'hashnode.draft.submit_for_review',description:'Submit a team-publication draft for editor review.',risk:'WRITE',schema:obj({draftId:s,approved:b},['draftId']),run:async a=>{authorize('WRITE',a.approved,p);return c.gql('mutation($input:SubmitDraftForReviewInput!){submitDraftForReview(input:$input){draft{id title}}}',{input:{draftId:reqString(a,'draftId')}})}});
add({name:'hashnode.draft.delete',description:'Soft-delete a draft.',risk:'DESTRUCTIVE',schema:obj({draftId:s,approved:b},['draftId']),run:async a=>{authorize('DESTRUCTIVE',a.approved,p);return c.gql('mutation($input:DeleteDraftInput!){deleteDraft(input:$input){draft{id title}}}',{input:{draftId:reqString(a,'draftId')}})}});return out;}
