import { strictObject, id, optionalString, pageSize, approval, plainObject } from "./validate.js";

const approvalSchema = {type:"object",additionalProperties:false,required:["confirmed","reason"],properties:{confirmed:{const:true},reason:{type:"string",minLength:3,maxLength:500}}};
export const tools = [
  {name:"knock.user.get",risk:"READ",description:"Get a Knock user by internal ID.",inputSchema:{type:"object",additionalProperties:false,required:["user_id"],properties:{user_id:{type:"string"}}},validate(a){strictObject(a,["user_id"],["user_id"]);id(a.user_id,"user_id");return a;}},
  {name:"knock.user.list",risk:"READ",description:"List Knock users with cursor pagination.",inputSchema:{type:"object",additionalProperties:false,properties:{page_size:{type:"integer",minimum:1,maximum:100},after:{type:"string"},before:{type:"string"}}},validate(a){strictObject(a,["page_size","after","before"]);pageSize(a.page_size);optionalString(a.after,"after",1000);optionalString(a.before,"before",1000);return a;}},
  {name:"knock.user.identify",risk:"WRITE",description:"Create or update a Knock user.",inputSchema:{type:"object",additionalProperties:false,required:["user_id"],properties:{user_id:{type:"string"},email:{type:"string"},name:{type:"string"},phone_number:{type:"string"},timezone:{type:"string"},locale:{type:"string"},avatar:{type:"string"},properties:{type:"object"},approval:approvalSchema}},validate(a){strictObject(a,["user_id","email","name","phone_number","timezone","locale","avatar","properties","approval"],["user_id"]);id(a.user_id,"user_id");for(const k of ["email","name","phone_number","timezone","locale","avatar"]) optionalString(a[k],k);plainObject(a.properties,"properties");approval(a.approval);return a;}},
  {name:"knock.user.preferences.list",risk:"READ",description:"List all preference sets for a Knock user.",inputSchema:{type:"object",additionalProperties:false,required:["user_id"],properties:{user_id:{type:"string"}}},validate(a){strictObject(a,["user_id"],["user_id"]);id(a.user_id,"user_id");return a;}},
  {name:"knock.user.preferences.get",risk:"READ",description:"Get one user preference set.",inputSchema:{type:"object",additionalProperties:false,required:["user_id","preference_set_id"],properties:{user_id:{type:"string"},preference_set_id:{type:"string"},tenant:{type:"string"}}},validate(a){strictObject(a,["user_id","preference_set_id","tenant"],["user_id","preference_set_id"]);id(a.user_id,"user_id");id(a.preference_set_id,"preference_set_id");optionalString(a.tenant,"tenant",255);return a;}},
  {name:"knock.user.preferences.set",risk:"WRITE",description:"Set a user's preference set.",inputSchema:{type:"object",additionalProperties:false,required:["user_id","preference_set_id","preferences"],properties:{user_id:{type:"string"},preference_set_id:{type:"string"},preferences:{type:"object"},tenant:{type:"string"},approval:approvalSchema}},validate(a){strictObject(a,["user_id","preference_set_id","preferences","tenant","approval"],["user_id","preference_set_id","preferences"]);id(a.user_id,"user_id");id(a.preference_set_id,"preference_set_id");plainObject(a.preferences,"preferences");optionalString(a.tenant,"tenant",255);approval(a.approval);return a;}},
  {name:"knock.user.messages.list",risk:"READ",description:"List messages generated for a Knock user.",inputSchema:{type:"object",additionalProperties:false,required:["user_id"],properties:{user_id:{type:"string"},page_size:{type:"integer",minimum:1,maximum:100},after:{type:"string"},before:{type:"string"}}},validate(a){strictObject(a,["user_id","page_size","after","before"],["user_id"]);id(a.user_id,"user_id");pageSize(a.page_size);return a;}},
  {name:"knock.user.subscriptions.list",risk:"READ",description:"List object subscriptions for a Knock user.",inputSchema:{type:"object",additionalProperties:false,required:["user_id"],properties:{user_id:{type:"string"},page_size:{type:"integer",minimum:1,maximum:100},after:{type:"string"},before:{type:"string"}}},validate(a){strictObject(a,["user_id","page_size","after","before"],["user_id"]);id(a.user_id,"user_id");pageSize(a.page_size);return a;}},
  {name:"knock.workflow.trigger",risk:"HIGH_RISK",description:"Trigger a Knock workflow; may send external messages.",inputSchema:{type:"object",additionalProperties:false,required:["workflow_key","recipients","idempotency_key","approval"],properties:{workflow_key:{type:"string"},recipients:{type:"array",minItems:1,maxItems:1000,items:{}},data:{type:"object"},actor:{},tenant:{},cancellation_key:{type:"string"},sandbox_mode:{type:"boolean"},skip_delay:{type:"boolean"},idempotency_key:{type:"string",minLength:8,maxLength:255},approval:approvalSchema}},validate(a){strictObject(a,["workflow_key","recipients","data","actor","tenant","cancellation_key","sandbox_mode","skip_delay","idempotency_key","approval"],["workflow_key","recipients","idempotency_key","approval"]);id(a.workflow_key,"workflow_key");if(!Array.isArray(a.recipients)||a.recipients.length<1||a.recipients.length>1000)throw new Error("recipients must contain 1-1000 entries");plainObject(a.data,"data");optionalString(a.cancellation_key,"cancellation_key",255);if(typeof a.idempotency_key!=="string"||a.idempotency_key.length<8||a.idempotency_key.length>255)throw new Error("idempotency_key must be 8-255 characters");approval(a.approval);return a;}},
  {name:"knock.workflow.cancel",risk:"HIGH_RISK",description:"Cancel a previously triggered Knock workflow by cancellation key.",inputSchema:{type:"object",additionalProperties:false,required:["workflow_key","cancellation_key","approval"],properties:{workflow_key:{type:"string"},cancellation_key:{type:"string"},recipients:{type:"array",maxItems:1000,items:{}},approval:approvalSchema}},validate(a){strictObject(a,["workflow_key","cancellation_key","recipients","approval"],["workflow_key","cancellation_key","approval"]);id(a.workflow_key,"workflow_key");optionalString(a.cancellation_key,"cancellation_key",255);if(Array.isArray(a.recipients)&&a.recipients.length>1000)throw new Error("recipients max is 1000");approval(a.approval);return a;}}
];
export const byName = new Map(tools.map(t=>[t.name,t]));
