import { z } from "zod";import type { ImgixClient } from "./client.js";import type { Config } from "./config.js";import { authorize,type Risk } from "./policy.js";
const sid=z.string().regex(/^[A-Za-z0-9_-]{8,64}$/);const path=z.string().min(1).max(2048);const approval={approvalToken:z.string().min(32).max(256).optional()};
export type Def={name:string;description:string;risk:Risk;schema:z.ZodObject<any>;run:(a:any)=>Promise<any>};
export function tools(client:ImgixClient,c:Config):Def[]{const d:Def[]=[
{name:"imgix.source.list",description:"List Imgix Sources.",risk:"READ",schema:z.object({pageSize:z.number().int().min(1).max(100).optional()}).strict(),run:a=>client.request("GET","/sources",{query:{"page[limit]":a.pageSize},retrySafe:true})},
{name:"imgix.source.get",description:"Get one Source.",risk:"READ",schema:z.object({sourceId:sid}).strict(),run:a=>client.request("GET",`/sources/${encodeURIComponent(a.sourceId)}`,{retrySafe:true})},
{name:"imgix.asset.list",description:"List/search assets in a Source.",risk:"READ",schema:z.object({sourceId:sid,keyword:z.string().max(200).optional(),pageSize:z.number().int().min(1).max(100).optional(),pageNumber:z.number().int().min(1).max(10000).optional()}).strict(),run:a=>client.request("GET",`/sources/${encodeURIComponent(a.sourceId)}/assets`,{query:{"filter[keyword]":a.keyword,"page[size]":a.pageSize,"page[number]":a.pageNumber},retrySafe:true})},
{name:"imgix.asset.get",description:"Get asset metadata by origin path.",risk:"READ",schema:z.object({sourceId:sid,originPath:path}).strict(),run:a=>client.request("GET",`/sources/${encodeURIComponent(a.sourceId)}/assets/${encodeURIComponent(a.originPath)}`,{retrySafe:true})},
{name:"imgix.asset.metadata.update",description:"Update categories/custom fields on an asset.",risk:"WRITE",schema:z.object({sourceId:sid,originPath:path,attributes:z.record(z.union([z.string().max(1000),z.array(z.string().max(200)).max(50)])).refine(x=>Object.keys(x).length<=30),...approval}).strict(),run:a=>client.request("PATCH",`/sources/${encodeURIComponent(a.sourceId)}/assets/${encodeURIComponent(a.originPath)}`,{body:{data:{type:"assets",attributes:a.attributes}}})},
{name:"imgix.asset.add_from_origin",description:"Register an origin asset with Asset Manager.",risk:"WRITE",schema:z.object({sourceId:sid,originPath:path,...approval}).strict(),run:a=>client.request("POST",`/sources/${encodeURIComponent(a.sourceId)}/assets/add/${encodeURIComponent(a.originPath)}`)},
{name:"imgix.asset.refresh",description:"Refresh, reprocess and purge one asset.",risk:"HIGH_RISK",schema:z.object({sourceId:sid,originPath:path,...approval}).strict(),run:a=>client.request("POST",`/sources/${encodeURIComponent(a.sourceId)}/assets/refresh/${encodeURIComponent(a.originPath)}`)},
{name:"imgix.cache.purge",description:"Purge an account-owned Imgix asset URL from cache.",risk:"HIGH_RISK",schema:z.object({url:z.string().url().max(4096).refine(v=>new URL(v).protocol==="https:","HTTPS required"),...approval}).strict(),run:a=>client.request("POST","/purge",{body:{data:{attributes:{url:a.url},type:"purges"}}})},
{name:"imgix.report.list",description:"List analytics reports.",risk:"READ",schema:z.object({completed:z.boolean().optional(),reportType:z.string().max(100).optional()}).strict(),run:a=>client.request("GET","/reports",{query:{"filter[completed]":a.completed,"filter[report_type]":a.reportType},retrySafe:true})},
{name:"imgix.report.get",description:"Get one analytics report.",risk:"READ",schema:z.object({reportId:z.string().min(1).max(128)}).strict(),run:a=>client.request("GET",`/reports/${encodeURIComponent(a.reportId)}`,{retrySafe:true})}
];return d.map(x=>({...x,run:async a=>{authorize(c,x.name,x.risk,a);const clean={...a};delete clean.approvalToken;const out=await x.run(clean);return {untrustedProviderData:true,data:out}}}))}
