import {z} from 'zod';import {StatuspageClient} from './client.js';import {id,requireApproval,Risk} from './security.js';
export const toolMeta={
'statuspage.page.get':{risk:'READ'},'statuspage.component.list':{risk:'READ'},'statuspage.component.get':{risk:'READ'},'statuspage.component.update':{risk:'WRITE'},'statuspage.incident.list':{risk:'READ'},'statuspage.incident.get':{risk:'READ'},'statuspage.incident.create':{risk:'HIGH_RISK'},'statuspage.incident.update':{risk:'HIGH_RISK'},'statuspage.incident.resolve':{risk:'HIGH_RISK'},'statuspage.maintenance.create':{risk:'HIGH_RISK'}} as const;
const approval=z.object({approved:z.boolean().optional()});const incidentStatus=z.enum(['investigating','identified','monitoring','resolved']);
export function handlers(c:StatuspageClient,pageId:string,allowWrites:boolean){const p=`/pages/${id(pageId)}`;const guard=(risk:Risk,a?:boolean)=>requireApproval(risk,allowWrites,a);return{
'statuspage.page.get':async()=>c.request('GET',`${p}.json`),
'statuspage.component.list':async()=>c.request('GET',`${p}/components.json`),
'statuspage.component.get':async(a:unknown)=>{const x=z.object({componentId:z.string().min(1)}).parse(a);return c.request('GET',`${p}/components/${id(x.componentId)}.json`)},
'statuspage.component.update':async(a:unknown)=>{const x=approval.extend({componentId:z.string(),status:z.enum(['operational','degraded_performance','partial_outage','major_outage','under_maintenance'])}).parse(a);guard('WRITE',x.approved);return c.request('PATCH',`${p}/components/${id(x.componentId)}.json`,{component:{status:x.status}})},
'statuspage.incident.list':async(a:unknown)=>{const x=z.object({page:z.number().int().positive().default(1),perPage:z.number().int().min(1).max(100).default(50)}).default({}).parse(a);return c.request('GET',`${p}/incidents.json?page=${x.page}&per_page=${x.perPage}`)},
'statuspage.incident.get':async(a:unknown)=>{const x=z.object({incidentId:z.string()}).parse(a);return c.request('GET',`${p}/incidents/${id(x.incidentId)}.json`)},
'statuspage.incident.create':async(a:unknown)=>{const x=approval.extend({name:z.string().min(1).max(200),status:incidentStatus.default('investigating'),body:z.string().max(10000),componentIds:z.array(z.string()).max(100).default([])}).parse(a);guard('HIGH_RISK',x.approved);return c.request('POST',`${p}/incidents.json`,{incident:{name:x.name,status:x.status,body:x.body,component_ids:x.componentIds}})},
'statuspage.incident.update':async(a:unknown)=>{const x=approval.extend({incidentId:z.string(),status:incidentStatus.optional(),body:z.string().max(10000).optional()}).refine(v=>v.status||v.body,{message:'status or body required'}).parse(a);guard('HIGH_RISK',x.approved);return c.request('PATCH',`${p}/incidents/${id(x.incidentId)}.json`,{incident:{status:x.status,body:x.body}})},
'statuspage.incident.resolve':async(a:unknown)=>{const x=approval.extend({incidentId:z.string(),body:z.string().max(10000)}).parse(a);guard('HIGH_RISK',x.approved);return c.request('PATCH',`${p}/incidents/${id(x.incidentId)}.json`,{incident:{status:'resolved',body:x.body}})},
'statuspage.maintenance.create':async(a:unknown)=>{const x=approval.extend({name:z.string().min(1).max(200),body:z.string().max(10000),scheduledFor:z.string().datetime(),scheduledUntil:z.string().datetime(),componentIds:z.array(z.string()).max(100).default([])}).refine(v=>new Date(v.scheduledUntil)>new Date(v.scheduledFor),{message:'scheduledUntil must be after scheduledFor'}).parse(a);guard('HIGH_RISK',x.approved);return c.request('POST',`${p}/incidents.json`,{incident:{name:x.name,body:x.body,status:'scheduled',scheduled_for:x.scheduledFor,scheduled_until:x.scheduledUntil,component_ids:x.componentIds}})}}}
