import {z} from "zod";import {PostmarkClient} from "./client.js";import {requireApproval,Risk} from "./policy.js";
export type Tool={name:string,description:string,risk:Risk,approval:boolean,schema:z.AnyZodObject,run:(x:any)=>Promise<any>};
const page=z.object({count:z.number().int().min(1).max(500).default(100),offset:z.number().int().min(0).default(0)}).strict();const id=z.string().min(1).max(200).regex(/^[A-Za-z0-9_-]+$/);const email=z.string().email().max(320);
export function tools(c=new PostmarkClient()):Tool[]{const read=(name:string,description:string,schema:z.AnyZodObject,run:(x:any)=>Promise<any>):Tool=>({name,description,risk:"READ",approval:false,schema,run});const write=(name:string,description:string,schema:z.AnyZodObject,run:(x:any)=>Promise<any>):Tool=>({name,description,risk:"WRITE",approval:true,schema,run});return[
read("postmark.server.get","Get the authenticated server.",z.object({}).strict(),()=>c.request("/server")),
read("postmark.template.list","List templates.",page,x=>c.paged("/templates?TemplateType=All",x.count,x.offset)),
read("postmark.template.get","Get template by ID or alias.",z.object({template:id}).strict(),x=>c.request("/templates/"+encodeURIComponent(x.template))),
read("postmark.message.outbound.list","List outbound messages.",page,x=>c.paged("/messages/outbound",x.count,x.offset)),
read("postmark.message.outbound.get","Get outbound message details.",z.object({messageId:z.string().uuid()}).strict(),x=>c.request("/messages/outbound/"+x.messageId+"/details")),
read("postmark.bounce.list","List bounces.",page,x=>c.paged("/bounces",x.count,x.offset)),
read("postmark.bounce.get","Get bounce.",z.object({bounceId:z.number().int().positive()}).strict(),x=>c.request("/bounces/"+x.bounceId)),
read("postmark.webhook.list","List webhooks for a message stream.",z.object({messageStream:z.string().min(1).max(100).default("outbound")}).strict(),x=>c.request("/webhooks?MessageStream="+encodeURIComponent(x.messageStream))),
read("postmark.webhook.get","Get webhook.",z.object({webhookId:z.number().int().positive()}).strict(),x=>c.request("/webhooks/"+x.webhookId)),
read("postmark.webhook.statistics","Get webhook delivery statistics.",z.object({webhookId:z.number().int().positive()}).strict(),x=>c.request("/webhooks/"+x.webhookId+"/statistics")),
write("postmark.email.send","Send transactional email; external side effect requires approval.",z.object({from:email,to:email,subject:z.string().min(1).max(998),textBody:z.string().max(100000).optional(),htmlBody:z.string().max(100000).optional(),messageStream:z.string().min(1).max(100).default("outbound"),approved:z.literal(true)}).strict(),async x=>{if(!x.textBody&&!x.htmlBody)throw new Error("POSTMARK_BODY_REQUIRED");requireApproval("WRITE",x.approved);return c.request("/email",{method:"POST",body:JSON.stringify({From:x.from,To:x.to,Subject:x.subject,TextBody:x.textBody,HtmlBody:x.htmlBody,MessageStream:x.messageStream})},false)}),
write("postmark.email.send_template","Send transactional template email; requires approval.",z.object({from:email,to:email,templateAlias:id,templateModel:z.record(z.unknown()),messageStream:z.string().min(1).max(100).default("outbound"),approved:z.literal(true)}).strict(),async x=>{requireApproval("WRITE",x.approved);return c.request("/email/withTemplate",{method:"POST",body:JSON.stringify({From:x.from,To:x.to,TemplateAlias:x.templateAlias,TemplateModel:x.templateModel,MessageStream:x.messageStream})},false)})
]}
