import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';import {z} from 'zod';import {StripeClient} from './client.js';import type {Config} from './config.js';import {enforce} from './policy.js';import {actionId,currency,email,id,idem,limit,positiveAmount} from './schemas.js';
const ok=(x:unknown)=>({content:[{type:'text' as const,text:JSON.stringify({data:x,untrusted_provider_content:true})}]});
export function registerTools(s:McpServer,c:StripeClient,cfg:Config){
 s.tool('stripe.customer.list','List Stripe customers (READ).',{limit,starting_after:id.optional()},async a=>ok(await c.request('GET','/customers',a)));
 s.tool('stripe.customer.get','Get a customer by ID (READ).',{customer_id:id},async a=>ok(await c.request('GET',`/customers/${a.customer_id}`)));
 s.tool('stripe.customer.search','Search customers using Stripe Search syntax (READ).',{query:z.string().min(1).max(500),limit},async a=>ok(await c.request('GET','/customers/search',a)));
 s.tool('stripe.customer.create','Create a customer (WRITE; approval configurable).',{email:email.optional(),name:z.string().max(200).optional(),description:z.string().max(500).optional(),action_id:actionId,idempotency_key:idem},async a=>{enforce(cfg,'WRITE',a.action_id);const {action_id,idempotency_key,...p}=a;return ok(await c.request('POST','/customers',p,idempotency_key))});
 s.tool('stripe.customer.update','Update safe customer profile fields (WRITE; approval configurable).',{customer_id:id,email:email.optional(),name:z.string().max(200).optional(),description:z.string().max(500).optional(),action_id:actionId,idempotency_key:idem},async a=>{enforce(cfg,'WRITE',a.action_id);const {customer_id,action_id,idempotency_key,...p}=a;if(!p.email&&!p.name&&!p.description)throw new Error('At least one update field is required');return ok(await c.request('POST',`/customers/${customer_id}`,p,idempotency_key))});
 s.tool('stripe.product.list','List active or inactive products (READ).',{limit,active:z.boolean().optional(),starting_after:id.optional()},async a=>ok(await c.request('GET','/products',a)));
 s.tool('stripe.price.list','List prices (READ).',{limit,active:z.boolean().optional(),product:id.optional(),starting_after:id.optional()},async a=>ok(await c.request('GET','/prices',a)));
 s.tool('stripe.payment_intent.list','List payment intents (READ).',{limit,customer:id.optional(),starting_after:id.optional()},async a=>ok(await c.request('GET','/payment_intents',a)));
 s.tool('stripe.payment_intent.get','Get payment intent (READ).',{payment_intent_id:id},async a=>ok(await c.request('GET',`/payment_intents/${a.payment_intent_id}`)));
 s.tool('stripe.invoice.list','List invoices (READ).',{limit,customer:id.optional(),status:z.enum(['draft','open','paid','uncollectible','void']).optional(),starting_after:id.optional()},async a=>ok(await c.request('GET','/invoices',a)));
 s.tool('stripe.invoice.get','Get invoice (READ).',{invoice_id:id},async a=>ok(await c.request('GET',`/invoices/${a.invoice_id}`)));
 s.tool('stripe.payment_link.create','Create a public Payment Link (HIGH_RISK; explicit approval).',{price_id:id,quantity:z.number().int().min(1).max(999),action_id:z.string().min(3).max(128),idempotency_key:idem},async a=>{enforce(cfg,'HIGH_RISK',a.action_id);return ok(await c.request('POST','/payment_links',{'line_items[0][price]':a.price_id,'line_items[0][quantity]':a.quantity},a.idempotency_key))});
 s.tool('stripe.refund.create','Create a refund (HIGH_RISK; explicit approval).',{payment_intent_id:id,amount:positiveAmount.optional(),reason:z.enum(['duplicate','fraudulent','requested_by_customer']).optional(),action_id:z.string().min(3).max(128),idempotency_key:idem},async a=>{enforce(cfg,'HIGH_RISK',a.action_id);const {action_id,idempotency_key,payment_intent_id,...p}=a;return ok(await c.request('POST','/refunds',{payment_intent:payment_intent_id,...p},idempotency_key))});
 s.tool('stripe.event.list','List recent Stripe events for diagnostics (READ).',{limit,type:z.string().max(200).optional(),starting_after:id.optional()},async a=>ok(await c.request('GET','/events',a)));
}
