import { z } from 'zod';
import { SparkPostClient } from './client.js';
import type { Config } from './config.js';
import { requireApproval, safeWebhookTarget, type Risk } from './security.js';

export type ToolDef={name:string;description:string;risk:Risk;schema:z.ZodTypeAny;run:(x:any)=>Promise<unknown>};
const approval=z.boolean().default(false);
const page=z.number().int().min(1).max(10000).default(100);
const enc=(s:string)=>encodeURIComponent(s);
export function buildTools(client:SparkPostClient,c:Config):ToolDef[]{
 const guard=(risk:Risk,x:any)=>requireApproval(risk,x.approved===true,c.writeApprovalRequired,c.destructiveEnabled);
 return [
 {name:'sparkpost.events.search',description:'Search recent SparkPost message events.',risk:'READ',schema:z.object({events:z.string().max(500).optional(),campaigns:z.string().max(500).optional(),from:z.string().optional(),to:z.string().optional(),cursor:z.string().max(2000).optional(),perPage:page}),run:x=>client.request('GET',`/events/message?per_page=${x.perPage}${x.cursor?`&cursor=${enc(x.cursor)}`:''}${x.events?`&events=${enc(x.events)}`:''}${x.campaigns?`&campaigns=${enc(x.campaigns)}`:''}${x.from?`&from=${enc(x.from)}`:''}${x.to?`&to=${enc(x.to)}`:''}`)},
 {name:'sparkpost.metrics.summary',description:'Read deliverability metrics summary.',risk:'READ',schema:z.object({from:z.string(),to:z.string().optional(),metrics:z.string().default('count_sent,count_accepted,count_delivered,count_bounce,count_unique_confirmed_opened,count_unique_clicked')}),run:x=>client.request('GET',`/metrics/deliverability?from=${enc(x.from)}${x.to?`&to=${enc(x.to)}`:''}&metrics=${enc(x.metrics)}`)},
 {name:'sparkpost.template.list',description:'List templates.',risk:'READ',schema:z.object({}),run:()=>client.request('GET','/templates')},
 {name:'sparkpost.template.get',description:'Get a template.',risk:'READ',schema:z.object({id:z.string().min(1).max(64),draft:z.boolean().default(false)}),run:x=>client.request('GET',`/templates/${enc(x.id)}?draft=${x.draft}`)},
 {name:'sparkpost.template.create',description:'Create a draft email template.',risk:'WRITE',schema:z.object({id:z.string().min(1).max(64),name:z.string().max(1024).optional(),description:z.string().max(1024).optional(),content:z.record(z.unknown()),approved:approval}),run:x=>{guard('WRITE',x);return client.request('POST','/templates',{id:x.id,name:x.name,description:x.description,content:x.content},{retry:false})}},
 {name:'sparkpost.template.update',description:'Update a template draft.',risk:'WRITE',schema:z.object({id:z.string().min(1).max(64),name:z.string().max(1024).optional(),description:z.string().max(1024).optional(),content:z.record(z.unknown()).optional(),approved:approval}),run:x=>{guard('WRITE',x);const {id,approved,...body}=x;return client.request('PUT',`/templates/${enc(id)}`,body,{retry:false})}},
 {name:'sparkpost.suppression.search',description:'Search suppression list.',risk:'READ',schema:z.object({recipient:z.string().email().optional(),type:z.enum(['transactional','non_transactional']).optional(),cursor:z.string().max(2000).optional(),perPage:page}),run:x=>client.request('GET',`/suppression-list?per_page=${x.perPage}${x.cursor?`&cursor=${enc(x.cursor)}`:''}${x.recipient?`&recipients=${enc(x.recipient)}`:''}${x.type?`&types=${x.type}`:''}`)},
 {name:'sparkpost.suppression.get',description:'Get suppression entries for a recipient.',risk:'READ',schema:z.object({recipient:z.string().email()}),run:x=>client.request('GET',`/suppression-list/${enc(x.recipient)}`)},
 {name:'sparkpost.suppression.upsert',description:'Create or update a recipient suppression.',risk:'HIGH_RISK',schema:z.object({recipient:z.string().email(),type:z.enum(['transactional','non_transactional']),description:z.string().max(1024).optional(),listId:z.string().max(255).optional(),approved:approval}),run:x=>{guard('HIGH_RISK',x);return client.request('PUT',`/suppression-list/${enc(x.recipient)}`,{type:x.type,description:x.description,list_id:x.listId},{retry:false})}},
 {name:'sparkpost.suppression.delete',description:'Remove a suppression; may permit future email delivery.',risk:'DESTRUCTIVE',schema:z.object({recipient:z.string().email(),type:z.enum(['transactional','non_transactional']).optional(),approved:approval}),run:x=>{guard('DESTRUCTIVE',x);return client.request('DELETE',`/suppression-list/${enc(x.recipient)}`,x.type?{type:x.type}:undefined,{retry:false})}},
 {name:'sparkpost.webhook.list',description:'List event webhooks.',risk:'READ',schema:z.object({}),run:()=>client.request('GET','/webhooks')},
 {name:'sparkpost.webhook.get',description:'Get an event webhook.',risk:'READ',schema:z.object({id:z.string().min(1).max(128)}),run:x=>client.request('GET',`/webhooks/${enc(x.id)}`)},
 {name:'sparkpost.webhook.create',description:'Create an HTTPS event webhook.',risk:'HIGH_RISK',schema:z.object({name:z.string().min(1).max(256),target:z.string().url(),events:z.array(z.string().min(1).max(80)).min(1).max(50),approved:approval}),run:x=>{guard('HIGH_RISK',x);return client.request('POST','/webhooks',{name:x.name,target:safeWebhookTarget(x.target),events:x.events},{retry:false})}},
 {name:'sparkpost.webhook.update',description:'Update an event webhook.',risk:'HIGH_RISK',schema:z.object({id:z.string().min(1).max(128),name:z.string().max(256).optional(),target:z.string().url().optional(),events:z.array(z.string().min(1).max(80)).min(1).max(50).optional(),active:z.boolean().optional(),approved:approval}),run:x=>{guard('HIGH_RISK',x);const body:any={};if(x.name!==undefined)body.name=x.name;if(x.target!==undefined)body.target=safeWebhookTarget(x.target);if(x.events!==undefined)body.events=x.events;if(x.active!==undefined)body.active=x.active;return client.request('PUT',`/webhooks/${enc(x.id)}`,body,{retry:false})}},
 {name:'sparkpost.webhook.delete',description:'Delete an event webhook.',risk:'DESTRUCTIVE',schema:z.object({id:z.string().min(1).max(128),approved:approval}),run:x=>{guard('DESTRUCTIVE',x);return client.request('DELETE',`/webhooks/${enc(x.id)}`,undefined,{retry:false})}},
 {name:'sparkpost.transmission.send',description:'Send or schedule email using inline content or a stored template.',risk:'HIGH_RISK',schema:z.object({recipients:z.array(z.object({address:z.union([z.string().email(),z.object({email:z.string().email(),name:z.string().max(200).optional()})]),substitution_data:z.record(z.unknown()).optional()})).min(1).max(1000),content:z.record(z.unknown()),campaignId:z.string().max(64).optional(),description:z.string().max(1024).optional(),options:z.record(z.unknown()).optional(),idempotencyKey:z.string().uuid(),approved:approval}),run:x=>{guard('HIGH_RISK',x);return client.request('POST','/transmissions',{recipients:x.recipients,content:x.content,campaign_id:x.campaignId,description:x.description,options:x.options},{idempotencyKey:x.idempotencyKey,retry:false})}},
 {name:'sparkpost.transmission.cancel_campaign',description:'Cancel scheduled transmissions for a campaign.',risk:'DESTRUCTIVE',schema:z.object({campaignId:z.string().min(1).max(64),approved:approval}),run:x=>{guard('DESTRUCTIVE',x);return client.request('DELETE',`/transmissions?campaign_id=${enc(x.campaignId)}`,undefined,{retry:false})}}
 ];
}
