import { z } from "zod";import type { Risk } from "./policy.js";
const id=z.string().min(1).max(100),empty=z.object({}).strict(),o=(p:Record<string,unknown>,r:string[]=[])=>({type:"object",additionalProperties:false,properties:p,required:r});
const signer=z.object({email:z.string().email(),name:z.string().min(1).max(100),recipientId:z.string().regex(/^\d+$/),routingOrder:z.string().regex(/^\d+$/).optional()}).strict();
const doc=z.object({documentBase64:z.string().min(1),name:z.string().min(1).max(255),fileExtension:z.string().min(1).max(20),documentId:z.string().regex(/^\d+$/)}).strict();
const role=z.object({email:z.string().email(),name:z.string().min(1).max(100),roleName:z.string().min(1).max(100)}).strict();
export type T={name:string;risk:Risk;description:string;schema:z.ZodTypeAny;inputSchema:Record<string,unknown>};
export const TOOLS:T[]=[
 {name:"docusign.user.info.get",risk:"READ",description:"Read OAuth account discovery information.",schema:empty,inputSchema:o({})},
 {name:"docusign.envelope.list",risk:"READ",description:"List envelopes with bounded filters.",schema:z.object({fromDate:z.string().min(1).optional(),status:z.string().max(100).optional(),count:z.number().int().min(1).max(100).optional(),startPosition:z.number().int().min(0).optional()}).strict(),inputSchema:o({fromDate:{type:"string"},status:{type:"string"},count:{type:"integer",minimum:1,maximum:100},startPosition:{type:"integer",minimum:0}})},
 {name:"docusign.envelope.get",risk:"READ",description:"Get envelope metadata/status.",schema:z.object({envelopeId:id}).strict(),inputSchema:o({envelopeId:{type:"string",minLength:1}},["envelopeId"])},
 {name:"docusign.envelope.recipients.list",risk:"READ",description:"List envelope recipients.",schema:z.object({envelopeId:id}).strict(),inputSchema:o({envelopeId:{type:"string",minLength:1}},["envelopeId"])},
 {name:"docusign.envelope.documents.list",risk:"READ",description:"List document metadata without downloading bytes.",schema:z.object({envelopeId:id}).strict(),inputSchema:o({envelopeId:{type:"string",minLength:1}},["envelopeId"])},
 {name:"docusign.template.list",risk:"READ",description:"List templates.",schema:z.object({count:z.number().int().min(1).max(100).optional(),startPosition:z.number().int().min(0).optional(),searchText:z.string().max(200).optional()}).strict(),inputSchema:o({count:{type:"integer",minimum:1,maximum:100},startPosition:{type:"integer",minimum:0},searchText:{type:"string",maxLength:200}})},
 {name:"docusign.template.get",risk:"READ",description:"Get template metadata.",schema:z.object({templateId:id}).strict(),inputSchema:o({templateId:{type:"string",minLength:1}},["templateId"])},
 {name:"docusign.template.recipients.list",risk:"READ",description:"List recipient roles on a template.",schema:z.object({templateId:id}).strict(),inputSchema:o({templateId:{type:"string",minLength:1}},["templateId"])},
 {name:"docusign.envelope.create_draft",risk:"WRITE",description:"Create a draft envelope; never sends.",schema:z.object({emailSubject:z.string().min(1).max(100),documents:z.array(doc).min(1).max(25),signers:z.array(signer).min(1).max(100)}).strict(),inputSchema:o({emailSubject:{type:"string",minLength:1,maxLength:100},documents:{type:"array",minItems:1,maxItems:25,items:{type:"object"}},signers:{type:"array",minItems:1,maxItems:100,items:{type:"object"}}},["emailSubject","documents","signers"])},
 {name:"docusign.envelope.create_from_template_draft",risk:"WRITE",description:"Create a draft from a template; never sends.",schema:z.object({templateId:id,emailSubject:z.string().min(1).max(100),templateRoles:z.array(role).min(1).max(100)}).strict(),inputSchema:o({templateId:{type:"string"},emailSubject:{type:"string"},templateRoles:{type:"array",minItems:1,maxItems:100,items:{type:"object"}}},["templateId","emailSubject","templateRoles"])},
 {name:"docusign.envelope.send",risk:"HIGH_RISK",description:"Send an existing draft envelope externally.",schema:z.object({envelopeId:id}).strict(),inputSchema:o({envelopeId:{type:"string",minLength:1}},["envelopeId"])},
 {name:"docusign.envelope.void",risk:"DESTRUCTIVE",description:"Void an envelope; disabled by default.",schema:z.object({envelopeId:id,voidedReason:z.string().min(3).max(200)}).strict(),inputSchema:o({envelopeId:{type:"string"},voidedReason:{type:"string",minLength:3,maxLength:200}},["envelopeId","voidedReason"])}
];
export const TOOL_MAP=new Map(TOOLS.map(t=>[t.name,t]));
