import {z} from 'zod'; import {DaprClient} from './client.js';
export type Risk='READ'|'WRITE'|'HIGH_RISK'|'DESTRUCTIVE';
const id=z.string().min(1).max(128).regex(/^[A-Za-z0-9._-]+$/); const key=z.string().min(1).max(512);
export const defs=[
 ['dapr.metadata.get','READ',z.object({}).strict()],['dapr.health.get','READ',z.object({outbound:z.boolean().default(false)}).strict()],
 ['dapr.state.get','READ',z.object({store:id,key}).strict()],['dapr.state.save','WRITE',z.object({store:id,key,value:z.unknown(),etag:z.string().optional(),approved:z.boolean().optional()}).strict()],
 ['dapr.state.delete','HIGH_RISK',z.object({store:id,key,etag:z.string().optional(),approved:z.literal(true)}).strict()],['dapr.secret.get','READ',z.object({store:id,name:key,metadata:z.record(z.string()).optional()}).strict()],
 ['dapr.pubsub.publish','WRITE',z.object({pubsub:id,topic:id,data:z.unknown(),contentType:z.string().default('application/json'),approved:z.boolean().optional()}).strict()],
 ['dapr.service.invoke','HIGH_RISK',z.object({appId:id,method:z.string().min(1).max(256).regex(/^[A-Za-z0-9._\/-]+$/),httpMethod:z.enum(['GET','POST','PUT','PATCH','DELETE']).default('POST'),body:z.unknown().optional(),approved:z.literal(true)}).strict()],
 ['dapr.lock.acquire','WRITE',z.object({store:id,resourceId:key,lockOwner:z.string().min(1).max(128),expirySeconds:z.number().int().min(1).max(86400),approved:z.boolean().optional()}).strict()],
 ['dapr.lock.release','WRITE',z.object({store:id,resourceId:key,lockOwner:z.string().min(1).max(128),approved:z.boolean().optional()}).strict()]
] as const;
export function authorize(r:Risk,input:any){if(r==='READ')return;if(r==='WRITE'&&process.env.DAPR_ALLOW_WRITES!=='true'&&input.approved!==true)throw new Error('WRITE approval required');if(r==='HIGH_RISK'&&(process.env.DAPR_ALLOW_HIGH_RISK!=='true'||input.approved!==true))throw new Error('HIGH_RISK requires DAPR_ALLOW_HIGH_RISK=true and approved=true');throwIfDestructive(r)}
function throwIfDestructive(r:Risk){if(r==='DESTRUCTIVE')throw new Error('DESTRUCTIVE operations are disabled')}
const q=(m?:Record<string,string>)=>m?'?'+new URLSearchParams(m).toString():'';
export async function execute(c:DaprClient,name:string,input:any){const d=defs.find(x=>x[0]===name);if(!d)throw new Error('Unknown tool');const v=(d[2] as any).parse(input);authorize(d[1] as Risk,v);
 switch(name){case'dapr.metadata.get':return c.request('/v1.0/metadata');case'dapr.health.get':return c.request(v.outbound?'/v1.0/healthz/outbound':'/v1.0/healthz');case'dapr.state.get':return c.request(`/v1.0/state/${v.store}/${encodeURIComponent(v.key)}`);case'dapr.state.save':return c.request(`/v1.0/state/${v.store}`,{method:'POST',body:JSON.stringify([{key:v.key,value:v.value,...(v.etag?{etag:v.etag}:{})}])},false);case'dapr.state.delete':return c.request(`/v1.0/state/${v.store}/${encodeURIComponent(v.key)}${v.etag?q({etag:v.etag}):''}`,{method:'DELETE'},false);case'dapr.secret.get':return c.request(`/v1.0/secrets/${v.store}/${encodeURIComponent(v.name)}${q(v.metadata)}`);case'dapr.pubsub.publish':return c.request(`/v1.0/publish/${v.pubsub}/${v.topic}`,{method:'POST',headers:{'content-type':v.contentType},body:typeof v.data==='string'?v.data:JSON.stringify(v.data)},false);case'dapr.service.invoke':return c.request(`/v1.0/invoke/${v.appId}/method/${v.method}`,{method:v.httpMethod,body:v.body===undefined?undefined:JSON.stringify(v.body)},false);case'dapr.lock.acquire':return c.request(`/v1.0-alpha1/lock/${v.store}`,{method:'POST',body:JSON.stringify({resourceId:v.resourceId,lockOwner:v.lockOwner,expiryInSeconds:v.expirySeconds})},false);case'dapr.lock.release':return c.request(`/v1.0-alpha1/unlock/${v.store}`,{method:'POST',body:JSON.stringify({resourceId:v.resourceId,lockOwner:v.lockOwner})},false);}}
