import {z} from 'zod';import {MailerLiteClient} from './client.js';import {requireApproval,Risk} from './core.js';
export type Def={name:string;description:string;risk:Risk;schema:z.ZodTypeAny;run:(x:any)=>Promise<unknown>};
const id=z.string().min(1).max(100);const page=z.object({limit:z.number().int().min(1).max(100).default(25),cursor:z.string().max(1000).optional()}).strict();
export function tools(c:MailerLiteClient,writesAllowed=false):Def[]{return[
{name:'mailerlite.subscriber.list',description:'List subscribers with bounded pagination.',risk:'READ',schema:page,run:x=>c.request('GET',`/subscribers?limit=${x.limit}${x.cursor?`&cursor=${encodeURIComponent(x.cursor)}`:''}`)},
{name:'mailerlite.subscriber.get',description:'Get one subscriber by ID or email.',risk:'READ',schema:z.object({idOrEmail:id}).strict(),run:x=>c.request('GET',`/subscribers/${encodeURIComponent(x.idOrEmail)}`)},
{name:'mailerlite.subscriber.upsert',description:'Create or update a subscriber.',risk:'WRITE',schema:z.object({email:z.string().email(),fields:z.record(z.union([z.string(),z.number(),z.boolean(),z.null()])).optional(),groups:z.array(id).max(100).optional(),approved:z.boolean().default(false)}).strict(),run:x=>{requireApproval('WRITE',x.approved,writesAllowed);const {approved,...body}=x;return c.request('POST','/subscribers',body)}},
{name:'mailerlite.subscriber.delete',description:'Permanently delete a subscriber.',risk:'DESTRUCTIVE',schema:z.object({id:id,approved:z.literal(true)}).strict(),run:x=>{requireApproval('DESTRUCTIVE',x.approved,writesAllowed);return c.request('DELETE',`/subscribers/${encodeURIComponent(x.id)}`)}},
{name:'mailerlite.group.list',description:'List subscriber groups.',risk:'READ',schema:page,run:x=>c.request('GET',`/groups?limit=${x.limit}${x.cursor?`&cursor=${encodeURIComponent(x.cursor)}`:''}`)},
{name:'mailerlite.group.get',description:'Get a subscriber group.',risk:'READ',schema:z.object({id}).strict(),run:x=>c.request('GET',`/groups/${encodeURIComponent(x.id)}`)},
{name:'mailerlite.campaign.list',description:'List campaigns.',risk:'READ',schema:page.extend({filter:z.enum(['sent','draft','outbox']).optional()}).strict(),run:x=>c.request('GET',`/campaigns?limit=${x.limit}${x.cursor?`&cursor=${encodeURIComponent(x.cursor)}`:''}${x.filter?`&filter[status]=${x.filter}`:''}`)},
{name:'mailerlite.campaign.get',description:'Get a campaign.',risk:'READ',schema:z.object({id}).strict(),run:x=>c.request('GET',`/campaigns/${encodeURIComponent(x.id)}`)},
{name:'mailerlite.campaign.create',description:'Create a draft campaign.',risk:'WRITE',schema:z.object({name:z.string().min(1).max(255),type:z.enum(['regular','ab']),emails:z.array(z.object({subject:z.string().min(1).max(255),from_name:z.string().min(1).max(255),from:z.string().email(),content:z.string().min(1)}).strict()).min(1).max(2),groups:z.array(id).min(1).max(100),approved:z.boolean().default(false)}).strict(),run:x=>{requireApproval('WRITE',x.approved,writesAllowed);const {approved,...body}=x;return c.request('POST','/campaigns',body)}},
{name:'mailerlite.campaign.schedule',description:'Schedule an existing draft campaign for delivery; external communication requires explicit approval.',risk:'HIGH_RISK',schema:z.object({id,delivery:z.enum(['instant','scheduled']),schedule:z.object({date:z.string().min(10).max(40),hours:z.string().regex(/^([01]\\d|2[0-3]):[0-5]\\d$/),timezone_id:z.number().int().positive()}).optional(),approved:z.literal(true)}).strict(),run:x=>{requireApproval('HIGH_RISK',x.approved,writesAllowed);const {id,approved,...body}=x;return c.request('POST',`/campaigns/${encodeURIComponent(id)}/schedule`,body)}}]}
