import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema,ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { loadConfig } from "./config.js"; import { LokaliseApiError,LokaliseClient } from "./client.js"; import { assertAllowed } from "./policy.js"; import { TOOLS,TOOL_MAP } from "./tools.js";
const config=loadConfig(); const client=new LokaliseClient(config); const enc=(x:unknown)=>encodeURIComponent(String(x)); const result=(v:unknown)=>({content:[{type:"text" as const,text:JSON.stringify({untrustedProviderData:true,data:v},null,2)}]});
async function dispatch(n:string,a:Record<string,unknown>){const p=`/projects/${enc(a.projectId)}`; switch(n){
case"lokalise.project.list":return client.request("GET","/projects",undefined,{page:a.page as number,limit:a.limit as number}); case"lokalise.project.get":return client.request("GET",p); case"lokalise.language.list":return client.request("GET",`${p}/languages`);
case"lokalise.key.list":return client.request("GET",`${p}/keys`,undefined,{page:a.page as number,limit:a.limit as number,filter_keys:a.filterKeys as string}); case"lokalise.key.get":return client.request("GET",`${p}/keys/${enc(a.keyId)}`); case"lokalise.key.create":return client.request("POST",`${p}/keys`,{keys:a.keys}); case"lokalise.key.update":return client.request("PUT",`${p}/keys/${enc(a.keyId)}`,a.key);
case"lokalise.translation.list":return client.request("GET",`${p}/translations`,undefined,{page:a.page as number,limit:a.limit as number,filter_lang_id:a.filterLangId as number,filter_untranslated:a.filterUntranslated===undefined?undefined:String(a.filterUntranslated)}); case"lokalise.translation.get":return client.request("GET",`${p}/translations/${enc(a.translationId)}`); case"lokalise.translation.update":return client.request("PUT",`${p}/translations/${enc(a.translationId)}`,{translation:a.translation,is_reviewed:a.isReviewed,is_unverified:a.isUnverified});
case"lokalise.comment.list":return client.request("GET",`${p}/comments`,undefined,{page:a.page as number,limit:a.limit as number}); case"lokalise.comment.create":return client.request("POST",`${p}/comments`,{comments:[{comment:a.comment}]});
case"lokalise.task.list":return client.request("GET",`${p}/tasks`,undefined,{page:a.page as number,limit:a.limit as number}); case"lokalise.task.get":return client.request("GET",`${p}/tasks/${enc(a.taskId)}`); case"lokalise.task.create":return client.request("POST",`${p}/tasks`,a.task); default:throw new Error("Unknown Lokalise tool.");}}
export const server=new Server({name:"lokalise-connector",version:"1.0.0"},{capabilities:{tools:{}}});
server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:TOOLS.map(t=>({name:t.name,description:`${t.description} Risk=${t.risk}.`,inputSchema:t.inputSchema as any}))}));
server.setRequestHandler(CallToolRequestSchema,async r=>{const t=TOOL_MAP.get(r.params.name);if(!t)throw new Error("Tool is not exposed by this connector.");const a=t.schema.parse(r.params.arguments??{}) as Record<string,unknown>;assertAllowed(t.risk,t.name,a,config);try{return result(await dispatch(t.name,a));}catch(e){if(e instanceof LokaliseApiError){if(e.status===401)throw new Error("Lokalise authentication failed.");if(e.status===403)throw new Error("Lokalise denied this operation; verify token permissions and project access.");if(e.status===404)throw new Error("Lokalise resource not found.");if(e.status===429)throw new Error(`Lokalise rate limit reached.${e.retryAfter?` Retry after ${e.retryAfter}.`:""}`);if(e.status===400||e.status===422)throw new Error(`Lokalise validation failed: ${e.message}`);}throw e;}});
if(import.meta.url===`file://${process.argv[1]}`)server.connect(new StdioServerTransport()).catch(e=>{console.error(e instanceof Error?e.message:e);process.exit(1);});
