import { z } from 'zod';
import type { Risk } from '../models/policy.js';
import type { NovuRestClient } from '../client/rest.js';
import type { NovuMcpClient } from '../transport/upstream-mcp.js';

export type ToolDef = { description: string; risk: Risk; schema: z.ZodTypeAny; run: (args: any) => Promise<unknown> };
const subscriberId = z.string().min(1).max(256);
const objectData = z.record(z.string(), z.unknown()).optional();
const profile = {
  firstName: z.string().max(256).optional(), lastName: z.string().max(256).optional(), email: z.string().email().optional(), phone: z.string().max(64).optional(),
  avatar: z.string().max(2048).optional(), locale: z.string().max(64).optional(), timezone: z.string().max(128).optional(), data: objectData
};
const approval = <T extends z.ZodRawShape>(shape: T) => z.object({ ...shape, approved: z.boolean().optional() }).strict();

async function primary<T>(mcpCall: () => Promise<T>, restCall: () => Promise<T>): Promise<T> {
  try { return await mcpCall(); } catch (error) { process.stderr.write(`Novu MCP fallback: ${error instanceof Error ? error.message : 'unknown'}\n`); return restCall(); }
}

export function buildTools(mcp: NovuMcpClient, rest: NovuRestClient): Map<string, ToolDef> {
  const tools = new Map<string, ToolDef>(); const add = (name: string, def: ToolDef) => tools.set(name, def);
  add('novu.subscriber.get',{description:'Retrieve a subscriber profile',risk:'READ',schema:z.object({subscriberId}).strict(),run:a=>primary(()=>mcp.call('get_subscriber',{subscriberId:a.subscriberId}),()=>rest.request('GET',`/v2/subscribers/${encodeURIComponent(a.subscriberId)}`))});
  add('novu.subscriber.search',{description:'Search subscribers',risk:'READ',schema:z.object({query:z.string().max(256).optional(),limit:z.number().int().min(1).max(100).optional(),after:z.string().max(512).optional(),before:z.string().max(512).optional()}).strict(),run:a=>primary(()=>mcp.call('find_subscribers',a),()=>rest.request('GET','/v2/subscribers',{query:a}))});
  add('novu.subscriber.create',{description:'Create or upsert a subscriber',risk:'WRITE',schema:approval({subscriberId,...profile,failIfExists:z.boolean().optional(),idempotencyKey:z.string().max(256).optional()}),run:a=>primary(()=>mcp.call('create_subscriber',{subscriberId:a.subscriberId,...pickProfile(a)}),()=>rest.request('POST','/v2/subscribers',{query:{failIfExists:a.failIfExists},body:{subscriberId:a.subscriberId,...pickProfile(a)},idempotencyKey:a.idempotencyKey,retryable:true}))});
  add('novu.subscriber.update',{description:'Update subscriber profile fields',risk:'WRITE',schema:approval({subscriberId,...profile,idempotencyKey:z.string().max(256).optional()}),run:a=>primary(()=>mcp.call('update_subscriber',{subscriberId:a.subscriberId,...pickProfile(a)}),()=>rest.request('PATCH',`/v2/subscribers/${encodeURIComponent(a.subscriberId)}`,{body:pickProfile(a),idempotencyKey:a.idempotencyKey,retryable:false}))});
  add('novu.subscriber.preferences.get',{description:'Read subscriber notification preferences',risk:'READ',schema:z.object({subscriberId,workflowId:z.string().max(256).optional()}).strict(),run:a=>primary(()=>mcp.call('get_subscriber_preferences',a),()=>rest.request('GET',`/v2/subscribers/${encodeURIComponent(a.subscriberId)}/preferences`,{query:{workflowId:a.workflowId}}))});
  add('novu.subscriber.preferences.update',{description:'Update subscriber channel preferences',risk:'WRITE',schema:approval({subscriberId,workflowId:z.string().max(256).optional(),channels:z.object({email:z.boolean().optional(),sms:z.boolean().optional(),in_app:z.boolean().optional(),chat:z.boolean().optional(),push:z.boolean().optional()}).strict(),idempotencyKey:z.string().max(256).optional()}),run:a=>primary(()=>mcp.call('update_subscriber_preferences',{subscriberId:a.subscriberId,workflowId:a.workflowId,channels:a.channels}),()=>rest.request('PATCH',`/v2/subscribers/${encodeURIComponent(a.subscriberId)}/preferences`,{body:{workflowId:a.workflowId,channels:a.channels},idempotencyKey:a.idempotencyKey,retryable:false}))});
  add('novu.subscriber.delete',{description:'Delete a subscriber',risk:'DESTRUCTIVE',schema:approval({subscriberId}),run:a=>primary(()=>mcp.call('delete_subscriber',{subscriberId:a.subscriberId}),()=>rest.request('DELETE',`/v2/subscribers/${encodeURIComponent(a.subscriberId)}`,{retryable:false}))});
  add('novu.workflow.list',{description:'List workflows',risk:'READ',schema:z.object({limit:z.number().int().min(1).max(100).optional(),offset:z.number().int().min(0).max(100000).optional(),query:z.string().max(256).optional(),status:z.array(z.string().max(64)).max(10).optional(),tags:z.array(z.string().max(128)).max(20).optional(),orderDirection:z.enum(['ASC','DESC']).optional(),orderBy:z.enum(['createdAt','updatedAt','name','lastTriggeredAt']).optional()}).strict(),run:a=>primary(()=>mcp.call('get_workflows',a),()=>rest.request('GET','/v2/workflows',{query:a}))});
  add('novu.workflow.get',{description:'Retrieve a workflow',risk:'READ',schema:z.object({workflowId:z.string().min(1).max(256),environmentId:z.string().max(256).optional()}).strict(),run:a=>primary(()=>mcp.call('get_workflow',a),()=>rest.request('GET',`/v2/workflows/${encodeURIComponent(a.workflowId)}`,{query:{environmentId:a.environmentId}}))});
  add('novu.workflow.trigger',{description:'Trigger a workflow and send external notifications',risk:'HIGH_RISK',schema:approval({workflowId:z.string().min(1).max(256),subscriberId, payload:z.record(z.string(),z.unknown()).optional(),transactionId:z.string().max(256).optional(),idempotencyKey:z.string().max(256).optional()}),run:a=>primary(()=>mcp.call('trigger_workflow',{workflowId:a.workflowId,subscriberId:a.subscriberId,payload:a.payload,transactionId:a.transactionId}),()=>rest.request('POST','/v1/events/trigger',{body:{name:a.workflowId,to:a.subscriberId,payload:a.payload||{},transactionId:a.transactionId},idempotencyKey:a.idempotencyKey,retryable:false}))});
  add('novu.notification.list',{description:'List notification events for the current environment',risk:'READ',schema:z.object({page:z.number().int().min(0).max(100000).optional(),limit:z.number().int().min(1).max(100).optional(),channels:z.array(z.enum(['in_app','email','sms','chat','push'])).max(5).optional(),subscriberIds:z.array(subscriberId).max(100).optional(),transactionId:z.string().max(256).optional(),severity:z.array(z.string().max(32)).max(10).optional()}).strict(),run:a=>primary(()=>mcp.call('get_notifications',a),()=>rest.request('GET','/v1/notifications',{query:a}))});
  add('novu.notification.get',{description:'Retrieve a notification event and execution logs',risk:'READ',schema:z.object({notificationId:z.string().regex(/^[a-fA-F0-9]{24}$/)}).strict(),run:a=>primary(()=>mcp.call('get_notification',{notificationId:a.notificationId}),()=>rest.request('GET',`/v1/notifications/${a.notificationId}`))});
  add('novu.integration.list',{description:'List configured integrations; API-key responses do not expose decrypted credentials',risk:'READ',schema:z.object({}).strict(),run:()=>primary(()=>mcp.call('get_integrations',{}),()=>rest.request('GET','/v1/integrations'))});
  add('novu.integration.active.list',{description:'List active channel integrations',risk:'READ',schema:z.object({}).strict(),run:()=>primary(()=>mcp.call('get_active_integrations',{}),()=>rest.request('GET','/v1/integrations/active'))});
  add('novu.event.cancel',{description:'Cancel an active or pending triggered event by transaction ID',risk:'HIGH_RISK',schema:approval({transactionId:z.string().min(1).max(256),idempotencyKey:z.string().max(256).optional()}),run:a=>primary(()=>mcp.call('cancel_triggered_event',{transactionId:a.transactionId}),()=>rest.request('DELETE',`/v1/events/trigger/${encodeURIComponent(a.transactionId)}`,{idempotencyKey:a.idempotencyKey,retryable:false}))});
  return tools;
}

function pickProfile(a:any){const keys=['firstName','lastName','email','phone','avatar','locale','timezone','data'];return Object.fromEntries(keys.filter(k=>a[k]!==undefined).map(k=>[k,a[k]]));}
