import { z } from "zod";
import type { Risk } from "./policy.js";

const approvalWrite = z.literal("APPROVE_WRITE").optional();
const approvalHigh = z.literal("APPROVE_HIGH_RISK");
const approvalDestructive = z.literal("APPROVE_DESTRUCTIVE");
const perPage = z.number().int().min(1).max(200).default(50);
const maxPages = z.number().int().min(1).max(5).default(1);
const after = z.string().min(1).max(200).optional();
const listBase = { perPage, maxPages, after };
const object = z.record(z.string(), z.unknown()).optional();

const paddleId = (prefix: string) => z.string().regex(new RegExp(`^${prefix}_[a-z0-9]{20,32}$`), `Expected a ${prefix}_ Paddle ID.`);
const productId = paddleId("pro");
const priceId = paddleId("pri");
const customerId = paddleId("ctm");
const transactionId = paddleId("txn");
const subscriptionId = paddleId("sub");
const transactionItemId = paddleId("txnitm");
const currency = z.string().regex(/^[A-Z]{3}$/, "Expected ISO 4217 currency code.");
const moneyAmount = z.string().regex(/^\d+$/, "Money amount must be a non-negative minor-unit integer string.");

export interface ToolDefinition {
  name: string;
  purpose: string;
  risk: Risk;
  permission: "read" | "write" | "high_risk" | "destructive";
  approval: string;
  output: string;
  errors: string;
  schema: z.ZodTypeAny;
  inputSchema: Record<string, unknown>;
}

const jsonSchema = (properties: Record<string, unknown>, required: string[] = []) => ({ type: "object", additionalProperties: false, properties, ...(required.length ? { required } : {}) });
const str = (description: string, pattern?: string) => ({ type: "string", description, ...(pattern ? { pattern } : {}) });
const idJs = (prefix: string) => str(`${prefix}_ Paddle ID`, `^${prefix}_[a-z0-9]{20,32}$`);
const listProps = { perPage:{type:"integer",minimum:1,maximum:200,default:50}, maxPages:{type:"integer",minimum:1,maximum:5,default:1}, after:str("Cursor from Paddle pagination") };
const approval = (value: string) => ({ type:"string", enum:[value], description:"Explicit human approval token." });
const readErrors = "Validation, authentication, permission, not-found, timeout, rate-limit, or provider errors.";
const writeErrors = `${readErrors} Writes are not automatically retried.`;
const tool = (def: ToolDefinition) => def;

export const TOOLS: ToolDefinition[] = [
  tool({name:"paddle.product.list",purpose:"List catalog products with bounded cursor pagination.",risk:"READ",permission:"read",approval:"none",output:"Paddle product array plus pagination metadata.",errors:readErrors,schema:z.object({...listBase,status:z.enum(["active","archived"]).optional()}).strict(),inputSchema:jsonSchema({...listProps,status:{type:"string",enum:["active","archived"]}})}),
  tool({name:"paddle.product.get",purpose:"Get one catalog product.",risk:"READ",permission:"read",approval:"none",output:"Paddle product resource.",errors:readErrors,schema:z.object({productId}).strict(),inputSchema:jsonSchema({productId:idJs("pro")},["productId"])}),
  tool({name:"paddle.price.list",purpose:"List prices, optionally scoped to one product.",risk:"READ",permission:"read",approval:"none",output:"Paddle price array plus pagination metadata.",errors:readErrors,schema:z.object({...listBase,productId:productId.optional(),status:z.enum(["active","archived"]).optional()}).strict(),inputSchema:jsonSchema({...listProps,productId:idJs("pro"),status:{type:"string",enum:["active","archived"]}})}),
  tool({name:"paddle.price.get",purpose:"Get one price.",risk:"READ",permission:"read",approval:"none",output:"Paddle price resource.",errors:readErrors,schema:z.object({priceId}).strict(),inputSchema:jsonSchema({priceId:idJs("pri")},["priceId"])}),
  tool({name:"paddle.customer.list",purpose:"List customers with bounded cursor pagination.",risk:"READ",permission:"read",approval:"none",output:"Paddle customer array plus pagination metadata.",errors:readErrors,schema:z.object({...listBase,status:z.enum(["active","archived"]).optional()}).strict(),inputSchema:jsonSchema({...listProps,status:{type:"string",enum:["active","archived"]}})}),
  tool({name:"paddle.customer.get",purpose:"Get one customer.",risk:"READ",permission:"read",approval:"none",output:"Paddle customer resource.",errors:readErrors,schema:z.object({customerId}).strict(),inputSchema:jsonSchema({customerId:idJs("ctm")},["customerId"])}),
  tool({name:"paddle.transaction.list",purpose:"List transactions with bounded pagination; Paddle caps this endpoint at 30 items per page.",risk:"READ",permission:"read",approval:"none",output:"Paddle transaction array plus pagination metadata.",errors:readErrors,schema:z.object({perPage:z.number().int().min(1).max(30).default(30),maxPages,after,status:z.enum(["draft","ready","billed","paid","completed","canceled","past_due"]).optional(),customerId:customerId.optional()}).strict(),inputSchema:jsonSchema({perPage:{type:"integer",minimum:1,maximum:30,default:30},maxPages:listProps.maxPages,after:listProps.after,status:{type:"string",enum:["draft","ready","billed","paid","completed","canceled","past_due"]},customerId:idJs("ctm")})}),
  tool({name:"paddle.transaction.get",purpose:"Get one transaction.",risk:"READ",permission:"read",approval:"none",output:"Paddle transaction resource.",errors:readErrors,schema:z.object({transactionId}).strict(),inputSchema:jsonSchema({transactionId:idJs("txn")},["transactionId"])}),
  tool({name:"paddle.subscription.list",purpose:"List subscriptions with bounded cursor pagination.",risk:"READ",permission:"read",approval:"none",output:"Paddle subscription array plus pagination metadata.",errors:readErrors,schema:z.object({...listBase,status:z.enum(["active","canceled","past_due","paused","trialing"]).optional(),customerId:customerId.optional()}).strict(),inputSchema:jsonSchema({...listProps,status:{type:"string",enum:["active","canceled","past_due","paused","trialing"]},customerId:idJs("ctm")})}),
  tool({name:"paddle.subscription.get",purpose:"Get one subscription.",risk:"READ",permission:"read",approval:"none",output:"Paddle subscription resource.",errors:readErrors,schema:z.object({subscriptionId}).strict(),inputSchema:jsonSchema({subscriptionId:idJs("sub")},["subscriptionId"])}),
  tool({name:"paddle.adjustment.list",purpose:"List financial adjustments with Paddle's bounded pagination limits.",risk:"READ",permission:"read",approval:"none",output:"Paddle adjustment array plus pagination metadata.",errors:readErrors,schema:z.object({perPage:z.number().int().min(1).max(50).default(10),maxPages,after,transactionId:transactionId.optional()}).strict(),inputSchema:jsonSchema({perPage:{type:"integer",minimum:1,maximum:50,default:10},maxPages:listProps.maxPages,after:listProps.after,transactionId:idJs("txn")})}),
  tool({name:"paddle.event_type.list",purpose:"List event types; useful for validating auth and designing webhook subscriptions.",risk:"READ",permission:"read",approval:"none",output:"Paddle event-type resources.",errors:readErrors,schema:z.object({}).strict(),inputSchema:jsonSchema({})}),
  tool({name:"paddle.product.create",purpose:"Create a catalog product record; does not create a price or charge a customer.",risk:"WRITE",permission:"write",approval:"APPROVE_WRITE when configured",output:"Created Paddle product.",errors:writeErrors,schema:z.object({name:z.string().min(1).max(200),description:z.string().max(2048).optional(),taxCategory:z.string().min(1).max(100),customData:object,approval:approvalWrite}).strict(),inputSchema:jsonSchema({name:str("Product name"),description:str("Product description"),taxCategory:str("Paddle tax category"),customData:{type:"object",additionalProperties:true},approval:approval("APPROVE_WRITE")},["name","taxCategory"])}),
  tool({name:"paddle.product.update",purpose:"Update product metadata without exposing archive/status changes.",risk:"WRITE",permission:"write",approval:"APPROVE_WRITE when configured",output:"Updated Paddle product.",errors:writeErrors,schema:z.object({productId,name:z.string().min(1).max(200).optional(),description:z.string().max(2048).nullable().optional(),taxCategory:z.string().min(1).max(100).optional(),customData:z.record(z.string(),z.unknown()).nullable().optional(),approval:approvalWrite}).strict().refine(v=>v.name!==undefined||v.description!==undefined||v.taxCategory!==undefined||v.customData!==undefined,{message:"At least one mutable field is required."}),inputSchema:jsonSchema({productId:idJs("pro"),name:str("New product name"),description:{type:["string","null"]},taxCategory:str("Paddle tax category"),customData:{type:["object","null"],additionalProperties:true},approval:approval("APPROVE_WRITE")},["productId"])}),
  tool({name:"paddle.price.create",purpose:"Create a catalog price; recurring prices may later create subscriptions when purchased.",risk:"WRITE",permission:"write",approval:"APPROVE_WRITE when configured",output:"Created Paddle price.",errors:writeErrors,schema:z.object({productId,description:z.string().min(1).max(255),unitPrice:z.object({amount:moneyAmount,currencyCode:currency}).strict(),billingCycle:z.object({interval:z.enum(["day","week","month","year"]),frequency:z.number().int().min(1).max(100)}).strict().nullable().optional(),trialPeriod:z.object({interval:z.enum(["day","week","month","year"]),frequency:z.number().int().min(1).max(100)}).strict().nullable().optional(),taxMode:z.enum(["account_setting","external","internal"]).optional(),customData:object,approval:approvalWrite}).strict(),inputSchema:jsonSchema({productId:idJs("pro"),description:str("Price description"),unitPrice:{type:"object",additionalProperties:false,properties:{amount:str("Minor-unit integer amount","^\\d+$"),currencyCode:str("ISO 4217 currency","^[A-Z]{3}$")},required:["amount","currencyCode"]},billingCycle:{type:["object","null"],additionalProperties:false,properties:{interval:{type:"string",enum:["day","week","month","year"]},frequency:{type:"integer",minimum:1,maximum:100}},required:["interval","frequency"]},trialPeriod:{type:["object","null"],additionalProperties:false,properties:{interval:{type:"string",enum:["day","week","month","year"]},frequency:{type:"integer",minimum:1,maximum:100}},required:["interval","frequency"]},taxMode:{type:"string",enum:["account_setting","external","internal"]},customData:{type:"object",additionalProperties:true},approval:approval("APPROVE_WRITE")},["productId","description","unitPrice"])}),
  tool({name:"paddle.customer.create",purpose:"Create a customer record without charging or messaging them.",risk:"WRITE",permission:"write",approval:"APPROVE_WRITE when configured",output:"Created Paddle customer.",errors:writeErrors,schema:z.object({email:z.string().email().max(255),name:z.string().max(255).optional(),locale:z.string().max(20).optional(),customData:object,approval:approvalWrite}).strict(),inputSchema:jsonSchema({email:{type:"string",format:"email",maxLength:255},name:str("Customer name"),locale:str("Locale"),customData:{type:"object",additionalProperties:true},approval:approval("APPROVE_WRITE")},["email"])}),
  tool({name:"paddle.customer.update",purpose:"Update customer identity metadata without exposing customer archival.",risk:"WRITE",permission:"write",approval:"APPROVE_WRITE when configured",output:"Updated Paddle customer.",errors:writeErrors,schema:z.object({customerId,email:z.string().email().max(255).optional(),name:z.string().max(255).nullable().optional(),locale:z.string().max(20).nullable().optional(),customData:z.record(z.string(),z.unknown()).nullable().optional(),approval:approvalWrite}).strict().refine(v=>v.email!==undefined||v.name!==undefined||v.locale!==undefined||v.customData!==undefined,{message:"At least one mutable field is required."}),inputSchema:jsonSchema({customerId:idJs("ctm"),email:{type:"string",format:"email",maxLength:255},name:{type:["string","null"]},locale:{type:["string","null"]},customData:{type:["object","null"],additionalProperties:true},approval:approval("APPROVE_WRITE")},["customerId"])}),
  tool({name:"paddle.subscription.pause",purpose:"Pause a subscription now or at the next billing period; may interrupt customer access or billing.",risk:"HIGH_RISK",permission:"high_risk",approval:"APPROVE_HIGH_RISK",output:"Updated Paddle subscription.",errors:writeErrors,schema:z.object({subscriptionId,effectiveFrom:z.enum(["next_billing_period","immediately"]).default("next_billing_period"),resumeAt:z.string().datetime({offset:true}).nullable().optional(),approval:approvalHigh}).strict(),inputSchema:jsonSchema({subscriptionId:idJs("sub"),effectiveFrom:{type:"string",enum:["next_billing_period","immediately"],default:"next_billing_period"},resumeAt:{type:["string","null"],format:"date-time"},approval:approval("APPROVE_HIGH_RISK")},["subscriptionId","approval"])}),
  tool({name:"paddle.adjustment.create",purpose:"Create an immutable financial refund or credit against selected transaction items.",risk:"HIGH_RISK",permission:"high_risk",approval:"APPROVE_HIGH_RISK",output:"Created Paddle adjustment, which may be pending approval in live Paddle.",errors:writeErrors,schema:z.object({action:z.enum(["refund","credit"]),transactionId,reason:z.string().min(1).max(500),items:z.array(z.object({itemId:transactionItemId,type:z.enum(["full","partial"]),amount:moneyAmount.optional()}).strict().superRefine((v,ctx)=>{if(v.type==="partial"&&!v.amount)ctx.addIssue({code:z.ZodIssueCode.custom,message:"Partial adjustment item requires amount."});if(v.type==="full"&&v.amount)ctx.addIssue({code:z.ZodIssueCode.custom,message:"Full adjustment item must omit amount."});})).min(1).max(100),approval:approvalHigh}).strict(),inputSchema:jsonSchema({action:{type:"string",enum:["refund","credit"]},transactionId:idJs("txn"),reason:str("Human-readable financial adjustment reason"),items:{type:"array",minItems:1,maxItems:100,items:{type:"object",additionalProperties:false,properties:{itemId:idJs("txnitm"),type:{type:"string",enum:["full","partial"]},amount:str("Required only for partial adjustment; minor-unit integer","^\\d+$")},required:["itemId","type"]}},approval:approval("APPROVE_HIGH_RISK")},["action","transactionId","reason","items","approval"])}),
  tool({name:"paddle.subscription.cancel",purpose:"Cancel a subscription at period end or immediately. Immediate cancellation is irreversible and cannot be reinstated.",risk:"DESTRUCTIVE",permission:"destructive",approval:"APPROVE_DESTRUCTIVE plus PADDLE_ENABLE_DESTRUCTIVE=true",output:"Canceled Paddle subscription.",errors:writeErrors,schema:z.object({subscriptionId,effectiveFrom:z.enum(["next_billing_period","immediately"]).default("next_billing_period"),approval:approvalDestructive}).strict(),inputSchema:jsonSchema({subscriptionId:idJs("sub"),effectiveFrom:{type:"string",enum:["next_billing_period","immediately"],default:"next_billing_period"},approval:approval("APPROVE_DESTRUCTIVE")},["subscriptionId","approval"])}),
];

export const TOOL_MAP = new Map(TOOLS.map(t => [t.name, t]));
