import { Client, Connection } from "@temporalio/client";

export class TemporalConnectorClient {
  constructor(config, deps={}) { this.config=config; this.Connection=deps.Connection||Connection; this.Client=deps.Client||Client; this.connection=null; this.client=null; this.connectPromise=null; }
  async ensureConnected(){ if(this.client)return this.client; if(!this.connectPromise)this.connectPromise=this.#connect().finally(()=>{this.connectPromise=null;}); return this.connectPromise; }
  async #connect(){ const tls=this.config.tls?(this.config.serverNameOverride?{serverNameOverride:this.config.serverNameOverride}:true):false; const options={address:this.config.address,tls}; if(this.config.apiKey)options.apiKey=this.config.apiKey; this.connection=await this.Connection.connect(options); this.client=new this.Client({connection:this.connection,namespace:this.config.namespace}); return this.client; }
  async withTimeout(operation){ let timer; try{return await Promise.race([operation(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`Temporal operation timed out after ${this.config.timeoutMs}ms`)),this.config.timeoutMs); timer.unref?.();})]);}finally{if(timer)clearTimeout(timer);} }
  async listWorkflows(args){ const c=await this.ensureConnected(),results=[],max=args.maxResults??100; for await(const item of c.workflow.list({...(args.query?{query:args.query}:{}),pageSize:args.pageSize??50})){results.push(sanitize(item)); if(results.length>=max)break;} return {executions:results,count:results.length,truncated:results.length>=max}; }
  async describeWorkflow(args){ const c=await this.ensureConnected(); return sanitize(await this.withTimeout(()=>c.workflow.getHandle(args.workflowId,args.runId).describe())); }
  async startWorkflow(args){ const c=await this.ensureConnected(); const h=await this.withTimeout(()=>c.workflow.start(args.workflowType,{taskQueue:args.taskQueue,workflowId:args.workflowId,args:args.args??[],...(args.memo?{memo:args.memo}:{}),...(args.searchAttributes?{searchAttributes:args.searchAttributes}:{})})); return {workflowId:h.workflowId,firstExecutionRunId:h.firstExecutionRunId}; }
  async signalWorkflow(args){ const c=await this.ensureConnected(); await this.withTimeout(()=>c.workflow.getHandle(args.workflowId,args.runId).signal(args.signalName,...(args.args??[]))); return {accepted:true,workflowId:args.workflowId,runId:args.runId??null,signalName:args.signalName}; }
  async queryWorkflow(args){ const c=await this.ensureConnected(); const result=await this.withTimeout(()=>c.workflow.getHandle(args.workflowId,args.runId).query(args.queryName,...(args.args??[]))); return {result:sanitize(result)}; }
  async cancelWorkflow(args){ const c=await this.ensureConnected(); await this.withTimeout(()=>c.workflow.getHandle(args.workflowId,args.runId).cancel()); return {cancellationRequested:true,workflowId:args.workflowId,runId:args.runId??null}; }
  async terminateWorkflow(args){ const c=await this.ensureConnected(); await this.withTimeout(()=>c.workflow.getHandle(args.workflowId,args.runId).terminate(args.reason,...(args.details??[]))); return {terminated:true,workflowId:args.workflowId,runId:args.runId??null,reason:args.reason}; }
  async listSchedules(args){ const c=await this.ensureConnected(),results=[],max=args.maxResults??100; for await(const item of c.schedule.list({pageSize:args.pageSize??50})){results.push(sanitize(item)); if(results.length>=max)break;} return {schedules:results,count:results.length,truncated:results.length>=max}; }
  async describeSchedule(args){ const c=await this.ensureConnected(); return sanitize(await this.withTimeout(()=>c.schedule.getHandle(args.scheduleId).describe())); }
  async pauseSchedule(args){ const c=await this.ensureConnected(); await this.withTimeout(()=>c.schedule.getHandle(args.scheduleId).pause(args.note)); return {paused:true,scheduleId:args.scheduleId}; }
  async unpauseSchedule(args){ const c=await this.ensureConnected(); await this.withTimeout(()=>c.schedule.getHandle(args.scheduleId).unpause(args.note)); return {paused:false,scheduleId:args.scheduleId}; }
  async deleteSchedule(args){ const c=await this.ensureConnected(); await this.withTimeout(()=>c.schedule.getHandle(args.scheduleId).delete()); return {deleted:true,scheduleId:args.scheduleId}; }
}

function sanitize(value){ if(value===null||value===undefined)return value; if(typeof value==="bigint")return value.toString(); if(value instanceof Date)return value.toISOString(); if(Array.isArray(value))return value.map(sanitize); if(typeof value==="object"){const out={}; for(const [k,v] of Object.entries(value)){if(typeof v!=="function")out[k]=sanitize(v);} return out;} return value; }
