const approval = { type: 'string', minLength: 64, maxLength: 64, pattern: '^[a-f0-9]{64}$' };
const positiveId = { type: 'integer', minimum: 1 };
const email = { type: 'string', format: 'email', maxLength: 320 };
const attrs = { type: 'object', maxProperties: 100, additionalProperties: { type: ['string','number','boolean','array','null'] } };
const recipient = { type: 'object', additionalProperties: false, required: ['email'], properties: { email, name: { type: 'string', maxLength: 200 } } };
const sender = { type: 'object', additionalProperties: false, properties: { email, name: { type: 'string', maxLength: 200 }, id: positiveId } };

export const TOOL_DEFINITIONS = [
  { name:'brevo.account.get', description:'Get Brevo account metadata. Permission READ; no approval.', inputSchema:{type:'object',additionalProperties:false,properties:{}} },
  { name:'brevo.contact.list', description:'List contacts with bounded pagination. Permission READ; no approval.', inputSchema:{type:'object',additionalProperties:false,properties:{limit:{type:'integer',minimum:1,maximum:1000,default:50},offset:{type:'integer',minimum:0,maximum:10000000,default:0},sort:{enum:['asc','desc']},modifiedSince:{type:'string',format:'date-time'},createdSince:{type:'string',format:'date-time'},ids:{type:'array',maxItems:20,items:positiveId},segmentId:positiveId,listIds:{type:'array',maxItems:50,items:positiveId},filter:{type:'string',maxLength:1000}}} },
  { name:'brevo.contact.get', description:'Get one contact by supported identifier. Permission READ; no approval.', inputSchema:{type:'object',additionalProperties:false,required:['identifier'],properties:{identifier:{oneOf:[{type:'string',minLength:1,maxLength:320},positiveId]},identifierType:{enum:['email_id','contact_id','ext_id','phone_id','whatsapp_id','landline_number_id']}}} },
  { name:'brevo.contact.create', description:'Create a contact. Permission WRITE; approval required. forceMerge is intentionally not exposed.', inputSchema:{type:'object',additionalProperties:false,required:['approval_token'],anyOf:[{required:['email']},{required:['ext_id']},{required:['attributes']}],properties:{email,emailBlacklisted:{type:'boolean'},smsBlacklisted:{type:'boolean'},ext_id:{type:'string',maxLength:255},attributes:attrs,listIds:{type:'array',maxItems:50,items:positiveId},updateEnabled:{type:'boolean',default:false},getId:{type:'boolean',default:true},approval_token:approval}} },
  { name:'brevo.contact.update', description:'Update contact attributes/list membership. Permission WRITE; approval required. forceMerge and email identifier replacement are not exposed.', inputSchema:{type:'object',additionalProperties:false,required:['identifier','approval_token'],properties:{identifier:{oneOf:[{type:'string',minLength:1,maxLength:320},positiveId]},identifierType:{enum:['email_id','contact_id','ext_id','phone_id','whatsapp_id','landline_number_id']},attributes:attrs,emailBlacklisted:{type:'boolean'},smsBlacklisted:{type:'boolean'},ext_id:{type:'string',maxLength:255},listIds:{type:'array',maxItems:50,items:positiveId},unlinkListIds:{type:'array',maxItems:50,items:positiveId},approval_token:approval}} },
  { name:'brevo.contact_list.list', description:'List Brevo contact lists. Permission READ; no approval.', inputSchema:{type:'object',additionalProperties:false,properties:{limit:{type:'integer',minimum:1,maximum:50,default:10},offset:{type:'integer',minimum:0,maximum:10000000,default:0},sort:{enum:['asc','desc']}}} },
  { name:'brevo.campaign.list', description:'List email campaigns and optional recent statistics. Permission READ; no approval.', inputSchema:{type:'object',additionalProperties:false,properties:{type:{enum:['classic','trigger']},status:{type:'string',maxLength:40},statistics:{enum:['globalStats','linksStats','statsByDomain']},startDate:{type:'string',format:'date-time'},endDate:{type:'string',format:'date-time'},limit:{type:'integer',minimum:1,maximum:100,default:50},offset:{type:'integer',minimum:0,maximum:10000000,default:0},sort:{enum:['asc','desc']},excludeHtmlContent:{type:'boolean',default:true},excludePdfAttachment:{type:'boolean'}}} },
  { name:'brevo.campaign.get', description:'Get one email campaign report. Permission READ; no approval.', inputSchema:{type:'object',additionalProperties:false,required:['campaignId'],properties:{campaignId:positiveId,statistics:{enum:['globalStats','linksStats','statsByDomain','statsByDevice','statsByBrowser']},excludeHtmlContent:{type:'boolean',default:true}}} },
  { name:'brevo.campaign.create', description:'Create a draft email campaign only. Permission WRITE; approval required.', inputSchema:{type:'object',additionalProperties:false,required:['name','sender','recipients','approval_token'],properties:{name:{type:'string',minLength:1,maxLength:200},sender,subject:{type:'string',maxLength:998},replyTo:email,htmlContent:{type:'string',maxLength:1000000},templateId:positiveId,recipients:{type:'object',additionalProperties:false,properties:{listIds:{type:'array',maxItems:50,items:positiveId},exclusionListIds:{type:'array',maxItems:50,items:positiveId},segmentIds:{type:'array',maxItems:50,items:positiveId}}},tag:{type:'string',maxLength:100},previewText:{type:'string',maxLength:500},approval_token:approval}} },
  { name:'brevo.campaign.send', description:'Immediately send an existing campaign. Permission HIGH_RISK; explicit approval required.', inputSchema:{type:'object',additionalProperties:false,required:['campaignId','approval_token'],properties:{campaignId:positiveId,approval_token:approval}} },
  { name:'brevo.transactional_email.send', description:'Send transactional email to explicit recipients. Permission HIGH_RISK; explicit approval required.', inputSchema:{type:'object',additionalProperties:false,required:['to','approval_token'],properties:{to:{type:'array',minItems:1,maxItems:99,items:recipient},sender,subject:{type:'string',maxLength:998},htmlContent:{type:'string',maxLength:1000000},textContent:{type:'string',maxLength:1000000},templateId:positiveId,replyTo:recipient,tags:{type:'array',maxItems:20,items:{type:'string',maxLength:100}},params:{type:'object',maxProperties:100,additionalProperties:true},scheduledAt:{type:'string',format:'date-time'},approval_token:approval}} },
  { name:'brevo.webhook.list', description:'List configured webhooks. Permission READ; no approval.', inputSchema:{type:'object',additionalProperties:false,properties:{type:{enum:['marketing','transactional','inbound']},sort:{enum:['asc','desc']}}} },
  { name:'brevo.webhook.create', description:'Create a webhook subscription to an HTTPS endpoint. Permission HIGH_RISK because Brevo will call an external URL; explicit approval required.', inputSchema:{type:'object',additionalProperties:false,required:['url','events','approval_token'],properties:{url:{type:'string',format:'uri',pattern:'^https://',maxLength:2048},description:{type:'string',maxLength:500},events:{type:'array',minItems:1,maxItems:30,uniqueItems:true,items:{type:'string',pattern:'^[a-zA-Z0-9._-]+$',maxLength:80}},type:{enum:['marketing','transactional','inbound'],default:'transactional'},approval_token:approval}} },
  { name:'brevo.webhook.delete', description:'Permanently delete a webhook. Permission DESTRUCTIVE; disabled by default and explicit approval required.', inputSchema:{type:'object',additionalProperties:false,required:['webhookId','approval_token'],properties:{webhookId:positiveId,approval_token:approval}} }
];
export function payloadWithoutApproval(args = {}) { const { approval_token: _ignored, ...rest } = args; return rest; }
