import { z } from "zod";import type { Risk } from "./policy.js";
const id=z.string().min(1).max(100),empty=z.object({}).strict();const obj=(p:Record<string,unknown>,r:string[]=[])=>({type:"object",additionalProperties:false,properties:p,required:r});
export type Tool={name:string;risk:Risk;description:string;schema:z.ZodTypeAny;inputSchema:Record<string,unknown>};
export const TOOLS:Tool[]=[
{name:"1password.server.health",risk:"READ",description:"Check Connect server health.",schema:empty,inputSchema:obj({})},
{name:"1password.vault.list",risk:"READ",description:"List accessible vaults.",schema:z.object({name:z.string().max(200).optional()}).strict(),inputSchema:obj({name:{type:"string",maxLength:200}})},
{name:"1password.vault.get",risk:"READ",description:"Get vault metadata.",schema:z.object({vaultId:id}).strict(),inputSchema:obj({vaultId:{type:"string"}},["vaultId"])},
{name:"1password.item.list",risk:"READ",description:"List item metadata; secret field values are not returned by list endpoint.",schema:z.object({vaultId:id,title:z.string().max(200).optional(),tag:z.string().max(100).optional()}).strict(),inputSchema:obj({vaultId:{type:"string"},title:{type:"string"},tag:{type:"string"}},["vaultId"])},
{name:"1password.item.get_redacted",risk:"READ",description:"Get an item with concealed/password field values redacted before returning to the agent.",schema:z.object({vaultId:id,itemId:id}).strict(),inputSchema:obj({vaultId:{type:"string"},itemId:{type:"string"}},["vaultId","itemId"])},
{name:"1password.file.list",risk:"READ",description:"List file metadata for an item; file content is not returned.",schema:z.object({vaultId:id,itemId:id}).strict(),inputSchema:obj({vaultId:{type:"string"},itemId:{type:"string"}},["vaultId","itemId"])},
{name:"1password.activity.list",risk:"READ",description:"List Connect API activity.",schema:z.object({limit:z.number().int().min(1).max(100).optional(),offset:z.number().int().min(0).optional()}).strict(),inputSchema:obj({limit:{type:"integer",minimum:1,maximum:100},offset:{type:"integer",minimum:0}})},
{name:"1password.item.create",risk:"WRITE",description:"Create an item in a vault from a bounded FullItem-compatible object.",schema:z.object({vaultId:id,title:z.string().min(1).max(200),category:z.enum(["LOGIN","PASSWORD","API_CREDENTIAL","SERVER","DATABASE","SECURE_NOTE","SSH_KEY"]),tags:z.array(z.string().max(100)).max(20).optional(),fields:z.array(z.record(z.unknown())).max(50).optional()}).strict(),inputSchema:obj({vaultId:{type:"string"},title:{type:"string"},category:{type:"string",enum:["LOGIN","PASSWORD","API_CREDENTIAL","SERVER","DATABASE","SECURE_NOTE","SSH_KEY"]},tags:{type:"array",items:{type:"string"},maxItems:20},fields:{type:"array",items:{type:"object"},maxItems:50}},["vaultId","title","category"])},
{name:"1password.item.replace",risk:"WRITE",description:"Replace an existing item. Requires the complete replacement item object.",schema:z.object({vaultId:id,itemId:id,item:z.record(z.unknown())}).strict(),inputSchema:obj({vaultId:{type:"string"},itemId:{type:"string"},item:{type:"object"}},["vaultId","itemId","item"])},
{name:"1password.item.archive",risk:"DESTRUCTIVE",description:"Archive/delete an item through the Connect API. Disabled by default.",schema:z.object({vaultId:id,itemId:id}).strict(),inputSchema:obj({vaultId:{type:"string"},itemId:{type:"string"}},["vaultId","itemId"])}];
export const TOOL_MAP=new Map(TOOLS.map(t=>[t.name,t]));
