import {z} from "zod";import {BetterStackClient}from"./client.js";import{authorize,Risk}from"./security.js";
const sid=z.union([z.string().min(1).max(100),z.number().int().positive()]).transform(String);const approval=z.boolean().optional();const page=z.number().int().min(1).max(10000).default(1);const q=(o:Record<string,unknown>)=>{const p=new URLSearchParams();for(const[k,v]of Object.entries(o))if(v!==undefined)p.set(k,String(v));const s=p.toString();return s?`?${s}`:""};
export type Def={name:string;description:string;risk:Risk;schema:z.ZodTypeAny;run:(a:any,c:BetterStackClient)=>Promise<unknown>};
export const tools:Def[]=[
{name:"betterstack.monitor.list",description:"List uptime monitors.",risk:"READ",schema:z.object({page,teamName:z.string().min(1).optional()}).strict(),run:(a,c)=>c.request("GET","/monitors"+q({page:a.page,team_name:a.teamName}))},
{name:"betterstack.monitor.get",description:"Get an uptime monitor.",risk:"READ",schema:z.object({id:sid}).strict(),run:(a,c)=>c.request("GET",`/monitors/${a.id}`)},
{name:"betterstack.monitor.create",description:"Create an uptime monitor.",risk:"WRITE",schema:z.object({url:z.string().url(),pronounceableName:z.string().min(1).max(200).optional(),monitorType:z.enum(["status","keyword","keyword_absence","ping","tcp","udp","smtp","pop","imap","dns"]).default("status"),paused:z.boolean().optional(),approved:approval}).strict(),run:(a,c)=>{authorize("WRITE",a.approved);return c.request("POST","/monitors",{url:a.url,pronounceable_name:a.pronounceableName,monitor_type:a.monitorType,paused:a.paused},false)}},
{name:"betterstack.monitor.update",description:"Update selected monitor settings.",risk:"WRITE",schema:z.object({id:sid,pronounceableName:z.string().min(1).max(200).optional(),paused:z.boolean().optional(),verifySsl:z.boolean().optional(),approved:approval}).strict().refine(x=>x.pronounceableName!==undefined||x.paused!==undefined||x.verifySsl!==undefined),run:(a,c)=>{authorize("WRITE",a.approved);return c.request("PATCH",`/monitors/${a.id}`,{pronounceable_name:a.pronounceableName,paused:a.paused,verify_ssl:a.verifySsl},false)}},
{name:"betterstack.monitor.delete",description:"Delete a monitor.",risk:"DESTRUCTIVE",schema:z.object({id:sid,approved:approval}).strict(),run:(a,c)=>{authorize("DESTRUCTIVE",a.approved);return c.request("DELETE",`/monitors/${a.id}`,undefined,false)}},
{name:"betterstack.incident.list",description:"List incidents with supported filters.",risk:"READ",schema:z.object({page,resolved:z.boolean().optional(),acknowledged:z.boolean().optional(),monitorId:sid.optional(),from:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),to:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional()}).strict(),run:(a,c)=>c.request("GET","/incidents"+q({page:a.page,resolved:a.resolved,acknowledged:a.acknowledged,monitor_id:a.monitorId,from:a.from,to:a.to}))},
{name:"betterstack.incident.get",description:"Get incident details.",risk:"READ",schema:z.object({id:sid}).strict(),run:(a,c)=>c.request("GET",`/incidents/${a.id}`)},
{name:"betterstack.incident.create",description:"Create a manual incident and optionally notify responders.",risk:"HIGH_RISK",schema:z.object({summary:z.string().min(1).max(500),requesterEmail:z.string().email(),description:z.string().max(10000).optional(),email:z.boolean().optional(),sms:z.boolean().optional(),call:z.boolean().optional(),push:z.boolean().optional(),approved:approval}).strict(),run:(a,c)=>{authorize("HIGH_RISK",a.approved);return c.request("POST","/incidents",{summary:a.summary,requester_email:a.requesterEmail,description:a.description,email:a.email,sms:a.sms,call:a.call,push:a.push},false)}},
{name:"betterstack.incident.acknowledge",description:"Acknowledge an ongoing incident.",risk:"HIGH_RISK",schema:z.object({id:sid,approved:approval}).strict(),run:(a,c)=>{authorize("HIGH_RISK",a.approved);return c.request("POST",`/incidents/${a.id}/acknowledge`,undefined,false)}},
{name:"betterstack.incident.resolve",description:"Resolve an ongoing incident.",risk:"HIGH_RISK",schema:z.object({id:sid,approved:approval}).strict(),run:(a,c)=>{authorize("HIGH_RISK",a.approved);return c.request("POST",`/incidents/${a.id}/resolve`,undefined,false)}},
{name:"betterstack.incident.escalate",description:"Escalate an ongoing incident.",risk:"HIGH_RISK",schema:z.object({id:sid,escalationType:z.enum(["User","Team","Schedule","Policy","Organization"]),userEmail:z.string().email().optional(),userId:z.number().int().positive().optional(),teamName:z.string().min(1).optional(),teamId:z.number().int().positive().optional(),scheduleId:z.number().int().positive().optional(),policyId:z.number().int().positive().optional(),approved:approval}).strict(),run:(a,c)=>{authorize("HIGH_RISK",a.approved);return c.request("POST",`/incidents/${a.id}/escalate`,{escalation_type:a.escalationType,user_email:a.userEmail,user_id:a.userId,team_name:a.teamName,team_id:a.teamId,schedule_id:a.scheduleId,policy_id:a.policyId},false)}},
{name:"betterstack.metadata.list",description:"List metadata, optionally scoped to a resource.",risk:"READ",schema:z.object({page,ownerId:sid.optional(),ownerType:z.enum(["Monitor","Heartbeat","Incident","WebhookIntegration","EmailIntegration","IncomingWebhook","CallRouting"]).optional()}).strict(),run:(a,c)=>c.request("GET","/metadata"+q({page:a.page,owner_id:a.ownerId,owner_type:a.ownerType}))},
{name:"betterstack.metadata.update",description:"Create, replace, merge, or remove metadata values for a resource key.",risk:"WRITE",schema:z.object({ownerId:sid,ownerType:z.enum(["Monitor","Heartbeat","Incident","WebhookIntegration","EmailIntegration","IncomingWebhook","CallRouting"]),key:z.string().min(1).max(200),values:z.array(z.object({type:z.string().min(1).optional(),value:z.union([z.string(),z.number(),z.boolean()])}).strict()).max(100),mode:z.enum(["replace","merge"]).default("replace"),approved:approval}).strict(),run:(a,c)=>{authorize("WRITE",a.approved);return c.request("POST","/metadata",{owner_id:a.ownerId,owner_type:a.ownerType,key:a.key,values:a.values,mode:a.mode},false)}}];
export async function execute(name:string,input:unknown,client=new BetterStackClient()){const t=tools.find(x=>x.name===name);if(!t)throw new Error("Unknown tool");return t.run(t.schema.parse(input),client)}
