import {z} from "zod";import {SplitClient} from "./client.js";import {authorize,Risk} from "./security.js";
const id=z.string().min(1).max(200);const name=z.string().min(1).max(200);const page=z.object({offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(50).default(20)}).strict();
export const defs=[
["split.project.list","READ",z.object({}).strict(),()=>["/internal/api/v2/workspaces","GET"]],
["split.environment.list","READ",z.object({workspaceId:id}).strict(),(a:any)=>[`/internal/api/v2/environments/ws/${a.workspaceId}`,"GET"]],
["split.traffic_type.list","READ",z.object({workspaceId:id}).strict(),(a:any)=>[`/internal/api/v2/trafficTypes/ws/${a.workspaceId}`,"GET"]],
["split.feature_flag.list","READ",z.object({workspaceId:id,offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(50).default(20),tag:z.string().optional()}).strict(),(a:any)=>[`/internal/api/v2/splits/ws/${a.workspaceId}/?offset=${a.offset}&limit=${a.limit}${a.tag?`&tag=${encodeURIComponent(a.tag)}`:""}`,"GET"]],
["split.feature_flag.get","READ",z.object({workspaceId:id,name}).strict(),(a:any)=>[`/internal/api/v2/splits/ws/${a.workspaceId}/${encodeURIComponent(a.name)}`,"GET"]],
["split.feature_flag.definition.get","READ",z.object({workspaceId:id,name,environment:id}).strict(),(a:any)=>[`/internal/api/v2/splits/ws/${a.workspaceId}/${encodeURIComponent(a.name)}/environments/${encodeURIComponent(a.environment)}`,"GET"]],
["split.feature_flag.create","WRITE",z.object({workspaceId:id,trafficType:id,name,description:z.string().max(1000).optional(),approved:z.boolean().default(false)}).strict(),(a:any)=>[`/internal/api/v2/splits/ws/${a.workspaceId}/trafficTypes/${encodeURIComponent(a.trafficType)}`,"POST",{name:a.name,description:a.description}]],
["split.feature_flag.definition.create","HIGH_RISK",z.object({workspaceId:id,name,environment:id,treatments:z.array(z.object({name}).passthrough()).min(2),defaultTreatment:name,defaultRule:z.array(z.object({treatment:name,size:z.number().min(0).max(100)}).strict()).min(1),comment:z.string().max(1000).optional(),approved:z.boolean()}).strict(),(a:any)=>[`/internal/api/v2/splits/ws/${a.workspaceId}/${encodeURIComponent(a.name)}/environments/${encodeURIComponent(a.environment)}`,"POST",{treatments:a.treatments,defaultTreatment:a.defaultTreatment,defaultRule:a.defaultRule,comment:a.comment}]],
["split.feature_flag.definition.update","HIGH_RISK",z.object({workspaceId:id,name,environment:id,patch:z.array(z.object({op:z.enum(["add","replace","remove"]),path:z.string().regex(/^\/(defaultTreatment|trafficAllocation|rules|treatments|baselineTreatment)(\/.*)?$/),value:z.unknown().optional()}).strict()).min(1).max(20),approved:z.boolean()}).strict(),(a:any)=>[`/internal/api/v2/splits/ws/${a.workspaceId}/${encodeURIComponent(a.name)}/environments/${encodeURIComponent(a.environment)}`,"PATCH",a.patch]],
["split.feature_flag.tags.set","WRITE",z.object({workspaceId:id,name,tags:z.array(z.string().min(1).max(100)).max(50),approved:z.boolean().default(false)}).strict(),(a:any)=>[`/internal/api/v2/tags/ws/${a.workspaceId}/object/${encodeURIComponent(a.name)}/objecttype/Split`,"POST",{tags:a.tags}]]
] as const;
export async function invoke(tool:string,input:unknown,client=new SplitClient()){const d:any=defs.find(x=>x[0]===tool);if(!d)throw new Error("Unknown tool");const a=d[2].parse(input);authorize(d[1] as Risk,(a as any).approved);const [path,method,body]=d[3](a);return client.request(path,{method,body:body===undefined?undefined:JSON.stringify(body)})}
