import test from 'node:test'; import assert from 'node:assert/strict'; import { loadConfig,approvalDigest } from '../src/auth/config.js'; import { POLICY,authorize } from '../src/tools/policy.js'; import { TOOLS } from '../src/tools/definitions.js'; import { ConvexClient,ConvexApiError } from '../src/client/convex-client.js';
test('registry matches policy and has 11 tools',()=>{assert.equal(TOOLS.length,11);assert.deepEqual(TOOLS.map(x=>x.name).sort(),Object.keys(POLICY).sort());});
test('auth config rejects missing token and non-https',()=>{assert.throws(()=>loadConfig({}),/required/);assert.throws(()=>loadConfig({CONVEX_MANAGEMENT_TOKEN:'x',CONVEX_MANAGEMENT_API_URL:'http://x'}),/HTTPS/);});
test('destructive actions disabled by default',()=>assert.throws(()=>authorize({destructiveEnabled:false},'convex.project.delete',{projectId:'1'},''),/disabled/));
test('approval is payload-bound',()=>{const c={destructiveEnabled:true,approvalSecret:'secret'},p={projectId:'1'},t=approvalDigest(c.approvalSecret,'convex.project.delete',p);assert.doesNotThrow(()=>authorize(c,'convex.project.delete',p,t));assert.throws(()=>authorize(c,'convex.project.delete',{projectId:'2'},t),/Invalid/);});
test('client isolates bearer credential and encodes path',async()=>{let seen;const f=async(url,init)=>{seen={url:String(url),init};return new Response('{}',{status:200});};const c=new ConvexClient({baseUrl:'https://api.convex.dev/v1',token:'tok',timeoutMs:1000,maxRetries:0},f);await c.getProject({team:'team one',projectSlug:'app'});assert.equal(seen.init.headers.Authorization,'Bearer tok');assert.match(seen.url,/team%20one/);});
test('401 is not retried',async()=>{let n=0;const f=async()=>{n++;return new Response(JSON.stringify({message:'no'}),{status:401});};const c=new ConvexClient({baseUrl:'https://api.convex.dev/v1',token:'x',timeoutMs:1000,maxRetries:3},f);await assert.rejects(c.listProjects({teamId:'1'}),e=>e instanceof ConvexApiError&&e.status===401);assert.equal(n,1);});
test('429 GET is retried',async()=>{let n=0;const f=async()=>{n++;return n===1?new Response('{}',{status:429,headers:{'retry-after':'0'}}):new Response('{"ok":true}',{status:200});};const c=new ConvexClient({baseUrl:'https://api.convex.dev/v1',token:'x',timeoutMs:1000,maxRetries:1},f);assert.deepEqual(await c.listDeployments({projectId:'1'}),{ok:true});assert.equal(n,2);});
test('destructive POST is never blindly retried',async()=>{let n=0;const f=async()=>{n++;return new Response('{}',{status:503});};const c=new ConvexClient({baseUrl:'https://api.convex.dev/v1',token:'x',timeoutMs:1000,maxRetries:3},f);await assert.rejects(c.deleteDeployment({deploymentName:'prod'}));assert.equal(n,1);});
