import {z} from 'zod';import {uiComponent} from '@team-plain/typescript-sdk';import {approval,call,Risk} from './core.js';
export type Tool={name:string;description:string;risk:Risk;schema:z.ZodObject<any>;run:(x:any)=>Promise<unknown>};
const id=z.string().min(3).max(100);const email=z.string().email();
export const tools:Tool[]=[
{name:'plain.customer.upsert',description:'Create or update a customer by email',risk:'WRITE',schema:z.object({email,fullName:z.string().min(1).max(200)}).strict(),run:x=>{approval('WRITE');return call('upsertCustomer',{identifier:{emailAddress:x.email},onCreate:{fullName:x.fullName,email:{email:x.email,isVerified:false}},onUpdate:{fullName:x.fullName}})}},
{name:'plain.thread.create',description:'Create a support thread for a customer',risk:'WRITE',schema:z.object({customerId:id,title:z.string().min(1).max(300),text:z.string().min(1).max(20000)}).strict(),run:x=>{approval('WRITE');return call('createThread',{customerIdentifier:{customerId:x.customerId},title:x.title,components:[uiComponent.text({text:x.text})]})}},
{name:'plain.thread.reply',description:'Send a reply to a customer thread',risk:'HIGH_RISK',schema:z.object({threadId:id,text:z.string().min(1).max(20000),approved:z.literal(true)}).strict(),run:x=>{approval('HIGH_RISK',x.approved);return call('replyToThread',{threadId:x.threadId,textContent:x.text})}},
{name:'plain.thread.assign',description:'Assign a thread to exactly one user or machine user',risk:'WRITE',schema:z.object({threadId:id,userId:id.optional(),machineUserId:id.optional()}).strict(),run:x=>{if((!!x.userId)===(!!x.machineUserId))throw new Error('Provide exactly one assignee');approval('WRITE');return call('assignThread',x)}},
{name:'plain.thread.unassign',description:'Remove the current assignee from a thread',risk:'WRITE',schema:z.object({threadId:id}).strict(),run:x=>{approval('WRITE');return call('unassignThread',x)}},
{name:'plain.thread.event.create',description:'Add contextual event to a thread',risk:'WRITE',schema:z.object({threadId:id,title:z.string().min(1).max(200),text:z.string().min(1).max(5000),externalId:z.string().max(200).optional()}).strict(),run:x=>{approval('WRITE');return call('createThreadEvent',{threadId:x.threadId,title:x.title,components:[uiComponent.text({text:x.text})],externalId:x.externalId})}},
{name:'plain.thread.priority.update',description:'Set thread priority',risk:'WRITE',schema:z.object({threadId:id,priority:z.enum(['URGENT','HIGH','MEDIUM','LOW'])}).strict(),run:x=>{approval('WRITE');return call('updateThreadPriority',x)}},
{name:'plain.customer.delete',description:'Delete a customer and associated data asynchronously',risk:'DESTRUCTIVE',schema:z.object({customerId:id,approved:z.literal(true),confirmation:z.literal('DELETE CUSTOMER')}).strict(),run:x=>{approval('DESTRUCTIVE',x.approved);return call('deleteCustomer',{customerId:x.customerId})}}
];
