import { RISK } from "./policy.js";

const domain = { type: "string", minLength: 3, maxLength: 253, pattern: "^(?=.{1,253}$)([A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z]{2,63}$" };
const approval = { type: "string", pattern: "^[a-f0-9]{64}$", description: "Payload-bound approval generated by a trusted approval service." };
const recordId = { type: "string", minLength: 1, maxLength: 32, pattern: "^[0-9]+$" };
const dnsType = { type: "string", enum: ["A","AAAA","CNAME","MX","TXT","NS","SRV","CAA","ALIAS","TLSA","HTTPS","SVCB","SSHFP"] };
const dnsName = { type: "string", maxLength: 253, description: "Record host/name. Use empty string for the zone apex when supported by Porkbun." };
const dnsContent = { type: "string", minLength: 1, maxLength: 4096 };

function obj(properties = {}, required = []) {
  return { type: "object", additionalProperties: false, properties, required };
}

export const tools = [
  { name: "porkbun.connectivity.ping", upstream: "ping", risk: RISK.READ, description: "Verify Porkbun API connectivity and configured credentials.", inputSchema: obj() },
  { name: "porkbun.domain.check", upstream: "check_domain", risk: RISK.READ, description: "Check domain availability and price without registering it.", inputSchema: obj({ domain }, ["domain"]) },
  { name: "porkbun.pricing.get", upstream: "get_pricing", risk: RISK.READ, description: "Get current Porkbun TLD registration, renewal and transfer pricing.", inputSchema: obj() },
  { name: "porkbun.domain.list", upstream: "list_domains", risk: RISK.READ, description: "List domains in the authenticated Porkbun account.", inputSchema: obj() },
  { name: "porkbun.domain.get", upstream: "get_domain", risk: RISK.READ, description: "Get metadata for one domain in the authenticated account.", inputSchema: obj({ domain }, ["domain"]) },
  { name: "porkbun.nameserver.get", upstream: "get_nameservers", risk: RISK.READ, description: "Read authoritative nameservers for a domain.", inputSchema: obj({ domain }, ["domain"]) },
  { name: "porkbun.dns.record.list", upstream: "list_dns_records", risk: RISK.READ, description: "List DNS records for a domain.", inputSchema: obj({ domain }, ["domain"]) },
  { name: "porkbun.dns.record.create", upstream: "create_dns_record", risk: RISK.WRITE, description: "Create a DNS record. Requires human approval by default.", inputSchema: obj({ domain, name: dnsName, type: dnsType, content: dnsContent, ttl: { type: "integer", minimum: 300, maximum: 604800 }, prio: { type: "integer", minimum: 0, maximum: 65535 }, approval_token: approval }, ["domain","name","type","content"]) },
  { name: "porkbun.dns.record.update", upstream: "update_dns_record", risk: RISK.WRITE, description: "Update a DNS record by numeric record ID. Requires human approval by default.", inputSchema: obj({ domain, record_id: recordId, name: dnsName, type: dnsType, content: dnsContent, ttl: { type: "integer", minimum: 300, maximum: 604800 }, prio: { type: "integer", minimum: 0, maximum: 65535 }, approval_token: approval }, ["domain","record_id","name","type","content"]) },
  { name: "porkbun.dns.record.delete", upstream: "delete_dns_record", risk: RISK.DESTRUCTIVE, description: "Delete one DNS record by ID. Disabled by default and requires explicit approval.", inputSchema: obj({ domain, record_id: recordId, approval_token: approval }, ["domain","record_id"]) },
  { name: "porkbun.nameserver.update", upstream: "update_nameservers", risk: RISK.HIGH_RISK, description: "Replace a domain's authoritative nameservers. Always requires explicit human approval.", inputSchema: obj({ domain, nameservers: { type: "array", minItems: 2, maxItems: 12, uniqueItems: true, items: { type: "string", minLength: 4, maxLength: 253, pattern: "^[A-Za-z0-9.-]+\\.?$" } }, approval_token: approval }, ["domain","nameservers"]) }
];

export const toolByName = new Map(tools.map((tool) => [tool.name, tool]));
export const upstreamAllowlist = new Set(tools.map((tool) => tool.upstream));

export function upstreamArguments(args) {
  const clean = { ...args };
  delete clean.approval_token;
  return clean;
}
