import test from 'node:test'; import assert from 'node:assert/strict'; import {LogSnagClient,LogSnagError} from '../src/client.js'; import {handlers,eventSchema} from '../src/tools.js';
const response=(status:number,body='{}',headers:Record<string,string>={})=>new Response(body,{status,headers});
test('rejects invalid channel and unknown input',()=>{assert.throws(()=>eventSchema.parse({channel:'Bad_Channel',event:'x',extra:true}));});
test('requires approval for writes',async()=>{const c=new LogSnagClient({token:'x',fetchImpl:async()=>response(200)});const h=handlers(c,{defaultProject:'demo',requireWriteApproval:true,allowNotifications:false});await assert.rejects(()=>h.eventPublish({channel:'ops',event:'Deploy'}),/approval/);});
test('notification needs server opt-in',async()=>{const c=new LogSnagClient({token:'x',fetchImpl:async()=>response(200)});const h=handlers(c,{defaultProject:'demo',requireWriteApproval:false,allowNotifications:false});await assert.rejects(()=>h.eventNotify({channel:'ops',event:'Deploy',approval:true}),/disabled/);});
test('publishes event without leaking token into body',async()=>{let req:RequestInit|undefined;const c=new LogSnagClient({token:'secret',fetchImpl:async(_u,i)=>{req=i;return response(200,'{"ok":true}')}});const h=handlers(c,{defaultProject:'demo',requireWriteApproval:false,allowNotifications:false});await h.eventPublish({channel:'ops',event:'Deploy'});assert.match(String((req?.headers as Record<string,string>).Authorization),/secret/);assert.doesNotMatch(String(req?.body),/secret/);assert.match(String(req?.body),/"notify":false/);});
test('maps 401 without retry',async()=>{let n=0;const c=new LogSnagClient({token:'x',maxRetries:2,fetchImpl:async()=>{n++;return response(401,'bad token')}});await assert.rejects(()=>c.post('/v1/log',{}),e=>e instanceof LogSnagError&&e.status===401);assert.equal(n,1);});
test('retries throttling and succeeds',async()=>{let n=0;const c=new LogSnagClient({token:'x',maxRetries:1,fetchImpl:async()=>{n++;return n===1?response(429,'slow'):response(200,'{"ok":true}')}});await c.post('/v1/log',{});assert.equal(n,2);});
test('increment uses PATCH mutation',async()=>{let method='';let body='';const c=new LogSnagClient({token:'x',fetchImpl:async(_u,i)=>{method=String(i?.method);body=String(i?.body);return response(200)}});const h=handlers(c,{defaultProject:'demo',requireWriteApproval:false,allowNotifications:false});await h.insightIncrement({title:'Users',value:2});assert.equal(method,'PATCH');assert.match(body,/"\$inc":2/);});
