import {Server} from '@modelcontextprotocol/sdk/server/index.js';
import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';
import {CallToolRequestSchema,ListToolsRequestSchema} from '@modelcontextprotocol/sdk/types.js';
import {z} from 'zod';
import {loadConfig} from './config.js'; import {authorize,type Risk} from './policy.js'; import {KoyebRestClient} from './client.js'; import {KoyebOfficialMcp} from './upstream-mcp.js';
const cfg=loadConfig(), rest=new KoyebRestClient(cfg), mcp=new KoyebOfficialMcp(cfg);
const id=z.string().uuid(); const page=z.object({limit:z.number().int().min(1).max(100).optional(),offset:z.number().int().min(0).optional()});
type Def={name:string;description:string;risk:Risk;schema:z.ZodTypeAny;run:(a:any)=>Promise<unknown>}; const defs=new Map<string,Def>();
function add(name:string,d:Def){defs.set(name,d)} function approval(s:z.ZodRawShape){return z.object({...s,approved:z.boolean().optional()}).strict()}
add('koyeb.app.list',{name:'koyeb.app.list',description:'List Koyeb apps',risk:'READ',schema:page.extend({name:z.string().max(128).optional()}).strict(),run:a=>mcp.call('list-apps',{query:{...a,limit:a.limit?.toString(),offset:a.offset?.toString()}})});
add('koyeb.app.get',{name:'koyeb.app.get',description:'Get an app by UUID',risk:'READ',schema:z.object({id}).strict(),run:a=>mcp.call('get-app',{path:{id:a.id}})});
add('koyeb.app.create',{name:'koyeb.app.create',description:'Create an app',risk:'WRITE',schema:approval({name:z.string().min(1).max(63).regex(/^[A-Za-z0-9-]+$/)}),run:a=>mcp.call('create-app',{body:{name:a.name}})});
add('koyeb.app.pause',{name:'koyeb.app.pause',description:'Pause an app',risk:'HIGH_RISK',schema:approval({id}),run:a=>rest.request('POST',`/v1/apps/${a.id}/pause`)});
add('koyeb.app.resume',{name:'koyeb.app.resume',description:'Resume an app',risk:'HIGH_RISK',schema:approval({id}),run:a=>rest.request('POST',`/v1/apps/${a.id}/resume`)});
add('koyeb.app.delete',{name:'koyeb.app.delete',description:'Delete an app',risk:'DESTRUCTIVE',schema:approval({id}),run:a=>rest.request('DELETE',`/v1/apps/${a.id}`)});
add('koyeb.service.list',{name:'koyeb.service.list',description:'List services',risk:'READ',schema:page.extend({app_id:id.optional(),name:z.string().max(128).optional()}).strict(),run:a=>mcp.call('list-services',{query:{...a,limit:a.limit?.toString(),offset:a.offset?.toString()}})});
add('koyeb.service.get',{name:'koyeb.service.get',description:'Get service',risk:'READ',schema:z.object({id}).strict(),run:a=>mcp.call('get-service',{path:{id:a.id}})});
add('koyeb.deployment.list',{name:'koyeb.deployment.list',description:'List deployments',risk:'READ',schema:page.extend({app_id:id.optional(),service_id:id.optional()}).strict(),run:a=>mcp.call('list-deployments',{query:{...a,limit:a.limit?.toString(),offset:a.offset?.toString()}})});
add('koyeb.deployment.get',{name:'koyeb.deployment.get',description:'Get deployment',risk:'READ',schema:z.object({id}).strict(),run:a=>mcp.call('get-deployment',{path:{id:a.id}})});
add('koyeb.instance.list',{name:'koyeb.instance.list',description:'List instances',risk:'READ',schema:page.extend({app_id:id.optional(),service_id:id.optional(),deployment_id:id.optional()}).strict(),run:a=>mcp.call('list-instances',{query:{...a,limit:a.limit?.toString(),offset:a.offset?.toString()}})});
add('koyeb.instance.get',{name:'koyeb.instance.get',description:'Get instance',risk:'READ',schema:z.object({id}).strict(),run:a=>mcp.call('get-instance',{path:{id:a.id}})});
add('koyeb.domain.list',{name:'koyeb.domain.list',description:'List custom domains',risk:'READ',schema:page.strict(),run:a=>rest.request('GET','/v1/domains',undefined,a)});
add('koyeb.secret.list',{name:'koyeb.secret.list',description:'List secret metadata; values are never returned by this connector',risk:'READ',schema:page.strict(),run:a=>rest.request('GET','/v1/secrets',undefined,a)});
add('koyeb.secret.create',{name:'koyeb.secret.create',description:'Create an organization secret',risk:'HIGH_RISK',schema:approval({name:z.string().min(1).max(128),value:z.string().min(1).max(65536)}),run:a=>rest.request('POST','/v1/secrets',{name:a.name,value:a.value})});
add('koyeb.secret.delete',{name:'koyeb.secret.delete',description:'Delete a secret',risk:'DESTRUCTIVE',schema:approval({id}),run:a=>rest.request('DELETE',`/v1/secrets/${a.id}`)});
const server=new Server({name:'koyeb-connector',version:'1.0.0'},{capabilities:{tools:{}}});
server.setRequestHandler(ListToolsRequestSchema,async()=>({tools:[...defs.values()].map(d=>({name:d.name,description:`${d.description} Risk=${d.risk}. ${d.risk==='READ'?'No approval required.':'Set approved=true after human approval.'}`,inputSchema:z.toJSONSchema?z.toJSONSchema(d.schema as any):{type:'object'}}))}));
server.setRequestHandler(CallToolRequestSchema,async req=>{const d=defs.get(req.params.name); if(!d)return {isError:true,content:[{type:'text',text:'Unknown tool'}]}; try{const a=d.schema.parse(req.params.arguments||{}); authorize(d.risk,a.approved,{requireWriteApproval:cfg.requireWriteApproval,destructiveEnabled:cfg.destructiveEnabled}); const out=await d.run(a); return {content:[{type:'text',text:JSON.stringify({provider:'koyeb',untrusted_data:true,result:out},null,2)}]};}catch(e){return {isError:true,content:[{type:'text',text:e instanceof Error?e.message:'Unknown error'}]}}});
await server.connect(new StdioServerTransport());
