import {McpServer} from "@modelcontextprotocol/sdk/server/mcp.js";
import {z} from "zod";
import type {Config} from "./config.js";import {requireApproval,type Risk} from "./policy.js";import type {WiseClient} from "./client.js";
export type Spec={name:string;description:string;risk:Risk};
export const TOOL_SPECS:Spec[]=[
{name:"wise.quote.create",description:"Create an authenticated Wise quote for a profile.",risk:"WRITE"},{name:"wise.quote.get",description:"Retrieve a quote by UUID.",risk:"READ"},{name:"wise.recipient.list",description:"List active recipient accounts for a profile.",risk:"READ"},{name:"wise.recipient.requirements",description:"Retrieve dynamic recipient requirements for a quote.",risk:"READ"},{name:"wise.transfer.create",description:"Create a transfer using a quote and recipient. Does not fund it.",risk:"HIGH_RISK"},{name:"wise.transfer.get",description:"Retrieve a transfer by ID.",risk:"READ"},{name:"wise.transfer.cancel",description:"Cancel an eligible transfer.",risk:"DESTRUCTIVE"},{name:"wise.transfer.fund_from_balance",description:"Fund a transfer from a Wise balance; moves money externally.",risk:"HIGH_RISK"},{name:"wise.balance.list",description:"List STANDARD/SAVINGS balances for a profile.",risk:"READ"},{name:"wise.balance.get",description:"Get one balance account.",risk:"READ"},{name:"wise.balance.statement",description:"Retrieve a JSON balance statement for a bounded period.",risk:"READ"},{name:"wise.account_details.list",description:"List available/active receiving account details for a profile.",risk:"READ"}];
const id=z.number().int().positive();const uuid=z.string().uuid();const approval=z.enum(["approved","approved-high-risk"]).optional();const currency=z.string().regex(/^[A-Z]{3}$/);
const schemas:any={
"wise.quote.create":z.object({profileId:id,sourceCurrency:currency,targetCurrency:currency,sourceAmount:z.number().positive().optional(),targetAmount:z.number().positive().optional(),targetAccount:id.optional(),payOut:z.string().max(40).optional(),preferredPayIn:z.string().max(40).optional(),approval}).strict(),
"wise.quote.get":z.object({profileId:id,quoteId:uuid}).strict(),
"wise.recipient.list":z.object({profileId:id,currency:currency.optional(),size:z.number().int().min(1).max(100).default(20),seekPosition:z.number().int().min(0).default(0)}).strict(),
"wise.recipient.requirements":z.object({quoteId:uuid}).strict(),
"wise.transfer.create":z.object({profileId:id,targetAccount:id,quoteId:uuid,customerTransactionId:uuid,reference:z.string().min(1).max(100).optional(),approval}).strict(),
"wise.transfer.get":z.object({transferId:id}).strict(),
"wise.transfer.cancel":z.object({transferId:id,approval}).strict(),
"wise.transfer.fund_from_balance":z.object({profileId:id,transferId:id,balanceId:id,approval}).strict(),
"wise.balance.list":z.object({profileId:id,types:z.array(z.enum(["STANDARD","SAVINGS"])).min(1).max(2).default(["STANDARD"])}).strict(),
"wise.balance.get":z.object({profileId:id,balanceId:id}).strict(),
"wise.balance.statement":z.object({profileId:id,balanceId:id,currency,intervalStart:z.string().datetime(),intervalEnd:z.string().datetime(),type:z.enum(["COMPACT","FLAT"]).default("COMPACT"),statementLocale:z.string().regex(/^[a-z]{2}$/).default("en")}).strict(),
"wise.account_details.list":z.object({profileId:id}).strict()};
const q=(o:Record<string,unknown>)=>{const p=new URLSearchParams();for(const[k,v]of Object.entries(o))if(v!==undefined)p.set(k,String(v));return p.toString()?`?${p}`:""};
function validateBusinessRules(name:string,v:any){if(name==="wise.quote.create"&&Number(v.sourceAmount!==undefined)+Number(v.targetAmount!==undefined)!==1)throw new Error("Provide exactly one of sourceAmount or targetAmount");if(name==="wise.balance.statement"){const a=new Date(v.intervalStart).getTime(),b=new Date(v.intervalEnd).getTime();if(b<=a)throw new Error("intervalEnd must be after intervalStart");if(b-a>469*86400000)throw new Error("statement period cannot exceed 469 days")}}
export async function executeTool(spec:Spec,input:Record<string,unknown>,client:WiseClient,c:Config){const v=schemas[spec.name].parse(input) as any;validateBusinessRules(spec.name,v);requireApproval(spec.risk,v.approval,c);delete v.approval;switch(spec.name){case"wise.quote.create":{const{profileId,...body}=v;return client.request("POST",`/profiles/${profileId}/quotes`,body)}case"wise.quote.get":return client.request("GET",`/profiles/${v.profileId}/quotes/${v.quoteId}`);case"wise.recipient.list":return client.request("GET",`/accounts${q({profileId:v.profileId,currency:v.currency,active:true,size:v.size,seekPosition:v.seekPosition})}`);case"wise.recipient.requirements":return client.request("GET",`/quotes/${v.quoteId}/account-requirements`);case"wise.transfer.create":{const{profileId,quoteId,reference,targetAccount,customerTransactionId}=v;return client.request("POST",`/profiles/${profileId}/transfers`,{targetAccount,quoteUuid:quoteId,customerTransactionId,details:reference?{reference}:undefined})}case"wise.transfer.get":return client.request("GET",`/transfers/${v.transferId}`);case"wise.transfer.cancel":return client.request("PUT",`/transfers/${v.transferId}/cancel`);case"wise.transfer.fund_from_balance":return client.request("POST",`/profiles/${v.profileId}/transfers/${v.transferId}/payments`,{type:"BALANCE",balanceId:v.balanceId});case"wise.balance.list":return client.request("GET",`/profiles/${v.profileId}/balances${q({types:v.types.join(",")})}`);case"wise.balance.get":return client.request("GET",`/profiles/${v.profileId}/balances/${v.balanceId}`);case"wise.balance.statement":return client.request("GET",`/profiles/${v.profileId}/balance-statements/${v.balanceId}/statement.json${q({currency:v.currency,intervalStart:v.intervalStart,intervalEnd:v.intervalEnd,type:v.type,statementLocale:v.statementLocale})}`);case"wise.account_details.list":return client.request("GET",`/profiles/${v.profileId}/account-details`);default:throw new Error("Unsupported tool")}}
export function registerTools(server:McpServer,client:WiseClient,c:Config){for(const s of TOOL_SPECS){const schema=schemas[s.name];server.tool(s.name,s.description,schema.shape,async(input)=>({content:[{type:"text",text:JSON.stringify({provider:"wise",tool:s.name,risk:s.risk,untrusted_provider_content:true,result:await executeTool(s,input as any,client,c)},null,2)}]}))}}
