export type Config={baseUrl:string;realm:string;authRealm:string;clientId?:string;clientSecret?:string;accessToken?:string;timeoutMs:number;maxRetries:number};
export class KeycloakError extends Error{constructor(message:string,public status?:number,public retryAfter?:number){super(message)}}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
export class KeycloakClient{
 private token?:{value:string;expiresAt:number};
 constructor(private c:Config,private fetcher:typeof fetch=fetch){}
 private async auth(){if(this.c.accessToken)return this.c.accessToken;if(this.token&&this.token.expiresAt>Date.now()+30000)return this.token.value;if(!this.c.clientId||!this.c.clientSecret)throw new KeycloakError('Configure KEYCLOAK_ACCESS_TOKEN or client credentials');const body=new URLSearchParams({grant_type:'client_credentials',client_id:this.c.clientId,client_secret:this.c.clientSecret});const r=await this.fetcher(`${this.c.baseUrl}/realms/${encodeURIComponent(this.c.authRealm)}/protocol/openid-connect/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new KeycloakError('Keycloak token acquisition failed',r.status);const j:any=await r.json();this.token={value:j.access_token,expiresAt:Date.now()+(Number(j.expires_in)||60)*1000};return this.token.value}
 async request(path:string,init:RequestInit={}){if(!path.startsWith('/'))throw new KeycloakError('Provider path must be relative');const method=(init.method||'GET').toUpperCase();const safe=method==='GET';for(let a=0;;a++){const ac=new AbortController();const t=setTimeout(()=>ac.abort(),this.c.timeoutMs);try{const token=await this.auth();const r=await this.fetcher(`${this.c.baseUrl}/admin/realms/${encodeURIComponent(this.c.realm)}${path}`,{...init,signal:ac.signal,headers:{accept:'application/json',...(init.body?{'content-type':'application/json'}:{}),authorization:`Bearer ${token}`,...init.headers}});if(r.status===401&&!this.c.accessToken)this.token=undefined;const retryAfter=Number(r.headers.get('retry-after')||0);if(safe&&(r.status===429||r.status>=500)&&a<this.c.maxRetries){await sleep(Math.min(retryAfter?retryAfter*1000:250*2**a,5000));continue}if(!r.ok){const text=(await r.text()).slice(0,1000);throw new KeycloakError(`Keycloak ${r.status}: ${text}`,r.status,retryAfter||undefined)}if(r.status===204)return null;const text=await r.text();return text?JSON.parse(text):null}catch(e:any){if(e?.name==='AbortError')throw new KeycloakError('Keycloak request timed out');throw e}finally{clearTimeout(t)}}}
}
export function loadConfig(env=process.env):Config{const base=env.KEYCLOAK_BASE_URL;if(!base)throw new Error('KEYCLOAK_BASE_URL is required');const u=new URL(base);if(u.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(u.hostname))throw new Error('KEYCLOAK_BASE_URL must use HTTPS except localhost');if(u.username||u.password||u.search||u.hash)throw new Error('KEYCLOAK_BASE_URL must be a credential-free origin');const realm=env.KEYCLOAK_REALM;if(!realm)throw new Error('KEYCLOAK_REALM is required');return{baseUrl:u.origin,realm,authRealm:env.KEYCLOAK_AUTH_REALM||realm,clientId:env.KEYCLOAK_CLIENT_ID,clientSecret:env.KEYCLOAK_CLIENT_SECRET,accessToken:env.KEYCLOAK_ACCESS_TOKEN,timeoutMs:Math.min(Math.max(Number(env.KEYCLOAK_TIMEOUT_MS)||15000,1000),120000),maxRetries:Math.min(Math.max(Number(env.KEYCLOAK_MAX_RETRIES)||2,0),5)}}
