import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';import {z} from 'zod';import {KeycloakClient,loadConfig} from './client.js';import {assertAllowed,Risk} from './policy.js';
const client=new KeycloakClient(loadConfig());const server=new McpServer({name:'keycloak-connector',version:'1.0.0'});const id=z.string().min(1).max(255).regex(/^[A-Za-z0-9._:-]+$/);const approved=z.boolean().default(false);const out=(data:any)=>({content:[{type:'text' as const,text:JSON.stringify({ok:true,untrustedProviderData:true,data})}]});
function tool(name:string,desc:string,risk:Risk,schema:any,fn:(a:any)=>Promise<any>){server.tool(name,desc,schema,async(a:any)=>{assertAllowed(risk,Boolean(a.approved));try{return out(await fn(a))}catch(e:any){return{isError:true,content:[{type:'text',text:JSON.stringify({ok:false,error:e.message})}]}}})}
tool('keycloak.user.search','Search/list realm users. READ.', 'READ',{search:z.string().max(255).optional(),first:z.number().int().min(0).default(0),max:z.number().int().min(1).max(100).default(25)},a=>client.request(`/users?${new URLSearchParams({first:String(a.first),max:String(a.max),...(a.search?{search:a.search}:{})})}`));
tool('keycloak.user.get','Get a user by id. READ.','READ',{id},a=>client.request(`/users/${encodeURIComponent(a.id)}`));
tool('keycloak.user.create','Create a realm user. WRITE; explicit approval required.','WRITE',{username:z.string().min(1).max(255),email:z.string().email().optional(),firstName:z.string().max(255).optional(),lastName:z.string().max(255).optional(),enabled:z.boolean().default(true),approved},a=>client.request('/users',{method:'POST',body:JSON.stringify({username:a.username,email:a.email,firstName:a.firstName,lastName:a.lastName,enabled:a.enabled})}));
tool('keycloak.user.update','Update bounded user profile fields. WRITE; explicit approval required.','WRITE',{id,email:z.string().email().optional(),firstName:z.string().max(255).optional(),lastName:z.string().max(255).optional(),approved},a=>client.request(`/users/${encodeURIComponent(a.id)}`,{method:'PUT',body:JSON.stringify({email:a.email,firstName:a.firstName,lastName:a.lastName})}));
tool('keycloak.user.disable','Disable user sign-in. HIGH_RISK; explicit approval required.','HIGH_RISK',{id,approved},a=>client.request(`/users/${encodeURIComponent(a.id)}`,{method:'PUT',body:JSON.stringify({enabled:false})}));
tool('keycloak.user.delete','Permanently delete a user. DESTRUCTIVE; disabled by default.','DESTRUCTIVE',{id,approved},a=>client.request(`/users/${encodeURIComponent(a.id)}`,{method:'DELETE'}));
tool('keycloak.group.list','List/search realm groups. READ.','READ',{search:z.string().max(255).optional(),first:z.number().int().min(0).default(0),max:z.number().int().min(1).max(100).default(25)},a=>client.request(`/groups?${new URLSearchParams({first:String(a.first),max:String(a.max),...(a.search?{search:a.search}:{})})}`));
tool('keycloak.group.get','Get group metadata. READ.','READ',{id},a=>client.request(`/groups/${encodeURIComponent(a.id)}`));
tool('keycloak.group.create','Create top-level realm group. WRITE; approval required.','WRITE',{name:z.string().min(1).max(255),approved},a=>client.request('/groups',{method:'POST',body:JSON.stringify({name:a.name})}));
tool('keycloak.group.member.add','Add user to group; may change effective access. HIGH_RISK.','HIGH_RISK',{groupId:id,userId:id,approved},a=>client.request(`/users/${encodeURIComponent(a.userId)}/groups/${encodeURIComponent(a.groupId)}`,{method:'PUT'}));
tool('keycloak.group.member.remove','Remove user from group; may revoke access. HIGH_RISK.','HIGH_RISK',{groupId:id,userId:id,approved},a=>client.request(`/users/${encodeURIComponent(a.userId)}/groups/${encodeURIComponent(a.groupId)}`,{method:'DELETE'}));
tool('keycloak.client.list','List/search clients. READ.','READ',{clientId:z.string().max(255).optional(),first:z.number().int().min(0).default(0),max:z.number().int().min(1).max(100).default(25)},a=>client.request(`/clients?${new URLSearchParams({first:String(a.first),max:String(a.max),...(a.clientId?{clientId:a.clientId}:{})})}`));
tool('keycloak.client.get','Get client metadata by internal UUID. READ.','READ',{id},a=>client.request(`/clients/${encodeURIComponent(a.id)}`));
await server.connect(new StdioServerTransport());
