import test from 'node:test';import assert from 'node:assert/strict';import {FactorialClient,assertApproved,FactorialError} from '../src/client.js';import {byName,tools} from '../src/tools.js';
test('registers ten scoped tools and no arbitrary HTTP escape hatch',()=>{assert.equal(tools.length,10);assert.ok(tools.every(t=>t.name.startsWith('factorial.')));assert.ok(!tools.some(t=>/request|http|execute_any/.test(t.name)))});
test('strict date validation rejects ambiguous leave date',()=>{const t=byName.get('factorial.timeoff.leave.create')!;assert.equal(t.schema.safeParse({employee_id:1,start_on:'tomorrow'}).success,false)});
test('write requires approval by default',()=>assert.throws(()=>assertApproved(false,{FACTORIAL_REQUIRE_WRITE_APPROVAL:'true'} as any),/approval/i));
test('OAuth token is isolated and sent as bearer',async()=>{let auth='';const f=(async(_u:any,i:any)=>{auth=i.headers.authorization;return new Response(JSON.stringify({data:[]}),{status:200,headers:{'content-type':'application/json'}})}) as typeof fetch;const c=new FactorialClient({FACTORIAL_TOKEN:'secret',FACTORIAL_TIMEOUT_MS:'1000'} as any,f);await c.request('employees/employees');assert.equal(auth,'Bearer secret')});
test('API key uses x-api-key, not bearer',async()=>{let h:any;const f=(async(_u:any,i:any)=>{h=i.headers;return new Response('{}',{status:200})}) as typeof fetch;await new FactorialClient({FACTORIAL_API_KEY:'key'} as any,f).request('employees/employees');assert.equal(h['x-api-key'],'key');assert.equal(h.authorization,undefined)});
test('429 preserves retry-after and bounded retry',async()=>{let n=0;const f=(async()=>{n++;return new Response(JSON.stringify({message:'slow'}),{status:429,headers:{'retry-after':'0'}})}) as typeof fetch;await assert.rejects(()=>new FactorialClient({FACTORIAL_TOKEN:'x'} as any,f).request('employees/employees'),FactorialError);assert.equal(n,3)});
test('401 is not retried',async()=>{let n=0;const f=(async()=>{n++;return new Response(JSON.stringify({message:'bad token'}),{status:401})}) as typeof fetch;await assert.rejects(()=>new FactorialClient({FACTORIAL_TOKEN:'x'} as any,f).request('employees/employees'));assert.equal(n,1)});
test('write operation is never retried blindly',async()=>{let n=0;const f=(async()=>{n++;return new Response('{}',{status:503})}) as typeof fetch;const c=new FactorialClient({FACTORIAL_TOKEN:'x'} as any,f);await assert.rejects(()=>c.request('timeoff/leaves',{method:'POST',body:{},retry:false}));assert.equal(n,1)});
