import test from "node:test"; import assert from "node:assert/strict";
import { ToolRouter, tools } from "../src/tools.js"; import { approve, ApprovalError, flagName, ValidationError } from "../src/security.js";
class Api {calls:any[]=[]; async get(p:string){this.calls.push(["GET",p]);return{data:[]}} async post(p:string,b?:any){this.calls.push(["POST",p,b]);return{ok:true}} async delete(p:string){this.calls.push(["DELETE",p]);return{ok:true}}}
class Mcp {async call(){return{handled:false}}}
test("registers 13 unique scoped tools",()=>{assert.equal(tools.length,13);assert.equal(new Set(tools.map(x=>x.name)).size,13);assert.ok(tools.every(x=>x.name.startsWith("unleash.")));});
test("validates feature names",()=>{assert.equal(flagName("checkout.v2"),"checkout.v2");assert.throws(()=>flagName("bad name"),ValidationError);});
test("write approval defaults on",()=>{process.env.UNLEASH_REQUIRE_WRITE_APPROVAL="true";delete process.env.UNLEASH_APPROVAL_TOKEN;assert.throws(()=>approve("WRITE"),ApprovalError);});
test("lists flags with bounded pagination",async()=>{const api=new Api();const r=new ToolRouter(api as any,new Mcp() as any);await r.execute("unleash.flag.list",{projectId:"default",page:2,limit:25});assert.match(api.calls[0][1],/page=2/);assert.match(api.calls[0][1],/limit=25/);});
test("creates disabled-by-default flag through Admin API fallback",async()=>{process.env.UNLEASH_REQUIRE_WRITE_APPROVAL="false";const api=new Api();const r=new ToolRouter(api as any,new Mcp() as any);await r.execute("unleash.flag.create",{projectId:"default",featureName:"new-checkout",type:"release"});assert.equal(api.calls[0][0],"POST");assert.deepEqual(api.calls[0][2],{name:"new-checkout",type:"release"});});
test("environment toggle requires explicit high-risk approval",async()=>{delete process.env.UNLEASH_APPROVAL_TOKEN;const r=new ToolRouter(new Api() as any,new Mcp() as any);await assert.rejects(()=>r.execute("unleash.flag.environment.enable",{projectId:"default",featureName:"x",environment:"production"}),ApprovalError);});
test("destructive delete disabled by default",async()=>{process.env.UNLEASH_ENABLE_DESTRUCTIVE="false";process.env.UNLEASH_APPROVAL_TOKEN="grant";const r=new ToolRouter(new Api() as any,new Mcp() as any);await assert.rejects(()=>r.execute("unleash.flag.delete",{projectId:"default",features:["x"],approvalId:"grant"}),ApprovalError);});
test("archive validation is a non-mutating prepare step",async()=>{const api=new Api();const r=new ToolRouter(api as any,new Mcp() as any);await r.execute("unleash.flag.archive.validate",{projectId:"default",features:["x"]});assert.equal(api.calls[0][1],"/projects/default/archive/validate");});
