const STR={type:"string",minLength:1,maxLength:500}; const RUN={type:"string",minLength:1,maxLength:100}; const APPROVAL={type:"string",minLength:64,maxLength:64,pattern:"^[a-f0-9]{64}$"};
export const TOOL_DEFINITIONS=[
{name:"temporal.workflow.list",description:"List Workflow Executions. Risk: READ.",inputSchema:{type:"object",additionalProperties:false,properties:{query:{type:"string",maxLength:5000},pageSize:{type:"integer",minimum:1,maximum:200,default:50},maxResults:{type:"integer",minimum:1,maximum:500,default:100}}}},
{name:"temporal.workflow.describe",description:"Describe one Workflow Execution. Risk: READ.",inputSchema:{type:"object",additionalProperties:false,required:["workflowId"],properties:{workflowId:STR,runId:RUN}}},
{name:"temporal.workflow.start",description:"Start a Workflow Execution. Risk: HIGH_RISK. Approval required.",inputSchema:{type:"object",additionalProperties:false,required:["workflowType","taskQueue","workflowId","approval_token"],properties:{workflowType:STR,taskQueue:STR,workflowId:STR,args:{type:"array",maxItems:50,items:{}},memo:{type:"object",maxProperties:50,additionalProperties:true},searchAttributes:{type:"object",maxProperties:50,additionalProperties:true},approval_token:APPROVAL}}},
{name:"temporal.workflow.signal",description:"Signal a Workflow. Risk: HIGH_RISK. Approval required.",inputSchema:{type:"object",additionalProperties:false,required:["workflowId","signalName","approval_token"],properties:{workflowId:STR,runId:RUN,signalName:STR,args:{type:"array",maxItems:50,items:{}},approval_token:APPROVAL}}},
{name:"temporal.workflow.query",description:"Run a read-only Workflow Query. Risk: READ.",inputSchema:{type:"object",additionalProperties:false,required:["workflowId","queryName"],properties:{workflowId:STR,runId:RUN,queryName:STR,args:{type:"array",maxItems:50,items:{}}}}},
{name:"temporal.workflow.cancel",description:"Request Workflow cancellation. Risk: DESTRUCTIVE.",inputSchema:{type:"object",additionalProperties:false,required:["workflowId","approval_token"],properties:{workflowId:STR,runId:RUN,approval_token:APPROVAL}}},
{name:"temporal.workflow.terminate",description:"Force terminate a Workflow. Risk: DESTRUCTIVE.",inputSchema:{type:"object",additionalProperties:false,required:["workflowId","reason","approval_token"],properties:{workflowId:STR,runId:RUN,reason:{type:"string",minLength:1,maxLength:1000},details:{type:"array",maxItems:20,items:{}},approval_token:APPROVAL}}},
{name:"temporal.schedule.list",description:"List Schedules. Risk: READ.",inputSchema:{type:"object",additionalProperties:false,properties:{pageSize:{type:"integer",minimum:1,maximum:200,default:50},maxResults:{type:"integer",minimum:1,maximum:500,default:100}}}},
{name:"temporal.schedule.describe",description:"Describe a Schedule. Risk: READ.",inputSchema:{type:"object",additionalProperties:false,required:["scheduleId"],properties:{scheduleId:STR}}},
{name:"temporal.schedule.pause",description:"Pause a Schedule. Risk: HIGH_RISK.",inputSchema:{type:"object",additionalProperties:false,required:["scheduleId","approval_token"],properties:{scheduleId:STR,note:{type:"string",maxLength:1000},approval_token:APPROVAL}}},
{name:"temporal.schedule.unpause",description:"Unpause a Schedule. Risk: HIGH_RISK.",inputSchema:{type:"object",additionalProperties:false,required:["scheduleId","approval_token"],properties:{scheduleId:STR,note:{type:"string",maxLength:1000},approval_token:APPROVAL}}},
{name:"temporal.schedule.delete",description:"Delete a Schedule. Risk: DESTRUCTIVE.",inputSchema:{type:"object",additionalProperties:false,required:["scheduleId","approval_token"],properties:{scheduleId:STR,approval_token:APPROVAL}}}
];
export function payloadWithoutApproval(args={}){const {approval_token:_ignored,...payload}=args; return payload;}
