import test from 'node:test';import assert from 'node:assert/strict';import {loadConfig} from '../src/config.js';import {requirePermission,assertRange,assertUuid} from '../src/security.js';import {UmamiClient,UmamiError} from '../src/client.js';
const cfg=()=>loadConfig({UMAMI_API_KEY:'secret',UMAMI_BASE_URL:'https://api.umami.is/v1'} as any);
test('configuration requires credential',()=>assert.throws(()=>loadConfig({} as any),/UMAMI_API_KEY/));
test('validation rejects bad identifiers and ranges',()=>{assert.throws(()=>assertUuid('x'));assert.throws(()=>assertRange(2,1))});
test('writes require both configuration and approval',()=>{assert.throws(()=>requirePermission(cfg(),'WRITE',true),/disabled/);const c={...cfg(),allowWrites:true};assert.throws(()=>requirePermission(c,'WRITE',false),/approval/)});
test('destructive additionally requires destructive gate',()=>{const c={...cfg(),allowWrites:true};assert.throws(()=>requirePermission(c,'DESTRUCTIVE',true),/DESTRUCTIVE/)});
test('client authenticates and returns read data',async()=>{let auth='';const f=async(_u:any,i:any)=>{auth=i.headers.Authorization;return new Response(JSON.stringify({data:[{id:'1'}]}),{status:200,headers:{'content-type':'application/json'}})};const c=new UmamiClient(cfg(),f as any);const r=await c.listWebsites();assert.equal(auth,'Bearer secret');assert.equal(r.data.length,1)});
test('rate limit preserves retry-after after bounded retries',async()=>{let n=0;const f=async()=>{n++;return new Response(JSON.stringify({message:'slow'}),{status:429,headers:{'retry-after':'0'}})};const c=new UmamiClient(cfg(),f as any);await assert.rejects(()=>c.listWebsites(),(e:any)=>e instanceof UmamiError&&e.code==='RATE_LIMIT');assert.equal(n,3)});
test('non-idempotent write is never retried',async()=>{let n=0;const f=async()=>{n++;return new Response(JSON.stringify({message:'fail'}),{status:500})};const c=new UmamiClient(cfg(),f as any);await assert.rejects(()=>c.createWebsite('x','example.com'));assert.equal(n,1)});
