import test from "node:test";import assert from "node:assert/strict";import {loadConfig} from "../src/config.js";import {assertAllowed,fingerprint} from "../src/policy.js";import {DocusignClient} from "../src/client.js";import {TOOLS} from "../src/tools.js";
const env={DOCUSIGN_ACCESS_TOKEN:"tok",DOCUSIGN_ACCOUNT_ID:"a",DOCUSIGN_BASE_URL:"https://demo.docusign.net/restapi",DOCUSIGN_MAX_RETRIES:"1"} as NodeJS.ProcessEnv;
test("safe config",()=>{const c=loadConfig(env);assert.equal(c.requireWriteApproval,true);assert.equal(c.allowDestructive,false);});
test("rejects SSRF host",()=>assert.throws(()=>loadConfig({...env,DOCUSIGN_BASE_URL:"https://evil.example"}),/official Docusign/));
test("high risk requires exact approval",()=>{const fp=fingerprint("docusign.envelope.send",{envelopeId:"e1"});assert.throws(()=>assertAllowed("HIGH_RISK","docusign.envelope.send",{envelopeId:"e1"},{requireWriteApproval:true,allowDestructive:false,approvedActions:new Set()}));assert.doesNotThrow(()=>assertAllowed("HIGH_RISK","docusign.envelope.send",{envelopeId:"e1"},{requireWriteApproval:true,allowDestructive:false,approvedActions:new Set([fp])}));});
test("destructive disabled",()=>assert.throws(()=>assertAllowed("DESTRUCTIVE","docusign.envelope.void",{envelopeId:"e1"},{requireWriteApproval:true,allowDestructive:false,approvedActions:new Set(["docusign.envelope.void:e1"])}),/disabled/));
test("GET retries 429 and sends bearer",async()=>{const c=loadConfig(env);let n=0,auth="";const f=async(_u:any,i:any)=>{n++;auth=i.headers.Authorization;return n===1?new Response("busy",{status:429,headers:{"retry-after":"0"}}):new Response("{}",{status:200});};await new DocusignClient(c,f as any).request("GET","/x");assert.equal(n,2);assert.equal(auth,"Bearer tok");});
test("write is not retried",async()=>{const c=loadConfig(env);let n=0;const f=async()=>{n++;return new Response("fail",{status:500});};await assert.rejects(()=>new DocusignClient(c,f as any).request("POST","/x",{}));assert.equal(n,1);});
test("tool surface bounded and scoped",()=>{assert.ok(TOOLS.length>=8&&TOOLS.length<=20);TOOLS.forEach(t=>assert.match(t.name,/^docusign\./));});
