import test from 'node:test'; import assert from 'node:assert/strict'; import {loadConfig} from '../src/auth.js'; import {authorize,toolPolicy} from '../src/policy.js'; import {KintoneClient,KintoneError} from '../src/client.js';
const cfg=()=>loadConfig({KINTONE_SUBDOMAIN:'acme',KINTONE_API_TOKENS:'secret',KINTONE_REQUIRE_WRITE_APPROVAL:'true',KINTONE_ENABLE_DESTRUCTIVE:'false',KINTONE_MAX_RETRIES:'0'} as any);
test('auth config validates and isolates tokens',()=>{const c=cfg();assert.equal(c.subdomain,'acme');assert.deepEqual(c.apiTokens,['secret']);assert.throws(()=>loadConfig({KINTONE_SUBDOMAIN:'bad/url',KINTONE_API_TOKENS:'x'} as any))});
test('tool registry policy covers expected risk classes',()=>{assert.equal(toolPolicy['kintone.record.get'],'READ');assert.equal(toolPolicy['kintone.comment.add'],'HIGH_RISK');assert.equal(toolPolicy['kintone.records.delete'],'DESTRUCTIVE')});
test('approval and destructive controls',()=>{const c=cfg();assert.doesNotThrow(()=>authorize(c,'READ'));assert.throws(()=>authorize(c,'WRITE'));assert.doesNotThrow(()=>authorize(c,'WRITE',true));assert.throws(()=>authorize(c,'DESTRUCTIVE',true))});
test('read operation sends token internally and maps response',async()=>{let seen='';const f=async(_u:any,i:any)=>{seen=i.headers['X-Cybozu-API-Token'];return new Response(JSON.stringify({record:{Name:{value:'A'}}}),{status:200})};const v:any=await new KintoneClient(cfg(),f as any).getRecord(1,2);assert.equal(seen,'secret');assert.equal(v.record.Name.value,'A')});
test('provider errors are mapped without retrying auth errors',async()=>{const f=async()=>new Response(JSON.stringify({code:'CB_AU01',message:'Authentication failed'}),{status:401});await assert.rejects(()=>new KintoneClient(cfg(),f as any).getApp(1),(e:any)=>e instanceof KintoneError&&e.status===401&&e.code==='CB_AU01')});
test('rate limit preserves retry-after',async()=>{const f=async()=>new Response(JSON.stringify({code:'GAIA_TM01',message:'limited'}),{status:429,headers:{'retry-after':'2'}});await assert.rejects(()=>new KintoneClient(cfg(),f as any).getApp(1),(e:any)=>e.retryAfter===2)});
test('pagination query is bounded by API contract',async()=>{let url='';const f=async(u:any)=>{url=String(u);return new Response(JSON.stringify({records:[]}),{status:200})};await new KintoneClient(cfg(),f as any).listRecords(1,'order by $id asc limit 500',['Name']);assert.match(url,/limit%20500|limit\+500/);assert.match(url,/fields%5B0%5D=Name/)});
