import { z } from "zod";
import type { ToolPolicy } from "./policy.js";

const id = (prefix: string) => z.string().regex(new RegExp(`^${prefix}_[A-Za-z0-9]+$`));
const approval = { approved: z.boolean().optional().describe("Must be true only after human approval when required by policy.") };

export interface Def { name: string; upstream: string; description: string; schema: z.ZodObject<any> | z.ZodEffects<any>; policy: ToolPolicy; }
const R = (permission: ToolPolicy["permission"], risk: ToolPolicy["risk"], approval: ToolPolicy["approval"]): ToolPolicy => ({ permission, risk, approval });

export const TOOLS: Def[] = [
  { name:"front.conversation.search", upstream:"search_conversations", description:"Search Front conversations by text and bounded filters.", policy:R("read","READ","none"), schema:z.object({ query:z.string().max(500).optional(), scope:z.enum(["my_conversations","my_workspace","all_inboxes"]).optional(), filters:z.object({ inboxId:id("inb").optional(), teammateId:id("tea").optional(), teamId:id("tim").optional(), tags:z.array(id("tag")).max(20).optional(), status:z.enum(["open","archived","trashed","spam"]).optional(), after:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), before:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional() }).strict().optional(), cursor:z.string().max(2048).optional() }).strict().refine(v => Boolean(v.query || v.filters), "query or at least one filter is required") },
  { name:"front.conversation.read", upstream:"read_conversation", description:"Read a conversation timeline and metadata.", policy:R("read","READ","none"), schema:z.object({ conversationId:id("cnv"), limit:z.number().int().min(1).max(200).optional(), cursor:z.string().max(2048).optional() }).strict() },
  { name:"front.message.read", upstream:"read_message", description:"Read one Front message with full content and delivery metadata.", policy:R("read","READ","none"), schema:z.object({ messageId:id("msg") }).strict() },
  { name:"front.attachment.get", upstream:"get_attachment", description:"Get attachment metadata and a short-lived download URL.", policy:R("read","READ","none"), schema:z.object({ attachmentId:id("fil") }).strict() },
  { name:"front.tag.list", upstream:"list_tags", description:"List workspace tags.", policy:R("read","READ","none"), schema:z.object({ name_query:z.string().max(200).optional(), limit:z.number().int().min(1).max(100).optional(), offset:z.number().int().min(0).max(100000).optional() }).strict() },
  { name:"front.inbox.list", upstream:"list_inboxes", description:"List inboxes accessible to the authenticated Front identity.", policy:R("read","READ","none"), schema:z.object({ name_query:z.string().max(200).optional(), limit:z.number().int().min(1).max(50).optional(), offset:z.number().int().min(0).max(100000).optional() }).strict() },
  { name:"front.channel.list", upstream:"list_channels", description:"List accessible channels for message routing discovery.", policy:R("read","READ","none"), schema:z.object({ name_query:z.string().max(200).optional(), inbox_ids:z.array(id("inb")).max(20).optional(), types:z.array(z.string().regex(/^[a-z0-9_-]+$/)).max(20).optional(), limit:z.number().int().min(1).max(50).optional(), offset:z.number().int().min(0).max(100000).optional() }).strict() },
  { name:"front.teammate.list", upstream:"list_teammates", description:"List teammates and roles.", policy:R("read","READ","none"), schema:z.object({ name_query:z.string().max(200).optional(), statuses:z.array(z.enum(["active","pending","pending_email","blocked"])).max(4).optional(), limit:z.number().int().min(1).max(25).optional(), offset:z.number().int().min(0).max(100000).optional() }).strict() },
  { name:"front.draft.list", upstream:"list_drafts", description:"List in-flight drafts owned by the authenticated teammate or agent.", policy:R("read","READ","none"), schema:z.object({ limit:z.number().int().min(1).max(200).optional() }).strict() },
  { name:"front.contact.search", upstream:"search_contacts", description:"Search contacts by name, email, or handle.", policy:R("read","READ","none"), schema:z.object({ query:z.string().min(1).max(300), cursor:z.string().max(2048).optional() }).strict() },
  { name:"front.contact.read", upstream:"read_contact", description:"Read a Front contact record.", policy:R("read","READ","none"), schema:z.object({ contactId:id("crd") }).strict() },
  { name:"front.draft.create", upstream:"create_draft", description:"Prepare a draft reply or outbound conversation; never sends it.", policy:R("write","WRITE","configurable"), schema:z.object({ conversationId:id("cnv").optional(), body:z.string().max(100000).optional(), bodyFormat:z.enum(["html","markdown","plain"]).optional(), subject:z.string().max(998).optional(), to:z.array(z.string().email()).max(50).optional(), cc:z.array(z.string().email()).max(50).optional(), bcc:z.array(z.string().email()).max(50).optional(), channelId:id("cha").optional(), takeOver:z.boolean().optional(), ...approval }).strict().refine(v => Boolean(v.conversationId || v.to?.length), "conversationId or at least one recipient is required") },
  { name:"front.comment.add", upstream:"add_comment", description:"Add an internal comment to a conversation; not customer-visible.", policy:R("write","WRITE","configurable"), schema:z.object({ conversationId:id("cnv"), body:z.string().min(1).max(10000), ...approval }).strict() },
  { name:"front.conversation.tag", upstream:"tag_conversation", description:"Add or remove existing tags from a conversation.", policy:R("write","WRITE","configurable"), schema:z.object({ conversationId:id("cnv"), addTags:z.array(id("tag")).max(30).optional(), removeTags:z.array(id("tag")).max(30).optional(), ...approval }).strict().refine(v => Boolean(v.addTags?.length || v.removeTags?.length), "addTags or removeTags must be non-empty") },
  { name:"front.conversation.assign", upstream:"assign_conversation", description:"Assign or unassign a conversation.", policy:R("write","WRITE","configurable"), schema:z.object({ conversationId:id("cnv"), assigneeId:id("tea").nullable(), ...approval }).strict() },
  { name:"front.conversation.status.update", upstream:"update_conversation_status", description:"Archive or reopen a conversation, or set a ticket status.", policy:R("write","HIGH_RISK","explicit"), schema:z.object({ conversationId:id("cnv"), status:z.enum(["open","archived"]).optional(), statusId:id("sts").optional(), ...approval }).strict().refine(v => Number(Boolean(v.status)) + Number(Boolean(v.statusId)) === 1, "provide exactly one of status or statusId") },
  { name:"front.message.send", upstream:"send_message", description:"Send an existing Front draft to external recipients. Disabled by default and always requires explicit approval.", policy:R("send","HIGH_RISK","explicit"), schema:z.object({ draftId:id("msg"), ...approval }).strict() }
];

export const TOOL_MAP = new Map(TOOLS.map(t => [t.name, t]));
export function argsForUpstream(args: Record<string, unknown>): Record<string, unknown> { const { approved: _approved, ...rest } = args; return rest; }
