import { z } from "zod";
import type { Risk } from "./policy.js";
const account=z.string().min(1).max(120).optional(); const approved=z.boolean().optional();
export type ToolDef={name:string;upstream:string;description:string;risk:Risk;schema:z.ZodTypeAny;inputSchema:Record<string,unknown>;retryable:boolean;map:(a:any,defaultAccount?:string)=>Record<string,unknown>};
const j=(props:Record<string,unknown>,required:string[]=[])=>({type:"object",properties:props,required,additionalProperties:false});
const A={account:{type:"string"},approved:{type:"boolean"}};
export const TOOLS:ToolDef[]=[
{name:"workable.account.list",upstream:"get_accounts",description:"List Workable accounts accessible to the authenticated user.",risk:"READ",retryable:true,schema:z.object({}),inputSchema:j({}),map:()=>({})},
{name:"workable.job.list",upstream:"get_jobs",description:"List jobs by state.",risk:"READ",retryable:true,schema:z.object({account,state:z.enum(["published","draft","archived","closed"]).optional(),limit:z.number().int().min(1).max(100).optional()}),inputSchema:j({...A,state:{type:"string",enum:["published","draft","archived","closed"]},limit:{type:"integer",minimum:1,maximum:100}}),map:(a,d)=>({account:a.account||d,state:a.state,limit:a.limit})},
{name:"workable.job.search",upstream:"search_jobs",description:"Search jobs by full or partial title.",risk:"READ",retryable:true,schema:z.object({account,query:z.string().min(1).max(200),state:z.enum(["published","draft","archived","closed"]).optional(),limit:z.number().int().min(1).max(100).optional()}),inputSchema:j({...A,query:{type:"string",minLength:1,maxLength:200},state:{type:"string",enum:["published","draft","archived","closed"]},limit:{type:"integer",minimum:1,maximum:100}},["query"]),map:(a,d)=>({account:a.account||d,query:a.query,state:a.state,limit:a.limit})},
{name:"workable.job.get",upstream:"get_job",description:"Get a job by shortcode.",risk:"READ",retryable:true,schema:z.object({account,shortcode:z.string().min(1).max(80)}),inputSchema:j({...A,shortcode:{type:"string",minLength:1,maxLength:80}},["shortcode"]),map:(a,d)=>({account:a.account||d,shortcode:a.shortcode})},
{name:"workable.job.stages",upstream:"get_job_stages",description:"Get pipeline stages for a job.",risk:"READ",retryable:true,schema:z.object({account,shortcode:z.string().min(1).max(80)}),inputSchema:j({...A,shortcode:{type:"string",minLength:1,maxLength:80}},["shortcode"]),map:(a,d)=>({account:a.account||d,shortcode:a.shortcode})},
{name:"workable.candidate.list",upstream:"get_candidates",description:"List candidates for a job.",risk:"READ",retryable:true,schema:z.object({account,shortcode:z.string().min(1).max(80),stage:z.string().max(120).optional(),email:z.string().email().optional(),limit:z.number().int().min(1).max(100).optional()}),inputSchema:j({...A,shortcode:{type:"string"},stage:{type:"string"},email:{type:"string",format:"email"},limit:{type:"integer",minimum:1,maximum:100}},["shortcode"]),map:(a,d)=>({account:a.account||d,shortcode:a.shortcode,stage:a.stage,email:a.email,limit:a.limit})},
{name:"workable.candidate.get",upstream:"get_candidate",description:"Get a candidate profile.",risk:"READ",retryable:true,schema:z.object({account,candidateId:z.string().min(1).max(120)}),inputSchema:j({...A,candidateId:{type:"string"}},["candidateId"]),map:(a,d)=>({account:a.account||d,candidate_id:a.candidateId})},
{name:"workable.candidate.create",upstream:"create_candidate",description:"Source a candidate into a job. Requires write approval.",risk:"WRITE",retryable:false,schema:z.object({account,approved,shortcode:z.string().min(1).max(80),firstname:z.string().min(1).max(120),lastname:z.string().min(1).max(120),email:z.string().email().optional(),headline:z.string().max(300).optional()}),inputSchema:j({...A,shortcode:{type:"string"},firstname:{type:"string"},lastname:{type:"string"},email:{type:"string",format:"email"},headline:{type:"string"}},["shortcode","firstname","lastname"]),map:(a,d)=>({account:a.account||d,shortcode:a.shortcode,firstname:a.firstname,lastname:a.lastname,email:a.email,headline:a.headline})},
{name:"workable.candidate.update",upstream:"update_candidate",description:"Partially update candidate profile fields. Requires write approval.",risk:"WRITE",retryable:false,schema:z.object({account,approved,candidateId:z.string().min(1),firstname:z.string().max(120).optional(),lastname:z.string().max(120).optional(),email:z.string().email().optional(),phone:z.string().max(80).optional(),headline:z.string().max(300).optional(),summary:z.string().max(5000).optional()}).refine(x=>[x.firstname,x.lastname,x.email,x.phone,x.headline,x.summary].some(v=>v!==undefined),"Provide at least one field to update."),inputSchema:j({...A,candidateId:{type:"string"},firstname:{type:"string"},lastname:{type:"string"},email:{type:"string",format:"email"},phone:{type:"string"},headline:{type:"string"},summary:{type:"string"}},["candidateId"]),map:(a,d)=>({account:a.account||d,candidate_id:a.candidateId,firstname:a.firstname,lastname:a.lastname,email:a.email,phone:a.phone,headline:a.headline,summary:a.summary})},
{name:"workable.candidate.move",upstream:"move_candidate",description:"Move a candidate to another pipeline stage. Explicit approval required.",risk:"HIGH_RISK",retryable:false,schema:z.object({account,approved,candidateId:z.string().min(1),stageId:z.string().min(1),requisitionCode:z.string().optional()}),inputSchema:j({...A,candidateId:{type:"string"},stageId:{type:"string"},requisitionCode:{type:"string"}},["candidateId","stageId"]),map:(a,d)=>({account:a.account||d,candidate_id:a.candidateId,stage_id:a.stageId,requisition_code:a.requisitionCode})},
{name:"workable.candidate.comment",upstream:"add_comment",description:"Add a comment to a candidate. Requires write approval.",risk:"WRITE",retryable:false,schema:z.object({account,approved,candidateId:z.string().min(1),body:z.string().min(1).max(10000),visibility:z.enum(["members","private"]).optional()}),inputSchema:j({...A,candidateId:{type:"string"},body:{type:"string",minLength:1,maxLength:10000},visibility:{type:"string",enum:["members","private"]}},["candidateId","body"]),map:(a,d)=>({account:a.account||d,candidate_id:a.candidateId,body:a.body,visibility:a.visibility})},
{name:"workable.requisition.list",upstream:"get_requisitions",description:"List requisitions.",risk:"READ",retryable:true,schema:z.object({account,state:z.string().max(80).optional(),limit:z.number().int().min(1).max(100).optional()}),inputSchema:j({...A,state:{type:"string"},limit:{type:"integer",minimum:1,maximum:100}}),map:(a,d)=>({account:a.account||d,state:a.state,limit:a.limit})},
{name:"workable.timeoff.list",upstream:"get_timeoff_requests",description:"List time-off requests in a date range.",risk:"READ",retryable:true,schema:z.object({account,startDate:z.string().min(10).max(40),endDate:z.string().min(10).max(40),employeeId:z.string().optional(),state:z.string().optional()}),inputSchema:j({...A,startDate:{type:"string"},endDate:{type:"string"},employeeId:{type:"string"},state:{type:"string"}},["startDate","endDate"]),map:(a,d)=>({account:a.account||d,start_date:a.startDate,end_date:a.endDate,employee_id:a.employeeId,state:a.state})}
];
export const TOOL_MAP=new Map(TOOLS.map(t=>[t.name,t]));
