import { z } from "zod";
import type { Risk } from "./policy.js";
const approval=z.boolean().optional().describe("Set true only after human approval when write approval is required.");
const id=z.number().int().positive();
export type ToolDef={name:string;description:string;risk:Risk;schema:z.ZodTypeAny;inputSchema:Record<string,unknown>};
const defs:[string,string,Risk,z.ZodTypeAny,Record<string,unknown>][]=[
["shortcut.story.search","Search Shortcut stories with Shortcut search syntax.","READ",z.object({query:z.string().min(1).max(1000),pageSize:z.number().int().min(1).max(250).optional(),detail:z.enum(["full","slim"]).optional(),next:z.string().max(4096).optional()}).strict(),{type:"object",properties:{query:{type:"string"},pageSize:{type:"integer",minimum:1,maximum:250},detail:{enum:["full","slim"]},next:{type:"string"}},required:["query"],additionalProperties:false}],
["shortcut.story.get","Get one story by numeric Shortcut story ID.","READ",z.object({storyId:id}).strict(),{type:"object",properties:{storyId:{type:"integer",minimum:1}},required:["storyId"],additionalProperties:false}],
["shortcut.story.create","Create a Shortcut story.","WRITE",z.object({name:z.string().min(1).max(512),storyType:z.enum(["feature","bug","chore"]),workflowStateId:id,description:z.string().max(100000).optional(),epicId:id.optional(),iterationId:id.optional(),groupId:z.string().uuid().optional(),ownerIds:z.array(z.string().uuid()).max(50).optional(),estimate:z.number().nonnegative().optional(),approved:approval}).strict(),{type:"object",properties:{name:{type:"string"},storyType:{enum:["feature","bug","chore"]},workflowStateId:{type:"integer",minimum:1},description:{type:"string"},epicId:{type:"integer",minimum:1},iterationId:{type:"integer",minimum:1},groupId:{type:"string",format:"uuid"},ownerIds:{type:"array",items:{type:"string",format:"uuid"}},estimate:{type:"number",minimum:0},approved:{type:"boolean"}},required:["name","storyType","workflowStateId"],additionalProperties:false}],
["shortcut.story.update","Update selected fields on an existing story.","WRITE",z.object({storyId:id,name:z.string().min(1).max(512).optional(),description:z.string().max(100000).optional(),workflowStateId:id.optional(),storyType:z.enum(["feature","bug","chore"]).optional(),epicId:id.nullable().optional(),iterationId:id.nullable().optional(),estimate:z.number().nonnegative().nullable().optional(),approved:approval}).strict().refine(v=>Object.keys(v).some(k=>!["storyId","approved"].includes(k)),"At least one update field is required."),{type:"object",properties:{storyId:{type:"integer",minimum:1},name:{type:"string"},description:{type:"string"},workflowStateId:{type:"integer",minimum:1},storyType:{enum:["feature","bug","chore"]},epicId:{type:["integer","null"]},iterationId:{type:["integer","null"]},estimate:{type:["number","null"]},approved:{type:"boolean"}},required:["storyId"],additionalProperties:false}],
["shortcut.story.comment.create","Add an internal comment to a story.","WRITE",z.object({storyId:id,text:z.string().min(1).max(100000),approved:approval}).strict(),{type:"object",properties:{storyId:{type:"integer",minimum:1},text:{type:"string"},approved:{type:"boolean"}},required:["storyId","text"],additionalProperties:false}],
["shortcut.epic.list","List epics visible to the authenticated user.","READ",z.object({}).strict(),{type:"object",properties:{},additionalProperties:false}],
["shortcut.epic.get","Get one epic by ID.","READ",z.object({epicId:id}).strict(),{type:"object",properties:{epicId:{type:"integer",minimum:1}},required:["epicId"],additionalProperties:false}],
["shortcut.epic.create","Create an epic.","WRITE",z.object({name:z.string().min(1).max(256),description:z.string().max(100000).optional(),objectiveId:id.optional(),groupId:z.string().uuid().optional(),approved:approval}).strict(),{type:"object",properties:{name:{type:"string"},description:{type:"string"},objectiveId:{type:"integer",minimum:1},groupId:{type:"string",format:"uuid"},approved:{type:"boolean"}},required:["name"],additionalProperties:false}],
["shortcut.iteration.list","List iterations.","READ",z.object({}).strict(),{type:"object",properties:{},additionalProperties:false}],
["shortcut.objective.list","List objectives.","READ",z.object({}).strict(),{type:"object",properties:{},additionalProperties:false}],
["shortcut.team.list","List Shortcut teams (API groups).","READ",z.object({}).strict(),{type:"object",properties:{},additionalProperties:false}],
["shortcut.workflow.list","List workflows and workflow states.","READ",z.object({}).strict(),{type:"object",properties:{},additionalProperties:false}]
];
export const TOOLS:ToolDef[]=defs.map(([name,description,risk,schema,inputSchema])=>({name,description,risk,schema,inputSchema}));
export const TOOL_MAP=new Map(TOOLS.map(t=>[t.name,t]));
