import {z} from "zod";import {BunnyClient} from "./client.js";import {authorize,Risk} from "./security.js";
const id=z.number().int().positive();const approval=z.boolean().optional();
export type Def={name:string;description:string;risk:Risk;schema:z.ZodTypeAny;run:(a:any,c:BunnyClient)=>Promise<unknown>};
const q=(o:Record<string,unknown>)=>{const p=new URLSearchParams();for(const[k,v]of Object.entries(o))if(v!==undefined)p.set(k,String(v));return p.toString()};
export const tools:Def[]=[
{name:"bunny.pullzone.list",description:"List CDN pull zones.",risk:"READ",schema:z.object({page:z.number().int().min(1).max(1000).default(1),perPage:z.number().int().min(1).max(1000).default(100)}).strict(),run:(a,c)=>c.request("GET",`/pullzone?page=${a.page}&perPage=${a.perPage}`)},
{name:"bunny.pullzone.get",description:"Get a CDN pull zone.",risk:"READ",schema:z.object({id}).strict(),run:(a,c)=>c.request("GET",`/pullzone/${a.id}`)},
{name:"bunny.pullzone.create",description:"Create a CDN pull zone.",risk:"WRITE",schema:z.object({name:z.string().min(1).max(100),originUrl:z.string().url(),approved:approval}).strict(),run:(a,c)=>{authorize("WRITE",a.approved);return c.request("POST","/pullzone",{Name:a.name,OriginUrl:a.originUrl},false)}},
{name:"bunny.pullzone.update",description:"Update selected pull-zone settings.",risk:"WRITE",schema:z.object({id,name:z.string().min(1).max(100).optional(),originUrl:z.string().url().optional(),enabled:z.boolean().optional(),approved:approval}).strict().refine(x=>x.name!==undefined||x.originUrl!==undefined||x.enabled!==undefined),run:(a,c)=>{authorize("WRITE",a.approved);return c.request("POST",`/pullzone/${a.id}`,{...(a.name!==undefined?{Name:a.name}:{}),...(a.originUrl!==undefined?{OriginUrl:a.originUrl}:{}),...(a.enabled!==undefined?{Enabled:a.enabled}:{})},false)}},
{name:"bunny.pullzone.delete",description:"Delete a CDN pull zone.",risk:"DESTRUCTIVE",schema:z.object({id,approved:approval}).strict(),run:(a,c)=>{authorize("DESTRUCTIVE",a.approved);return c.request("DELETE",`/pullzone/${a.id}`,undefined,false)}},
{name:"bunny.cache.purge_url",description:"Purge a specific cached URL.",risk:"HIGH_RISK",schema:z.object({url:z.string().url(),async:z.boolean().default(true),approved:approval}).strict(),run:(a,c)=>{authorize("HIGH_RISK",a.approved);return c.request("POST",`/purge?${q({url:a.url,async:a.async})}`,undefined,false)}},
{name:"bunny.cache.purge_zone",description:"Purge all cached content in a pull zone.",risk:"HIGH_RISK",schema:z.object({id,approved:approval}).strict(),run:(a,c)=>{authorize("HIGH_RISK",a.approved);return c.request("POST",`/pullzone/${a.id}/purgeCache`,undefined,false)}},
{name:"bunny.dnszone.list",description:"List DNS zones.",risk:"READ",schema:z.object({page:z.number().int().min(1).default(1),perPage:z.number().int().min(1).max(1000).default(100)}).strict(),run:(a,c)=>c.request("GET",`/dnszone?page=${a.page}&perPage=${a.perPage}`)},
{name:"bunny.dnszone.get",description:"Get a DNS zone and records.",risk:"READ",schema:z.object({id}).strict(),run:(a,c)=>c.request("GET",`/dnszone/${a.id}`)},
{name:"bunny.statistics.get",description:"Get account traffic statistics for an optional UTC time range.",risk:"READ",schema:z.object({dateFrom:z.string().datetime().optional(),dateTo:z.string().datetime().optional(),pullZone:z.number().int().positive().optional(),hourly:z.boolean().default(false)}).strict(),run:(a,c)=>c.request("GET",`/statistics?${q({dateFrom:a.dateFrom,dateTo:a.dateTo,pullZone:a.pullZone,hourly:a.hourly})}`)}];
export async function execute(name:string,input:unknown,client=new BunnyClient()){const t=tools.find(x=>x.name===name);if(!t)throw new Error("Unknown tool");const a=t.schema.parse(input);return t.run(a,client);}