const str={type:'string',minLength:1,maxLength:500},uid={type:'string',minLength:1,maxLength:300},approval={type:'string',pattern:'^[a-f0-9]{64}$'};const write=(name,description,required,properties)=>({name,description,inputSchema:{type:'object',additionalProperties:false,required:[...required,'approval_token'],properties:{...properties,approval_token:approval}}});
export const TOOLS=[
{name:'cal.event_type.list',description:'List Cal.com event types. READ.',inputSchema:{type:'object',additionalProperties:false,properties:{username:str,eventSlug:str,usernames:str,orgSlug:str,orgId:{type:'integer',minimum:1},sortCreatedAt:{enum:['asc','desc']}}}},
{name:'cal.event_type.get',description:'Get an authorized event type by ID. READ.',inputSchema:{type:'object',additionalProperties:false,required:['eventTypeId'],properties:{eventTypeId:{type:'integer',minimum:1}}}},
{name:'cal.availability.slots',description:'Find available slots for an event type. READ.',inputSchema:{type:'object',additionalProperties:false,required:['start','end'],properties:{start:str,end:str,eventTypeId:{type:'integer',minimum:1},eventTypeSlug:str,username:str,teamSlug:str,organizationSlug:str,timeZone:str,duration:{type:'integer',minimum:1,maximum:1440}}}},
{name:'cal.booking.list',description:'List bookings visible to the authenticated identity. READ.',inputSchema:{type:'object',additionalProperties:false,properties:{status:{type:'string',maxLength:50},attendeeEmail:{type:'string',format:'email'},attendeeName:str,eventTypeId:{type:'integer',minimum:1},afterStart:str,beforeEnd:str,take:{type:'integer',minimum:1,maximum:100},skip:{type:'integer',minimum:0}}}},
{name:'cal.booking.get',description:'Get a booking by UID. READ.',inputSchema:{type:'object',additionalProperties:false,required:['bookingUid'],properties:{bookingUid:uid}}},
{name:'cal.booking.references',description:'Get external calendar/video references for a booking. READ.',inputSchema:{type:'object',additionalProperties:false,required:['bookingUid'],properties:{bookingUid:uid,type:{enum:['google_calendar','office365_calendar','daily_video','google_video','office365_video','zoom_video']}}}},
write('cal.booking.create','Create a booking and send provider notifications. WRITE; approval required.',['start','attendee'],{start:str,attendee:{type:'object',additionalProperties:false,required:['name','email','timeZone'],properties:{name:str,email:{type:'string',format:'email'},timeZone:str,phoneNumber:str,language:str}},eventTypeId:{type:'integer',minimum:1},eventTypeSlug:str,username:str,teamSlug:str,organizationSlug:str,guests:{type:'array',maxItems:20,items:{type:'string',format:'email'}},bookingFieldsResponses:{type:'object',maxProperties:50,additionalProperties:true},metadata:{type:'object',maxProperties:50,additionalProperties:{type:'string',maxLength:500}},lengthInMinutes:{type:'integer',minimum:1,maximum:1440}}),
write('cal.booking.reschedule','Reschedule a booking. WRITE; approval required.',['bookingUid','start'],{bookingUid:uid,start:str,reschedulingReason:{type:'string',maxLength:1000}}),
write('cal.booking.request_reschedule','Cancel current booking and ask attendee to choose a new time. WRITE; approval required.',['bookingUid'],{bookingUid:uid,rescheduleReason:{type:'string',maxLength:1000}}),
write('cal.booking.confirm','Confirm a pending booking. WRITE; approval required.',['bookingUid'],{bookingUid:uid}),
write('cal.booking.decline','Decline a pending booking. WRITE; approval required.',['bookingUid'],{bookingUid:uid,reason:{type:'string',maxLength:1000}}),
write('cal.booking.cancel','Cancel a booking and trigger cancellation notifications. DESTRUCTIVE; disabled by default and approval required.',['bookingUid'],{bookingUid:uid,cancellationReason:{type:'string',maxLength:1000},seatUid:uid})];
export function stripApproval(a={}){const{approval_token:_x,...p}=a;return p}
