import {z} from "zod";import {RetoolClient} from "./client.js";
export type Risk="READ"|"WRITE"|"HIGH_RISK"|"DESTRUCTIVE";export type ToolDef={name:string;purpose:string;risk:Risk;approval:boolean;schema:z.ZodTypeAny;run:(a:any,c:RetoolClient)=>Promise<unknown>};
const id=z.string().min(1).max(200).regex(/^[A-Za-z0-9_-]+$/);const page=z.object({page:z.number().int().min(1).max(10000).default(1),pageSize:z.number().int().min(1).max(100).default(50)}).strict();const list=(resource:string)=>(a:any,c:RetoolClient)=>c.get(`/${resource}?page=${a.page}&pageSize=${a.pageSize}`);const get=(resource:string)=>(a:any,c:RetoolClient)=>c.get(`/${resource}/${encodeURIComponent(a.id)}`);
export const tools:ToolDef[]=[
{name:"retool.app.list",purpose:"List Retool apps visible to the token.",risk:"READ",approval:false,schema:page,run:list("apps")},{name:"retool.app.get",purpose:"Get one Retool app by ID.",risk:"READ",approval:false,schema:z.object({id}).strict(),run:get("apps")},
{name:"retool.workflow.list",purpose:"List Retool workflows visible to the token.",risk:"READ",approval:false,schema:page,run:list("workflows")},{name:"retool.workflow.get",purpose:"Get one Retool workflow by ID.",risk:"READ",approval:false,schema:z.object({id}).strict(),run:get("workflows")},
{name:"retool.folder.list",purpose:"List Retool folders visible to the token.",risk:"READ",approval:false,schema:page,run:list("folders")},{name:"retool.folder.get",purpose:"Get one Retool folder by ID.",risk:"READ",approval:false,schema:z.object({id}).strict(),run:get("folders")},
{name:"retool.group.list",purpose:"List Retool groups visible to the token.",risk:"READ",approval:false,schema:page,run:list("groups")},{name:"retool.group.get",purpose:"Get one Retool group by ID.",risk:"READ",approval:false,schema:z.object({id}).strict(),run:get("groups")},
{name:"retool.resource.list",purpose:"List Retool resources visible to the token.",risk:"READ",approval:false,schema:page,run:list("resources")},{name:"retool.resource.get",purpose:"Get one Retool resource by ID.",risk:"READ",approval:false,schema:z.object({id}).strict(),run:get("resources")}];
export async function execute(name:string,input:unknown,client=new RetoolClient()){const tool=tools.find(t=>t.name===name);if(!tool)throw new Error("Unknown tool");return tool.run(tool.schema.parse(input),client);}
