import type {Config} from './config.js';import {CredentialProvider} from './auth.js';
export class ZitadelError extends Error{constructor(public status:number,public retryAfter?:string,public body?:unknown){super(`ZITADEL_${status}`)}}
export class ZitadelClient{private auth:CredentialProvider;constructor(private c:Config,private fetcher:typeof fetch=fetch){this.auth=new CredentialProvider(c)}
private async request(path:string,init:RequestInit={},attempt=0):Promise<any>{const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),this.c.timeoutMs);try{const token=await this.auth.getToken(ctrl.signal);const r=await this.fetcher(`${this.c.baseUrl}${path}`,{...init,signal:ctrl.signal,headers:{Authorization:`Bearer ${token}`,Accept:'application/json','Content-Type':'application/json',...(init.headers||{})}});if(r.status===429&&attempt<3){const ra=r.headers.get('retry-after');const wait=ra?Math.min(Number(ra)*1000,10000):500*2**attempt;await new Promise(x=>setTimeout(x,Number.isFinite(wait)?wait:1000));return this.request(path,init,attempt+1)}if(!r.ok){let body:unknown;try{body=await r.json()}catch{body=await r.text()}throw new ZitadelError(r.status,r.headers.get('retry-after')||undefined,body)}if(r.status===204)return{ok:true};return r.json()}finally{clearTimeout(timer)}}
listOrganizations(limit=50){return this.request('/v2/organizations/_search',{method:'POST',body:JSON.stringify({query:{limit:String(limit)}})})}
listProjects(limit=50){return this.request('/zitadel.project.v2.ProjectService/ListProjects',{method:'POST',headers:{'Connect-Protocol-Version':'1'},body:JSON.stringify({pagination:{limit}})})}
listUsers(orgId:string,startIndex=1,count=50,filter?:string){const q=new URLSearchParams({startIndex:String(startIndex),count:String(Math.min(count,100))});if(filter)q.set('filter',filter);return this.request(`/scim/v2/${encodeURIComponent(orgId)}/Users?${q}`,{headers:{Accept:'application/scim+json'}})}
getUser(orgId:string,userId:string){return this.request(`/scim/v2/${encodeURIComponent(orgId)}/Users/${encodeURIComponent(userId)}`,{headers:{Accept:'application/scim+json'}})}
createUser(orgId:string,user:any){return this.request(`/scim/v2/${encodeURIComponent(orgId)}/Users`,{method:'POST',headers:{Accept:'application/scim+json','Content-Type':'application/scim+json'},body:JSON.stringify({...user,schemas:['urn:ietf:params:scim:schemas:core:2.0:User']})})}
patchUser(orgId:string,userId:string,operations:any[]){return this.request(`/scim/v2/${encodeURIComponent(orgId)}/Users/${encodeURIComponent(userId)}`,{method:'PATCH',headers:{'Content-Type':'application/scim+json'},body:JSON.stringify({schemas:['urn:ietf:params:scim:api:messages:2.0:PatchOp'],Operations:operations})})}
deleteUser(orgId:string,userId:string){return this.request(`/scim/v2/${encodeURIComponent(orgId)}/Users/${encodeURIComponent(userId)}`,{method:'DELETE'})}}