import {z} from 'zod';import {Risk,requireApproval} from './policy.js';
const sym=z.string().regex(/^[A-Z0-9.\/-]{1,20}$/);const id=z.string().min(1).max(100);const approval=z.string().optional();
export function toolset(client,cfg){const T={};const add=(name,risk,schema,fn,description)=>T[name]={risk,schema,description,run:async raw=>{const a=schema.parse(raw);requireApproval(cfg,a.approval_token,risk);return fn(a);}};
add('alpaca.account.get',Risk.READ,z.object({}),()=>client.request('GET','/v2/account'),'Read account balances, buying power and status.');
add('alpaca.position.list',Risk.READ,z.object({}),()=>client.request('GET','/v2/positions'),'List open positions.');
add('alpaca.position.get',Risk.READ,z.object({symbol:sym}),a=>client.request('GET',`/v2/positions/${encodeURIComponent(a.symbol)}`),'Get one open position.');
add('alpaca.order.list',Risk.READ,z.object({status:z.enum(['open','closed','all']).default('open'),limit:z.number().int().min(1).max(500).default(50),after:z.string().optional(),until:z.string().optional(),direction:z.enum(['asc','desc']).default('desc')}),a=>client.request('GET','/v2/orders',{query:a}),'List orders with bounded pagination.');
add('alpaca.order.get',Risk.READ,z.object({order_id:id}),a=>client.request('GET',`/v2/orders/${encodeURIComponent(a.order_id)}`),'Get order status.');
add('alpaca.order.create',Risk.HIGH_RISK,z.object({symbol:sym,side:z.enum(['buy','sell']),type:z.enum(['market','limit','stop','stop_limit','trailing_stop']),time_in_force:z.enum(['day','gtc','opg','cls','ioc','fok']),qty:z.number().positive().optional(),notional:z.number().positive().optional(),limit_price:z.number().positive().optional(),stop_price:z.number().positive().optional(),trail_price:z.number().positive().optional(),trail_percent:z.number().positive().optional(),client_order_id:z.string().max(48).optional(),approval_token:approval}).refine(x=>(x.qty===undefined)!==(x.notional===undefined),{message:'Exactly one of qty or notional is required'}).refine(x=>x.type!=='limit'||x.limit_price!==undefined,{message:'limit_price required for limit'}).refine(x=>x.type!=='stop'||x.stop_price!==undefined,{message:'stop_price required for stop'}).refine(x=>x.type!=='stop_limit'||(x.stop_price!==undefined&&x.limit_price!==undefined),{message:'stop_price and limit_price required for stop_limit'}),a=>{const {approval_token,...body}=a;return client.request('POST','/v2/orders',{body});},'Submit a trading order; explicit approval is mandatory.');
add('alpaca.order.cancel',Risk.DESTRUCTIVE,z.object({order_id:id,approval_token:approval}),a=>client.request('DELETE',`/v2/orders/${encodeURIComponent(a.order_id)}`),'Cancel an order; explicit approval is mandatory.');
add('alpaca.asset.search',Risk.READ,z.object({status:z.enum(['active','inactive']).default('active'),asset_class:z.string().optional()}),a=>client.request('GET','/v2/assets',{query:{status:a.status,asset_class:a.asset_class}}),'Search/list tradable assets.');
add('alpaca.asset.get',Risk.READ,z.object({symbol_or_id:id}),a=>client.request('GET',`/v2/assets/${encodeURIComponent(a.symbol_or_id)}`),'Get asset metadata.');
add('alpaca.market.clock',Risk.READ,z.object({}),()=>client.request('GET','/v2/clock'),'Read market clock.');
add('alpaca.market.calendar',Risk.READ,z.object({start:z.string().optional(),end:z.string().optional()}),a=>client.request('GET','/v2/calendar',{query:a}),'Read market calendar.');
add('alpaca.watchlist.list',Risk.READ,z.object({}),()=>client.request('GET','/v2/watchlists'),'List watchlists.');
add('alpaca.watchlist.get',Risk.READ,z.object({watchlist_id:id}),a=>client.request('GET',`/v2/watchlists/${encodeURIComponent(a.watchlist_id)}`),'Get watchlist.');
add('alpaca.watchlist.create',Risk.WRITE,z.object({name:z.string().min(1).max(64),symbols:z.array(sym).max(100).default([]),approval_token:approval}),a=>client.request('POST','/v2/watchlists',{body:{name:a.name,symbols:a.symbols}}),'Create watchlist; approval required.');
add('alpaca.watchlist.add_asset',Risk.WRITE,z.object({watchlist_id:id,symbol:sym,approval_token:approval}),a=>client.request('POST',`/v2/watchlists/${encodeURIComponent(a.watchlist_id)}`,{body:{symbol:a.symbol}}),'Add asset to watchlist; approval required.');return T;}
