import { z } from 'zod';
import type { Risk } from './policy.js';
const pub=z.string().regex(/^pub_[0-9a-fA-F-]+$/);const post=z.string().regex(/^post_[0-9a-fA-F-]+$/);const aut=z.string().regex(/^aut_[0-9a-fA-F-]+$/);const seg=z.string().regex(/^seg_[0-9a-fA-F-]+$/);const email=z.string().email();
const page=z.object({limit:z.number().int().min(1).max(100).optional(),page:z.number().int().min(1).optional()});
const approval=z.object({confirmed:z.literal(true),reason:z.string().min(3).max(500)});
export type Def={name:string;risk:Risk;description:string;schema:z.ZodTypeAny;run:(c:any,a:any)=>Promise<any>};
export const tools:Def[]=[
{name:'beehiiv.workspace.permissions.get',risk:'READ',description:'Read permissions granted to the current API/OAuth token.',schema:z.object({}),run:(c)=>c.request('GET','/workspaces/permissions')},
{name:'beehiiv.publication.list',risk:'READ',description:'List publications visible to the credential.',schema:page,run:(c,a)=>c.request('GET','/publications',{query:a})},
{name:'beehiiv.publication.engagements.get',risk:'READ',description:'Read publication email engagement metrics for a bounded date range.',schema:z.object({publicationId:pub,startDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),endDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),granularity:z.enum(['day','week','month']).optional()}),run:(c,a)=>c.request('GET',`/publications/${a.publicationId}/engagements`,{query:{start_date:a.startDate,end_date:a.endDate,granularity:a.granularity}})},
{name:'beehiiv.post.list',risk:'READ',description:'List posts for a publication.',schema:page.extend({publicationId:pub}),run:(c,a)=>c.request('GET',`/publications/${a.publicationId}/posts`,{query:{limit:a.limit,page:a.page}})},
{name:'beehiiv.post.preview.get',risk:'READ',description:'Generate a session-protected preview URL for a post.',schema:z.object({publicationId:pub,postId:post,platform:z.enum(['email','web']).optional(),subscriberType:z.enum(['free','premium']).optional()}),run:(c,a)=>c.request('GET',`/publications/${a.publicationId}/posts/${a.postId}/preview`,{query:{platform:a.platform,subscriber_type:a.subscriberType}})},
{name:'beehiiv.subscription.list',risk:'READ',description:'List subscriptions using bounded pagination.',schema:page.extend({publicationId:pub}),run:(c,a)=>c.request('GET',`/publications/${a.publicationId}/subscriptions`,{query:{limit:a.limit,page:a.page}})},
{name:'beehiiv.subscription.get_by_email',risk:'READ',description:'Find a publication subscription by exact email.',schema:z.object({publicationId:pub,email}),run:(c,a)=>c.request('GET',`/publications/${a.publicationId}/subscriptions/by_email/${encodeURIComponent(a.email)}`)},
{name:'beehiiv.subscription.create',risk:'WRITE',description:'Create or reactivate a newsletter subscription. Requires human approval.',schema:z.object({publicationId:pub,email,reactivateExisting:z.boolean().optional(),sendWelcomeEmail:z.boolean().optional(),utmSource:z.string().max(200).optional(),approval}),run:(c,a)=>c.request('POST',`/publications/${a.publicationId}/subscriptions`,{body:{email:a.email,reactivate_existing:a.reactivateExisting,send_welcome_email:a.sendWelcomeEmail,utm_source:a.utmSource}})},
{name:'beehiiv.automation.list',risk:'READ',description:'List automations for a publication.',schema:z.object({publicationId:pub}),run:(c,a)=>c.request('GET',`/publications/${a.publicationId}/automations`)},
{name:'beehiiv.automation.enroll',risk:'WRITE',description:'Enroll an existing subscriber into an API-triggered automation. Requires human approval.',schema:z.object({publicationId:pub,automationId:aut,email:email.optional(),subscriptionId:z.string().regex(/^sub_[0-9a-fA-F-]+$/).optional(),approval}).refine(x=>!!x.email!==!!x.subscriptionId,'Provide exactly one of email or subscriptionId'),run:(c,a)=>c.request('POST',`/publications/${a.publicationId}/automations/${a.automationId}/journeys`,{body:{email:a.email,subscription_id:a.subscriptionId}})},
{name:'beehiiv.segment.members.list',risk:'READ',description:'List detailed subscribers in a segment.',schema:page.extend({publicationId:pub,segmentId:seg}),run:(c,a)=>c.request('GET',`/publications/${a.publicationId}/segments/${a.segmentId}/members`,{query:{limit:a.limit,page:a.page}})},
{name:'beehiiv.webhook.list',risk:'READ',description:'List publication webhooks.',schema:z.object({publicationId:pub,limit:z.number().int().min(1).max(100).optional()}),run:(c,a)=>c.request('GET',`/publications/${a.publicationId}/webhooks`,{query:{limit:a.limit}})},
{name:'beehiiv.webhook.create',risk:'HIGH_RISK',description:'Create a webhook delivery target. Requires explicit human approval because events send data externally.',schema:z.object({publicationId:pub,url:z.string().url().refine(u=>u.startsWith('https://'),'Webhook URL must use HTTPS'),eventTypes:z.array(z.string().min(1)).min(1).max(26),description:z.string().max(500).optional(),approval}),run:(c,a)=>c.request('POST',`/publications/${a.publicationId}/webhooks`,{body:{url:a.url,event_types:a.eventTypes,description:a.description}})}
];
