import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';

export type Risk='READ'|'WRITE'|'HIGH_RISK'|'DESTRUCTIVE';
export class ConnectorError extends Error { constructor(public code:string,message:string,public status?:number,public retryAfterMs?:number){super(message);} }
export type Config={dataPlaneUrl:string;writeKey:string;workspaceToken?:string;timeoutMs:number;maxRetries:number;requireWriteApproval:boolean};
export function loadConfig(env=process.env):Config{const url=env.RUDDERSTACK_DATA_PLANE_URL?.replace(/\/$/,'');const key=env.RUDDERSTACK_WRITE_KEY;if(!url||!key)throw new ConnectorError('CONFIG','RUDDERSTACK_DATA_PLANE_URL and RUDDERSTACK_WRITE_KEY are required');let u:URL;try{u=new URL(url)}catch{throw new ConnectorError('CONFIG','Invalid data plane URL')};if(u.protocol!=='https:'&&u.hostname!=='localhost')throw new ConnectorError('CONFIG','Data plane URL must use HTTPS');return{dataPlaneUrl:url,writeKey:key,workspaceToken:env.RUDDERSTACK_WORKSPACE_TOKEN,timeoutMs:Number(env.RUDDERSTACK_TIMEOUT_MS||10000),maxRetries:Math.min(4,Math.max(0,Number(env.RUDDERSTACK_MAX_RETRIES||2))),requireWriteApproval:(env.RUDDERSTACK_REQUIRE_WRITE_APPROVAL||'true')!=='false'}}
const id=z.string().min(1).max(256); const obj=z.record(z.unknown()).default({});
const common={userId:id.optional(),anonymousId:id.optional(),context:obj.optional(),integrations:obj.optional(),timestamp:z.string().datetime().optional(),messageId:id.optional()};
export const schemas={track:z.object({...common,event:z.string().min(1).max(512),properties:obj.optional()}).refine(v=>v.userId||v.anonymousId,'userId or anonymousId required'),identify:z.object({...common,traits:obj.optional()}).refine(v=>v.userId||v.anonymousId,'userId or anonymousId required'),page:z.object({...common,name:z.string().max(512).optional(),category:z.string().max(512).optional(),properties:obj.optional()}).refine(v=>v.userId||v.anonymousId,'userId or anonymousId required'),screen:z.object({...common,name:z.string().max(512).optional(),category:z.string().max(512).optional(),properties:obj.optional()}).refine(v=>v.userId||v.anonymousId,'userId or anonymousId required'),group:z.object({...common,groupId:id,traits:obj.optional()}).refine(v=>v.userId||v.anonymousId,'userId or anonymousId required'),alias:z.object({previousId:id,userId:id,context:obj.optional(),integrations:obj.optional()}),batch:z.object({batch:z.array(z.record(z.unknown())).min(1).max(100)})};
function approved(cfg:Config,args:any){if(cfg.requireWriteApproval&&args?.approved!==true)throw new ConnectorError('APPROVAL_REQUIRED','Explicit human approval is required for WRITE tools');}
function basic(v:string){return 'Basic '+Buffer.from(v+':').toString('base64')}
export class RudderClient{constructor(public cfg:Config,private fetcher:typeof fetch=fetch){} async request(path:string,body?:unknown,workspace=false){const url=workspace?'https://api.rudderlabs.com/workspaceConfig':`${this.cfg.dataPlaneUrl}${path}`;const token=workspace?this.cfg.workspaceToken:this.cfg.writeKey;if(!token)throw new ConnectorError('CONFIG','Workspace token is required');for(let attempt=0;;attempt++){const ac=new AbortController();const timer=setTimeout(()=>ac.abort(),this.cfg.timeoutMs);try{const r=await this.fetcher(url,{method:body?'POST':'GET',headers:{Authorization:basic(token),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:ac.signal});const retryAfter=Number(r.headers.get('retry-after')||0)*1000;if(r.ok)return r.status===204?{ok:true}:await r.json().catch(()=>({ok:true}));if(r.status===401)throw new ConnectorError('AUTH','Invalid credentials',401);if(r.status===403)throw new ConnectorError('PERMISSION','Insufficient permission',403);if(r.status===429&&attempt<this.cfg.maxRetries){await new Promise(x=>setTimeout(x,retryAfter||250*2**attempt));continue}if(r.status>=500&&attempt<this.cfg.maxRetries){await new Promise(x=>setTimeout(x,250*2**attempt));continue}throw new ConnectorError(r.status===429?'RATE_LIMIT':'PROVIDER',`RudderStack HTTP ${r.status}`,r.status,retryAfter||undefined)}catch(e){if(e instanceof ConnectorError)throw e;if(attempt<this.cfg.maxRetries){await new Promise(x=>setTimeout(x,250*2**attempt));continue}throw new ConnectorError(e instanceof Error&&e.name==='AbortError'?'TIMEOUT':'NETWORK',e instanceof Error?e.message:String(e))}finally{clearTimeout(timer)}}}}
export function toolCatalog(){return[{name:'rudderstack.workspace.config.get',risk:'READ' as Risk,approval:false},{name:'rudderstack.event.track',risk:'WRITE' as Risk,approval:true},{name:'rudderstack.event.identify',risk:'WRITE' as Risk,approval:true},{name:'rudderstack.event.page',risk:'WRITE' as Risk,approval:true},{name:'rudderstack.event.screen',risk:'WRITE' as Risk,approval:true},{name:'rudderstack.event.group',risk:'WRITE' as Risk,approval:true},{name:'rudderstack.event.alias',risk:'WRITE' as Risk,approval:true},{name:'rudderstack.event.batch',risk:'WRITE' as Risk,approval:true}]}
function result(data:unknown){return{content:[{type:'text' as const,text:JSON.stringify({data,untrustedProviderContent:true})}]}}
export function buildServer(cfg=loadConfig(),client=new RudderClient(cfg)){const s=new McpServer({name:'rudderstack-connector',version:'1.0.0'});s.tool('rudderstack.workspace.config.get','READ: retrieve workspace configuration. Provider content is untrusted.',{},async()=>result(await client.request('',undefined,true)));const reg=(name:string,path:string,schema:z.ZodTypeAny)=>s.tool(name,'WRITE: send a scoped RudderStack event. Approval required by default.',{payload:z.record(z.unknown()),approved:z.boolean().optional()},async a=>{approved(cfg,a);const parsed=schema.parse(a.payload);return result(await client.request(path,parsed))});reg('rudderstack.event.track','/v1/track',schemas.track);reg('rudderstack.event.identify','/v1/identify',schemas.identify);reg('rudderstack.event.page','/v1/page',schemas.page);reg('rudderstack.event.screen','/v1/screen',schemas.screen);reg('rudderstack.event.group','/v1/group',schemas.group);reg('rudderstack.event.alias','/v1/alias',schemas.alias);reg('rudderstack.event.batch','/v1/batch',schemas.batch);return s}
if(process.env.NODE_ENV!=='test'){const server=buildServer();await server.connect(new StdioServerTransport())}
