import {z} from 'zod';import {Client,page} from './client.js';import {key,requireApproval,Risk} from './security.js';
const K=z.string().min(1).max(128).regex(/^[A-Za-z0-9._:-]+$/), P=z.object({projectKey:K}), PE=z.object({projectKey:K,environmentKey:K});
export type Def={name:string;risk:Risk;schema:z.ZodTypeAny;run:(a:any,c:Client)=>Promise<any>};const enc=encodeURIComponent;
export const tools:Def[]=[
{name:'launchdarkly.project.list',risk:'READ',schema:z.object({limit:z.number().int().min(1).max(100).default(20),offset:z.number().int().min(0).default(0)}),run:async(a,c)=>c.request('/projects?'+page(new URLSearchParams(),a.limit,a.offset))},
{name:'launchdarkly.project.get',risk:'READ',schema:P,run:async(a,c)=>c.request('/projects/'+enc(key(a.projectKey,'projectKey')))},
{name:'launchdarkly.environment.list',risk:'READ',schema:P.extend({limit:z.number().int().min(1).max(100).default(20),offset:z.number().int().min(0).default(0)}),run:async(a,c)=>c.request(`/projects/${enc(a.projectKey)}/environments?`+page(new URLSearchParams(),a.limit,a.offset))},
{name:'launchdarkly.flag.list',risk:'READ',schema:P.extend({environmentKey:K.optional(),query:z.string().max(200).optional(),limit:z.number().int().min(1).max(100).default(20),offset:z.number().int().min(0).default(0)}),run:async(a,c)=>{const q=page(new URLSearchParams(),a.limit,a.offset);if(a.environmentKey)q.set('env',a.environmentKey);if(a.query)q.set('filter',`query:${a.query}`);return c.request(`/flags/${enc(a.projectKey)}?${q}`)}},
{name:'launchdarkly.flag.get',risk:'READ',schema:P.extend({flagKey:K,environmentKey:K.optional()}),run:async(a,c)=>c.request(`/flags/${enc(a.projectKey)}/${enc(a.flagKey)}${a.environmentKey?'?env='+enc(a.environmentKey):''}`)},
{name:'launchdarkly.flag.status',risk:'READ',schema:PE.extend({flagKey:K}),run:async(a,c)=>c.request(`/flag-statuses/${enc(a.projectKey)}/${enc(a.environmentKey)}/${enc(a.flagKey)}`)},
{name:'launchdarkly.flag.create',risk:'WRITE',schema:P.extend({flagKey:K,name:z.string().min(1).max(256),description:z.string().max(2000).optional(),variations:z.array(z.object({value:z.union([z.string(),z.number(),z.boolean()]),name:z.string().max(256).optional()})).min(2).max(20),approved:z.boolean().default(false)}),run:async(a,c)=>{requireApproval('WRITE',a.approved);const {approved,...b}=a;return c.request(`/flags/${enc(a.projectKey)}`,{method:'POST',body:JSON.stringify({key:b.flagKey,name:b.name,description:b.description,variations:b.variations})})}},
{name:'launchdarkly.flag.update',risk:'HIGH_RISK',schema:P.extend({flagKey:K,patch:z.array(z.object({op:z.enum(['replace','add','remove']),path:z.string().min(1).max(512).regex(/^\/(?!.*(?:access|role|permission))/),value:z.unknown().optional()})).min(1).max(20),approved:z.boolean()}),run:async(a,c)=>{requireApproval('HIGH_RISK',a.approved);return c.request(`/flags/${enc(a.projectKey)}/${enc(a.flagKey)}`,{method:'PATCH',body:JSON.stringify(a.patch)})}},
{name:'launchdarkly.flag.archive',risk:'HIGH_RISK',schema:P.extend({flagKey:K,approved:z.boolean()}),run:async(a,c)=>{requireApproval('HIGH_RISK',a.approved);return c.request(`/flags/${enc(a.projectKey)}/${enc(a.flagKey)}`,{method:'PATCH',body:JSON.stringify([{op:'replace',path:'/archived',value:true}])})}}
];