import { z } from 'zod';import { Risk,requireApproval,cleanArgs } from './policy.js';
const key=z.string().min(1).max(128).regex(/^[A-Za-z0-9._:-]+$/);const page=z.object({limit:z.number().int().min(1).max(100).default(20),offset:z.number().int().min(0).default(0)});
export function toolDefinitions(client,config){const defs=[
['launchdarkly.project.list',Risk.READ,page,async a=>client.request('GET','/projects',{query:a})],
['launchdarkly.project.get',Risk.READ,z.object({projectKey:key}),async a=>client.request('GET',`/projects/${encodeURIComponent(a.projectKey)}`)],
['launchdarkly.environment.list',Risk.READ,z.object({projectKey:key}),async a=>client.request('GET',`/projects/${encodeURIComponent(a.projectKey)}/environments`)],
['launchdarkly.flag.list',Risk.READ,page.extend({projectKey:key,env:z.string().optional(),query:z.string().max(200).optional()}),async a=>client.request('GET',`/flags/${encodeURIComponent(a.projectKey)}`,{query:{limit:a.limit,offset:a.offset,env:a.env,filter:a.query?`query:${a.query}`:undefined}})],
['launchdarkly.flag.get',Risk.READ,z.object({projectKey:key,flagKey:key,env:z.string().optional()}),async a=>client.request('GET',`/flags/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.flagKey)}`,{query:{env:a.env}})],
['launchdarkly.flag.create',Risk.WRITE,z.object({projectKey:key,key, name:z.string().min(1).max(256),kind:z.enum(['boolean','multivariate']).default('boolean'),description:z.string().max(1000).optional(),approved:z.boolean().optional()}),async a=>client.request('POST',`/flags/${encodeURIComponent(a.projectKey)}`,{body:{key:a.key,name:a.name,kind:a.kind,description:a.description}})],
['launchdarkly.flag.update',Risk.WRITE,z.object({projectKey:key,flagKey:key,patch:z.array(z.object({op:z.enum(['add','remove','replace','test']),path:z.string().startsWith('/'),value:z.unknown().optional()})).min(1).max(20),approved:z.boolean().optional()}),async a=>client.request('PATCH',`/flags/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.flagKey)}`,{body:a.patch})],
['launchdarkly.segment.list',Risk.READ,z.object({projectKey:key,environmentKey:key}).merge(page),async a=>client.request('GET',`/segments/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.environmentKey)}`,{query:{limit:a.limit,offset:a.offset}})],
['launchdarkly.segment.get',Risk.READ,z.object({projectKey:key,environmentKey:key,segmentKey:key}),async a=>client.request('GET',`/segments/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.environmentKey)}/${encodeURIComponent(a.segmentKey)}`)]
];return defs.map(([name,risk,schema,run])=>({name,risk,schema,async execute(raw){const args=schema.parse(raw);requireApproval(config,risk,args);const data=await run(cleanArgs(args));return {untrustedProviderData:true,data}}}))}
