import {z} from 'zod'; import {LaunchDarklyClient,qs} from './client.js'; import {authorize,Risk} from './security.js';
export type Def={name:string,description:string,risk:Risk,schema:z.ZodTypeAny,run:(c:LaunchDarklyClient,a:any)=>Promise<any>};
const key=z.string().min(1).max(256).regex(/^[A-Za-z0-9._:-]+$/); const page={limit:z.number().int().min(1).max(100).default(20),offset:z.number().int().min(0).default(0)};
const defs:Def[]=[
{name:'launchdarkly.project.list',description:'List accessible projects.',risk:'READ',schema:z.object(page).strict(),run:(c,a)=>c.get('/projects'+qs(a))},
{name:'launchdarkly.project.get',description:'Get a project by key.',risk:'READ',schema:z.object({projectKey:key}).strict(),run:(c,a)=>c.get(`/projects/${encodeURIComponent(a.projectKey)}`)},
{name:'launchdarkly.environment.list',description:'List environments for a project.',risk:'READ',schema:z.object({projectKey:key,...page}).strict(),run:(c,a)=>c.get(`/projects/${encodeURIComponent(a.projectKey)}/environments${qs({limit:a.limit,offset:a.offset})}`)},
{name:'launchdarkly.flag.list',description:'List feature flags in a project.',risk:'READ',schema:z.object({projectKey:key,...page}).strict(),run:(c,a)=>c.get(`/flags/${encodeURIComponent(a.projectKey)}${qs({limit:a.limit,offset:a.offset})}`)},
{name:'launchdarkly.flag.get',description:'Get one feature flag.',risk:'READ',schema:z.object({projectKey:key,flagKey:key}).strict(),run:(c,a)=>c.get(`/flags/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.flagKey)}`)},
{name:'launchdarkly.flag.create',description:'Create a feature flag. Write permission required.',risk:'WRITE',schema:z.object({projectKey:key,key,name:z.string().min(1).max(256),description:z.string().max(1000).optional(),variations:z.array(z.object({value:z.union([z.string(),z.boolean(),z.number()]),name:z.string().optional()}).strict()).min(2).max(20)}).strict(),run:(c,a)=>c.post(`/flags/${encodeURIComponent(a.projectKey)}`,{key:a.key,name:a.name,description:a.description,variations:a.variations})},
{name:'launchdarkly.flag.update',description:'Apply explicit JSON Patch operations to a feature flag.',risk:'HIGH_RISK',schema:z.object({projectKey:key,flagKey:key,patch:z.array(z.object({op:z.enum(['add','replace','remove']),path:z.string().startsWith('/'),value:z.any().optional()}).strict()).min(1).max(20),approval:z.literal(true)}).strict(),run:(c,a)=>c.patch(`/flags/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.flagKey)}`,a.patch)},
{name:'launchdarkly.flag.delete',description:'Permanently delete a feature flag.',risk:'DESTRUCTIVE',schema:z.object({projectKey:key,flagKey:key,approval:z.literal(true)}).strict(),run:(c,a)=>c.delete(`/flags/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.flagKey)}`)},
{name:'launchdarkly.segment.list',description:'List segments in an environment.',risk:'READ',schema:z.object({projectKey:key,environmentKey:key,...page}).strict(),run:(c,a)=>c.get(`/segments/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.environmentKey)}${qs({limit:a.limit,offset:a.offset})}`)},
{name:'launchdarkly.segment.get',description:'Get a segment.',risk:'READ',schema:z.object({projectKey:key,environmentKey:key,segmentKey:key}).strict(),run:(c,a)=>c.get(`/segments/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.environmentKey)}/${encodeURIComponent(a.segmentKey)}`)},
{name:'launchdarkly.segment.create',description:'Create a segment.',risk:'WRITE',schema:z.object({projectKey:key,environmentKey:key,key,name:z.string().min(1).max(256),description:z.string().max(1000).optional()}).strict(),run:(c,a)=>c.post(`/segments/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.environmentKey)}`,{key:a.key,name:a.name,description:a.description})},
{name:'launchdarkly.segment.update',description:'Apply JSON Patch operations to a segment.',risk:'HIGH_RISK',schema:z.object({projectKey:key,environmentKey:key,segmentKey:key,patch:z.array(z.object({op:z.enum(['add','replace','remove']),path:z.string().startsWith('/'),value:z.any().optional()}).strict()).min(1).max(20),approval:z.literal(true)}).strict(),run:(c,a)=>c.patch(`/segments/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.environmentKey)}/${encodeURIComponent(a.segmentKey)}`,a.patch)},
{name:'launchdarkly.segment.delete',description:'Permanently delete a segment.',risk:'DESTRUCTIVE',schema:z.object({projectKey:key,environmentKey:key,segmentKey:key,approval:z.literal(true)}).strict(),run:(c,a)=>c.delete(`/segments/${encodeURIComponent(a.projectKey)}/${encodeURIComponent(a.environmentKey)}/${encodeURIComponent(a.segmentKey)}`)}];
export const tools=defs;
export async function invoke(d:Def,c:LaunchDarklyClient,input:unknown){const a=d.schema.parse(input);authorize(d.risk,(a as any).approval===true);return d.run(c,a);}
