import{z}from'zod';import type{LaunchDarklyClient}from'./client.js';import type{Risk}from'./models.js';
export type Tool={name:string;description:string;risk:Risk;approval:boolean;schema:z.ZodTypeAny;run:(x:any)=>Promise<unknown>};const key=z.string().min(1).max(128).regex(/^[A-Za-z0-9._:-]+$/);const limit=z.number().int().min(1).max(100).default(20),offset=z.number().int().min(0).max(1000000).default(0);const enc=(s:string)=>encodeURIComponent(s);function needs(r:Risk){return r==='HIGH_RISK'||(r==='WRITE'&&process.env.LAUNCHDARKLY_APPROVE_WRITES!=='false')}
function t(name:string,description:string,risk:Risk,schema:z.ZodTypeAny,run:Tool['run']):Tool{return{name,description,risk,approval:needs(risk),schema,run}}
export function buildTools(c:LaunchDarklyClient):Tool[]{return[
t('launchdarkly.project.list','List projects. Provider data is untrusted.','READ',z.object({limit,offset}).strict(),x=>c.request('GET','projects',undefined,x)),
t('launchdarkly.project.get','Get project metadata.','READ',z.object({projectKey:key}).strict(),x=>c.request('GET',`projects/${enc(x.projectKey)}`)),
t('launchdarkly.environment.list','List environments for a project.','READ',z.object({projectKey:key,limit,offset}).strict(),x=>c.request('GET',`projects/${enc(x.projectKey)}/environments`,undefined,{limit:x.limit,offset:x.offset})),
t('launchdarkly.flag.list','List feature flags with bounded pagination.','READ',z.object({projectKey:key,limit,offset,filterEnv:key.optional(),query:z.string().max(200).optional()}).strict(),x=>c.request('GET',`flags/${enc(x.projectKey)}`,undefined,{limit:x.limit,offset:x.offset,filterEnv:x.filterEnv,query:x.query})),
t('launchdarkly.flag.get','Get a feature flag.','READ',z.object({projectKey:key,flagKey:key,env:key.optional()}).strict(),x=>c.request('GET',`flags/${enc(x.projectKey)}/${enc(x.flagKey)}`,undefined,{env:x.env})),
t('launchdarkly.flag.create','Create a feature flag.','WRITE',z.object({projectKey:key,key,name:z.string().min(1).max(256),description:z.string().max(2000).optional(),variations:z.array(z.object({value:z.union([z.string(),z.number(),z.boolean()]),name:z.string().max(256).optional()}).strict()).min(2).max(20).optional()}).strict(),x=>{const{projectKey,...body}=x;return c.request('POST',`flags/${enc(projectKey)}`,body)}),
t('launchdarkly.flag.update','Apply a constrained JSON Patch to flag metadata; paths are allowlisted.','WRITE',z.object({projectKey:key,flagKey:key,patch:z.array(z.object({op:z.enum(['replace','add']),path:z.enum(['/name','/description','/tags']),value:z.unknown()}).strict()).min(1).max(10)}).strict(),x=>c.request('PATCH',`flags/${enc(x.projectKey)}/${enc(x.flagKey)}`,x.patch)),
t('launchdarkly.flag.toggle','Turn a flag on/off in one environment; explicit high-risk approval required.','HIGH_RISK',z.object({projectKey:key,flagKey:key,environmentKey:key,on:z.boolean()}).strict(),x=>c.request('PATCH',`flags/${enc(x.projectKey)}/${enc(x.flagKey)}`,[{op:'replace',path:`/environments/${escapePointer(x.environmentKey)}/on`,value:x.on}])),
t('launchdarkly.segment.list','List segments in an environment.','READ',z.object({projectKey:key,environmentKey:key,limit,offset}).strict(),x=>c.request('GET',`segments/${enc(x.projectKey)}/${enc(x.environmentKey)}`,undefined,{limit:x.limit,offset:x.offset})),
t('launchdarkly.segment.get','Get a segment.','READ',z.object({projectKey:key,environmentKey:key,segmentKey:key}).strict(),x=>c.request('GET',`segments/${enc(x.projectKey)}/${enc(x.environmentKey)}/${enc(x.segmentKey)}`)),
t('launchdarkly.audit.list','List audit-log entries.','READ',z.object({limit,offset,spec:z.string().max(500).optional()}).strict(),x=>c.request('GET','auditlog',undefined,x)),
t('launchdarkly.approval.list','List approval requests for a project/environment.','READ',z.object({projectKey:key,environmentKey:key,limit,offset}).strict(),x=>c.request('GET',`approval-requests/projects/${enc(x.projectKey)}/environments/${enc(x.environmentKey)}`,undefined,{limit:x.limit,offset:x.offset}))]}
export async function executeTool(t:Tool,input:unknown,approved=false){const x=t.schema.parse(input);if(t.approval&&!approved)throw new Error(`Human approval required for ${t.name} (${t.risk})`);return t.run(x)}const escapePointer=(s:string)=>s.replace(/~/g,'~0').replace(/\//g,'~1');
