import crypto from 'node:crypto';import{z}from'zod';import{Risk,requireApproval}from'./policy.js';
const id=z.string().min(1).max(128);const page=z.object({count:z.number().int().min(1).max(1000).default(50),offset:z.number().int().min(0).default(0)});const email=z.string().email();const hash=e=>crypto.createHash('md5').update(e.trim().toLowerCase()).digest('hex');
export function buildTools(client,config){const run=(risk,fn)=>(a)=>{requireApproval(risk,a.approved===true,config.approvalMode);return fn(a)};return[
['mailchimp.account.get',Risk.READ,z.object({}),()=>client.request('GET','/')],
['mailchimp.audience.list',Risk.READ,page,a=>client.request('GET','/lists',{query:a})],
['mailchimp.audience.get',Risk.READ,z.object({listId:id}),a=>client.request('GET',`/lists/${encodeURIComponent(a.listId)}`)],
['mailchimp.contact.list',Risk.READ,page.extend({listId:id,status:z.enum(['subscribed','unsubscribed','cleaned','pending','transactional','archived']).optional()}),a=>client.request('GET',`/lists/${encodeURIComponent(a.listId)}/members`,{query:{count:a.count,offset:a.offset,status:a.status}})],
['mailchimp.contact.get',Risk.READ,z.object({listId:id,email}),a=>client.request('GET',`/lists/${encodeURIComponent(a.listId)}/members/${hash(a.email)}`)],
['mailchimp.contact.upsert',Risk.WRITE,z.object({listId:id,email,statusIfNew:z.enum(['subscribed','unsubscribed','cleaned','pending','transactional']).default('pending'),mergeFields:z.record(z.union([z.string(),z.number(),z.boolean()])).optional(),approved:z.boolean().optional()}),run(Risk.WRITE,a=>client.request('PUT',`/lists/${encodeURIComponent(a.listId)}/members/${hash(a.email)}`,{body:{email_address:a.email,status_if_new:a.statusIfNew,merge_fields:a.mergeFields}}))],
['mailchimp.contact.update',Risk.WRITE,z.object({listId:id,email,status:z.enum(['subscribed','unsubscribed','cleaned','pending','transactional']).optional(),mergeFields:z.record(z.union([z.string(),z.number(),z.boolean()])).optional(),approved:z.boolean().optional()}).refine(x=>x.status||x.mergeFields,'status or mergeFields required'),run(Risk.WRITE,a=>client.request('PATCH',`/lists/${encodeURIComponent(a.listId)}/members/${hash(a.email)}`,{body:{status:a.status,merge_fields:a.mergeFields}}))],
['mailchimp.contact.tags.list',Risk.READ,z.object({listId:id,email}),a=>client.request('GET',`/lists/${encodeURIComponent(a.listId)}/members/${hash(a.email)}/tags`)],
['mailchimp.contact.tags.update',Risk.WRITE,z.object({listId:id,email,tags:z.array(z.object({name:z.string().min(1).max(100),status:z.enum(['active','inactive'])})).min(1).max(50),approved:z.boolean().optional()}),run(Risk.WRITE,a=>client.request('POST',`/lists/${encodeURIComponent(a.listId)}/members/${hash(a.email)}/tags`,{body:{tags:a.tags}}))],
['mailchimp.contact.event.create',Risk.WRITE,z.object({listId:id,email,name:z.string().regex(/^[A-Za-z0-9_-]{2,30}$/),properties:z.record(z.union([z.string(),z.number(),z.boolean()])).optional(),approved:z.boolean().optional()}),run(Risk.WRITE,a=>client.request('POST',`/lists/${encodeURIComponent(a.listId)}/members/${hash(a.email)}/events`,{body:{name:a.name,properties:a.properties}}))],
['mailchimp.campaign.list',Risk.READ,page,a=>client.request('GET','/campaigns',{query:a})],
['mailchimp.campaign.get',Risk.READ,z.object({campaignId:id}),a=>client.request('GET',`/campaigns/${encodeURIComponent(a.campaignId)}`)],
['mailchimp.report.get',Risk.READ,z.object({campaignId:id}),a=>client.request('GET',`/reports/${encodeURIComponent(a.campaignId)}`)]
].map(([name,risk,schema,handler])=>({name,risk,schema,handler:async raw=>handler(schema.parse(raw))}));}