import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';
import {z} from 'zod'; import {OpsgenieClient} from './client.js'; import {Risk,authorize} from './policy.js';
const c=new OpsgenieClient(); const s=new McpServer({name:'opsgenie-connector',version:'1.0.0'}); const out=x=>({content:[{type:'text',text:JSON.stringify(x)}],structuredContent:x});
const gid=z.string().min(1).max(512); const approval=z.boolean().optional().describe('Explicit human approval captured by the caller.');
function tool(name,description,schema,risk,handler){s.tool(name,`${description} Risk=${risk}. ${risk==='READ'?'No approval required.':'Explicit approval required.'}`,schema,async a=>{authorize(risk,a.approval);return out(await handler(a));});}
tool('opsgenie.alert.list','List alerts with bounded pagination.',{query:z.string().max(1000).optional(),limit:z.number().int().min(1).max(100).default(50),offset:z.number().int().min(0).max(19900).default(0)},Risk.READ,a=>c.request('GET','/v2/alerts',{query:a}));
tool('opsgenie.alert.get','Get an alert by id, tiny id, or alias.',{identifier:gid,identifierType:z.enum(['id','tiny','alias']).default('id')},Risk.READ,a=>c.request('GET',`/v2/alerts/${encodeURIComponent(a.identifier)}`,{query:{identifierType:a.identifierType}}));
tool('opsgenie.team.list','List teams.',{limit:z.number().int().min(1).max(100).default(50),offset:z.number().int().min(0).default(0)},Risk.READ,a=>c.request('GET','/v2/teams',{query:a}));
tool('opsgenie.team.get','Get a team by id or name.',{identifier:gid,identifierType:z.enum(['id','name']).default('id')},Risk.READ,a=>c.request('GET',`/v2/teams/${encodeURIComponent(a.identifier)}`,{query:{identifierType:a.identifierType}}));
tool('opsgenie.schedule.list','List schedules.',{limit:z.number().int().min(1).max(100).default(50),offset:z.number().int().min(0).default(0)},Risk.READ,a=>c.request('GET','/v2/schedules',{query:a}));
tool('opsgenie.schedule.oncall.get','Get current on-call participants for a schedule.',{identifier:gid,identifierType:z.enum(['id','name']).default('id'),flat:z.boolean().default(true)},Risk.READ,a=>c.request('GET',`/v2/schedules/${encodeURIComponent(a.identifier)}/on-calls`,{query:{scheduleIdentifierType:a.identifierType,flat:a.flat}}));
tool('opsgenie.alert.note.add','Add an operator note to an alert.',{identifier:gid,identifierType:z.enum(['id','tiny','alias']).default('id'),note:z.string().min(1).max(25000),user:z.string().max(100).optional(),source:z.string().max(100).optional(),approval},Risk.WRITE,a=>c.request('POST',`/v2/alerts/${encodeURIComponent(a.identifier)}/notes`,{query:{identifierType:a.identifierType},body:{note:a.note,user:a.user,source:a.source},retrySafe:false}));
tool('opsgenie.alert.acknowledge','Acknowledge an alert.',{identifier:gid,identifierType:z.enum(['id','tiny','alias']).default('id'),note:z.string().max(25000).optional(),user:z.string().max(100).optional(),source:z.string().max(100).optional(),approval},Risk.WRITE,a=>c.request('POST',`/v2/alerts/${encodeURIComponent(a.identifier)}/acknowledge`,{query:{identifierType:a.identifierType},body:{note:a.note,user:a.user,source:a.source},retrySafe:false}));
tool('opsgenie.alert.create','Create and route an alert; this can notify external responders.',{message:z.string().min(1).max(130),alias:z.string().max(512).optional(),description:z.string().max(15000).optional(),priority:z.enum(['P1','P2','P3','P4','P5']).default('P3'),tags:z.array(z.string().max(50)).max(20).optional(),entity:z.string().max(512).optional(),source:z.string().max(100).optional(),approval},Risk.HIGH_RISK,a=>{const {approval:_,...body}=a;return c.request('POST','/v2/alerts',{body,retrySafe:false});});
tool('opsgenie.alert.close','Close an alert. This changes incident-response state and is never retried automatically.',{identifier:gid,identifierType:z.enum(['id','tiny','alias']).default('id'),note:z.string().max(25000).optional(),user:z.string().max(100).optional(),source:z.string().max(100).optional(),approval},Risk.HIGH_RISK,a=>c.request('POST',`/v2/alerts/${encodeURIComponent(a.identifier)}/close`,{query:{identifierType:a.identifierType},body:{note:a.note,user:a.user,source:a.source},retrySafe:false}));
await s.connect(new StdioServerTransport());
