import {z} from 'zod'; import {GroundcoverClient} from './client.js';
export const iso=z.string().datetime();
const time={start:iso,end:iso,sources:z.array(z.unknown()).default([])};
export const tools=[
 {name:'groundcover.clusters.list',description:'List Kubernetes clusters with health and resource usage.',schema:z.object({sources:z.array(z.unknown()).default([])}).strict(),run:(c:GroundcoverClient,a:any)=>c.post('/api/k8s/v3/clusters/list',a)},
 {name:'groundcover.namespaces.list',description:'List namespaces observed in a UTC time range.',schema:z.object(time).strict(),run:(c:GroundcoverClient,a:any)=>c.post('/api/k8s/v2/namespaces/list',a)},
 {name:'groundcover.workloads.list',description:'List workloads and performance/resource metrics with bounded pagination.',schema:z.object({conditions:z.array(z.unknown()).default([]),limit:z.number().int().min(1).max(1000).default(100),skip:z.number().int().min(0).default(0),order:z.enum(['asc','desc']).default('desc'),sortBy:z.enum(['rps','cpuUsage','memoryUsage']).default('rps'),sources:z.array(z.unknown()).default([])}).strict(),run:(c:GroundcoverClient,a:any)=>c.post('/api/k8s/v3/workloads/list',a)},
 {name:'groundcover.nodes.list',description:'List Kubernetes nodes with resource information for a time range.',schema:z.object({...time,limit:z.number().int().min(1).max(1000).default(100),nameFilter:z.string().max(200).default('')}).strict(),run:(c:GroundcoverClient,a:any)=>c.post('/api/k8s/v2/nodes/info-with-resources',a)},
 {name:'groundcover.workflows.list',description:'List configured alert workflows and execution status.',schema:z.object({}).strict(),run:(c:GroundcoverClient)=>c.post('/api/workflows/list',{},false)},
 {name:'groundcover.monitors.summary',description:'Query monitor configurations, state, alert status and recent execution summary.',schema:z.object({conditions:z.array(z.unknown()).default([]),limit:z.number().int().min(1).max(200).default(100),skip:z.number().int().min(0).default(0),maxInstances:z.number().int().min(1).max(50).default(10),order:z.enum(['asc','desc']).default('desc'),sortBy:z.enum(['lastFiringStart','title','severity','createdAt','updatedAt','state']).default('lastFiringStart'),start:iso.optional(),end:iso.optional()}).strict(),run:(c:GroundcoverClient,a:any)=>c.post('/api/monitors/summary/query',a,false)},
 {name:'groundcover.metrics.query',description:'Run a read-only Prometheus instant query against groundcover metrics.',schema:z.object({query:z.string().min(1).max(4000),time:z.string().optional()}).strict(),run:(c:GroundcoverClient,a:any)=>c.prom('/api/v1/query',Object.fromEntries(Object.entries(a).filter(([,v])=>v!==undefined)) as any)},
 {name:'groundcover.metrics.query_range',description:'Run a bounded Prometheus range query.',schema:z.object({query:z.string().min(1).max(4000),start:z.string().min(1),end:z.string().min(1),step:z.string().regex(/^\d+(\.\d+)?(ms|s|m|h|d)?$/)}).strict(),run:(c:GroundcoverClient,a:any)=>c.prom('/api/v1/query_range',a)}
];
export async function invoke(c:GroundcoverClient,name:string,args:unknown){const t=tools.find(x=>x.name===name);if(!t)throw new Error('Unknown tool');const parsed=t.schema.parse(args);return t.run(c,parsed as any)}