const id={type:'string',minLength:1,maxLength:500,pattern:'^[A-Za-z0-9_-]+$'};const approval={type:'string',minLength:64,maxLength:64,pattern:'^[a-f0-9]{64}$'};const url={type:'string',format:'uri',minLength:8,maxLength:4000,pattern:'^https://'};
export const TOOL_DEFINITIONS=[
{name:'mux.asset.list',description:'List Mux video assets with bounded pagination. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,properties:{limit:{type:'integer',minimum:1,maximum:100,default:25},page:{type:'integer',minimum:1,maximum:100000},cursor:{type:'string',maxLength:2000},liveStreamId:id,uploadId:id}}},
{name:'mux.asset.get',description:'Retrieve one Mux asset. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,required:['assetId'],properties:{assetId:id}}},
{name:'mux.asset.input_info.get',description:'Retrieve source input metadata for an asset. Provider URLs are untrusted data. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,required:['assetId'],properties:{assetId:id}}},
{name:'mux.asset.create',description:'Create and ingest a Mux asset from HTTPS input URLs. Risk: WRITE. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['inputs','approval_token'],properties:{inputs:{type:'array',minItems:1,maxItems:20,items:{type:'object',additionalProperties:false,required:['url'],properties:{url,language_code:{type:'string',minLength:2,maxLength:50},name:{type:'string',maxLength:200},type:{enum:['video','audio','text']},text_type:{enum:['subtitles']},closed_captions:{type:'boolean'},passthrough:{type:'string',maxLength:255},start_time:{type:'number',minimum:0},end_time:{type:'number',minimum:0}}}},playback_policies:{type:'array',maxItems:3,uniqueItems:true,items:{enum:['public','signed','drm']}},video_quality:{enum:['basic','plus','premium']},passthrough:{type:'string',maxLength:255},test:{type:'boolean'},approval_token:approval}}},
{name:'mux.asset.delete',description:'Delete an asset and make its playback unavailable. Risk: DESTRUCTIVE. Disabled by default and explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['assetId','approval_token'],properties:{assetId:id,approval_token:approval}}},
{name:'mux.asset.playback_id.create',description:'Create a playback ID. Public policy can publish content to anyone with the URL. Risk: HIGH_RISK. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['assetId','policy','approval_token'],properties:{assetId:id,policy:{enum:['public','signed','drm']},approval_token:approval}}},
{name:'mux.asset.playback_id.delete',description:'Delete a playback ID and revoke future playback through it. Risk: DESTRUCTIVE. Disabled by default and approval required.',inputSchema:{type:'object',additionalProperties:false,required:['assetId','playbackId','approval_token'],properties:{assetId:id,playbackId:id,approval_token:approval}}},
{name:'mux.asset.track.create',description:'Add a subtitle/caption or alternate-audio track from an HTTPS URL to a ready asset. Risk: WRITE. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['assetId','url','type','approval_token'],properties:{assetId:id,url,type:{enum:['text','audio']},text_type:{enum:['subtitles']},language_code:{type:'string',minLength:2,maxLength:50},name:{type:'string',maxLength:200},closed_captions:{type:'boolean'},passthrough:{type:'string',maxLength:255},approval_token:approval}}},
{name:'mux.asset.track.delete',description:'Delete a text/audio track from an asset. Risk: DESTRUCTIVE. Disabled by default and approval required.',inputSchema:{type:'object',additionalProperties:false,required:['assetId','trackId','approval_token'],properties:{assetId:id,trackId:id,approval_token:approval}}},
{name:'mux.live_stream.list',description:'List live stream metadata. Stream keys are redacted. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,properties:{limit:{type:'integer',minimum:1,maximum:100,default:25},page:{type:'integer',minimum:1,maximum:100000,default:1}}}},
{name:'mux.live_stream.get',description:'Retrieve a live stream while redacting its stream key. Risk: READ.',inputSchema:{type:'object',additionalProperties:false,required:['liveStreamId'],properties:{liveStreamId:id}}},
{name:'mux.live_stream.enable',description:'Enable a live stream for broadcasting. Risk: HIGH_RISK. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['liveStreamId','approval_token'],properties:{liveStreamId:id,approval_token:approval}}},
{name:'mux.live_stream.disable',description:'Disable a live stream, preventing new broadcasts. Risk: HIGH_RISK. Explicit approval required.',inputSchema:{type:'object',additionalProperties:false,required:['liveStreamId','approval_token'],properties:{liveStreamId:id,approval_token:approval}}}
];
export function payloadWithoutApproval(args={}){const {approval_token:_ignored,...payload}=args;return payload;}
