import{z}from'zod';import{DifyClient}from'./client.js';import{authorize,inputs,page,safeId,untrusted,user,Risk}from'./core.js';
export type ToolDef={name:string,description:string,risk:Risk,approval:boolean,schema:z.ZodTypeAny,run:(a:any,c:DifyClient)=>Promise<any>};const qs=(a:any)=>{const q=new URLSearchParams();for(const[k,v]of Object.entries(a))if(v!==undefined)q.set(k,String(v));return q.toString()};
export const tools:ToolDef[]=[
{name:'dify.app.parameters.get',description:'Get application input parameters and file settings',risk:'READ',approval:false,schema:z.object({}),run:async(_a,c)=>untrusted(await c.request('GET','parameters'))},
{name:'dify.app.meta.get',description:'Get application metadata',risk:'READ',approval:false,schema:z.object({}),run:async(_a,c)=>untrusted(await c.request('GET','meta'))},
{name:'dify.conversation.list',description:'List conversations for an end user',risk:'READ',approval:false,schema:page,run:async(a,c)=>untrusted(await c.request('GET',`conversations?${qs(a)}`))},
{name:'dify.message.list',description:'List messages in a conversation',risk:'READ',approval:false,schema:z.object({user,conversation_id:safeId,first_id:safeId.optional(),limit:z.number().int().min(1).max(100).default(20)}),run:async(a,c)=>untrusted(await c.request('GET',`messages?${qs(a)}`))},
{name:'dify.workflow.run.get',description:'Get workflow run details',risk:'READ',approval:false,schema:z.object({workflow_run_id:safeId}),run:async(a,c)=>untrusted(await c.request('GET',`workflows/run/${encodeURIComponent(a.workflow_run_id)}`))},
{name:'dify.chat.send',description:'Send a message to a Dify chat application',risk:'HIGH_RISK',approval:true,schema:z.object({inputs,query:z.string().min(1).max(100000),user,conversation_id:safeId.optional(),response_mode:z.enum(['blocking','streaming']).default('blocking'),approved:z.literal(true)}),run:async(a,c)=>{authorize('HIGH_RISK',a.approved);const{approved,...b}=a;return untrusted(await c.request('POST','chat-messages',b))}},
{name:'dify.completion.create',description:'Invoke a Dify text-generation application',risk:'WRITE',approval:true,schema:z.object({inputs,user,response_mode:z.enum(['blocking','streaming']).default('blocking'),approved:z.literal(true)}),run:async(a,c)=>{authorize('WRITE',a.approved);const{approved,...b}=a;return untrusted(await c.request('POST','completion-messages',b))}},
{name:'dify.workflow.run',description:'Run a published Dify workflow',risk:'HIGH_RISK',approval:true,schema:z.object({inputs,user,response_mode:z.enum(['blocking','streaming']).default('blocking'),approved:z.literal(true)}),run:async(a,c)=>{authorize('HIGH_RISK',a.approved);const{approved,...b}=a;return untrusted(await c.request('POST','workflows/run',b))}},
{name:'dify.conversation.rename',description:'Rename a conversation',risk:'WRITE',approval:true,schema:z.object({conversation_id:safeId,name:z.string().min(1).max(255),user,auto_generate:z.boolean().default(false),approved:z.literal(true)}),run:async(a,c)=>{authorize('WRITE',a.approved);const{conversation_id,approved,...b}=a;return c.request('POST',`conversations/${encodeURIComponent(conversation_id)}/name`,b)}},
{name:'dify.message.feedback',description:'Submit like/dislike feedback for a message',risk:'WRITE',approval:true,schema:z.object({message_id:safeId,rating:z.enum(['like','dislike','null']),user,content:z.string().max(1000).optional(),approved:z.literal(true)}),run:async(a,c)=>{authorize('WRITE',a.approved);const{message_id,approved,...b}=a;return c.request('POST',`messages/${encodeURIComponent(message_id)}/feedbacks`,b)}}];
export async function invoke(name:string,args:unknown,client:DifyClient){const t=tools.find(x=>x.name===name);if(!t)throw new Error('Unknown tool');return t.run(t.schema.parse(args),client)}
