import test from "node:test";import assert from "node:assert/strict";import {PostmarkAuth} from "../src/auth.js";import {PostmarkClient,PostmarkError} from "../src/client.js";import {requireApproval} from "../src/policy.js";import {tools} from "../src/tools.js";
test("auth requires token",()=>assert.throws(()=>new PostmarkAuth({} as any).token(),/AUTH_MISSING/));
test("registers scoped tools",()=>{const names=tools({} as any).map(x=>x.name);assert.equal(names.length,12);assert(names.every(x=>x.startsWith("postmark.")))});
test("write requires approval",()=>assert.throws(()=>requireApproval("WRITE",false,{POSTMARK_WRITE_APPROVAL:"required"} as any),/APPROVAL_REQUIRED/));
test("strict validation rejects extra fields",()=>assert.equal(tools({} as any)[0].schema.safeParse({x:1}).success,false));
test("pagination validation",async()=>{const c=new PostmarkClient(new PostmarkAuth({POSTMARK_SERVER_TOKEN:"x"} as any),fetch,{POSTMARK_API_BASE_URL:"https://api.postmarkapp.com"} as any);await assert.rejects(()=>c.paged("/bounces",501,0),/PAGINATION_INVALID/)});
test("maps API error",async()=>{const f=async()=>new Response(JSON.stringify({ErrorCode:10,Message:"bad"}),{status:422,headers:{"content-type":"application/json"}});const c=new PostmarkClient(new PostmarkAuth({POSTMARK_SERVER_TOKEN:"x"} as any),f as any,{POSTMARK_API_BASE_URL:"https://api.postmarkapp.com",POSTMARK_MAX_RETRIES:"0"} as any);await assert.rejects(()=>c.request("/server"),e=>e instanceof PostmarkError&&e.status===422)});
test("rate limit retries read",async()=>{let n=0;const f=async()=>{n++;return n===1?new Response(JSON.stringify({Message:"slow"}),{status:429,headers:{"retry-after":"0"}}):new Response(JSON.stringify({ID:1}),{status:200})};const c=new PostmarkClient(new PostmarkAuth({POSTMARK_SERVER_TOKEN:"x"} as any),f as any,{POSTMARK_API_BASE_URL:"https://api.postmarkapp.com",POSTMARK_MAX_RETRIES:"1"} as any);assert.equal((await c.request("/server")).ID,1);assert.equal(n,2)});
test("send does not blindly retry",async()=>{let n=0;const f=async()=>{n++;return new Response(JSON.stringify({Message:"slow"}),{status:429})};const c=new PostmarkClient(new PostmarkAuth({POSTMARK_SERVER_TOKEN:"x"} as any),f as any,{POSTMARK_API_BASE_URL:"https://api.postmarkapp.com",POSTMARK_MAX_RETRIES:"3"} as any);await assert.rejects(()=>c.request("/email",{method:"POST"},false));assert.equal(n,1)});
