import{z}from'zod';import type{McpServer}from'@modelcontextprotocol/sdk/server/mcp.js';import type{Config}from'./client.js';import{RCClient}from'./client.js';
const id=z.string().regex(/^[A-Za-z0-9~_-]{1,128}$/);const phone=z.string().regex(/^\+[1-9]\d{6,14}$/);const page=z.number().int().min(1).max(1000).default(100);const result=(x:unknown)=>({content:[{type:'text' as const,text:JSON.stringify({data:x,untrusted:true})}]});
export function register(s:McpServer,c:Config,a:RCClient){const read=(n:string,d:string,shape:any,f:(x:any)=>Promise<any>)=>s.tool(n,d,shape,async x=>result(await f(x)));
 read('ringcentral.account.get','Read current RingCentral account.',{},()=>a.request('GET','/restapi/v1.0/account/~'));
 read('ringcentral.extension.list','List account extensions.',{perPage:page},x=>a.request('GET','/restapi/v1.0/account/~/extension?perPage='+x.perPage));
 read('ringcentral.extension.get','Read an extension.',{extensionId:id},x=>a.request('GET','/restapi/v1.0/account/~/extension/'+x.extensionId));
 read('ringcentral.phone_number.list','List extension phone numbers.',{extensionId:id.default('~'),perPage:page},x=>a.request('GET','/restapi/v1.0/account/~/extension/'+x.extensionId+'/phone-number?perPage='+x.perPage));
 read('ringcentral.call_log.list','List extension call log.',{extensionId:id.default('~'),dateFrom:z.string().datetime().optional(),dateTo:z.string().datetime().optional(),perPage:page},x=>{const q=new URLSearchParams({perPage:String(x.perPage)});if(x.dateFrom)q.set('dateFrom',x.dateFrom);if(x.dateTo)q.set('dateTo',x.dateTo);return a.request('GET','/restapi/v1.0/account/~/extension/'+x.extensionId+'/call-log?'+q)});
 read('ringcentral.message.list','List message-store records.',{extensionId:id.default('~'),dateFrom:z.string().datetime().optional(),dateTo:z.string().datetime().optional(),perPage:page},x=>{const q=new URLSearchParams({perPage:String(x.perPage)});if(x.dateFrom)q.set('dateFrom',x.dateFrom);if(x.dateTo)q.set('dateTo',x.dateTo);return a.request('GET','/restapi/v1.0/account/~/extension/'+x.extensionId+'/message-store?'+q)});
 read('ringcentral.message.get','Read a message-store record.',{extensionId:id.default('~'),messageId:id},x=>a.request('GET','/restapi/v1.0/account/~/extension/'+x.extensionId+'/message-store/'+x.messageId));
 read('ringcentral.presence.get','Read extension presence.',{extensionId:id.default('~')},x=>a.request('GET','/restapi/v1.0/account/~/extension/'+x.extensionId+'/presence'));
 read('ringcentral.subscription.list','List active event subscriptions.',{},()=>a.request('GET','/restapi/v1.0/subscription'));
 s.tool('ringcentral.sms.send','Send an external SMS. HIGH_RISK: explicit human approval is always required.',{from:phone,to:phone,text:z.string().trim().min(1).max(1000),approved:z.literal(true)},async x=>{if(!x.approved)throw new Error('Explicit human approval required');return result(await a.request('POST','/restapi/v1.0/account/~/extension/~/sms',{from:{phoneNumber:x.from},to:[{phoneNumber:x.to}],text:x.text},false))});
}