import {OAuth2Client} from 'google-auth-library';
import {z} from 'zod';

const Env=z.object({
 GOOGLE_DRIVE_ACCESS_TOKEN:z.string().optional(), GOOGLE_CLIENT_ID:z.string().optional(), GOOGLE_CLIENT_SECRET:z.string().optional(), GOOGLE_REFRESH_TOKEN:z.string().optional(),
 GOOGLE_DRIVE_READ_ONLY:z.enum(['true','false']).default('true'), GOOGLE_DRIVE_ALLOW_WRITE:z.enum(['true','false']).default('false'), GOOGLE_DRIVE_ALLOW_PUBLIC_SHARING:z.enum(['true','false']).default('false'),
 GOOGLE_DRIVE_APPROVAL_MODE:z.enum(['required','disabled']).default('required'), GOOGLE_DRIVE_TIMEOUT_MS:z.coerce.number().int().min(1000).max(120000).default(30000)
});
export type Config={readOnly:boolean;allowWrite:boolean;allowPublic:boolean;approvalMode:'required'|'disabled';timeoutMs:number};
export function config(env=process.env):Config{return ((p)=>({readOnly:p.GOOGLE_DRIVE_READ_ONLY==='true',allowWrite:p.GOOGLE_DRIVE_ALLOW_WRITE==='true',allowPublic:p.GOOGLE_DRIVE_ALLOW_PUBLIC_SHARING==='true',approvalMode:p.GOOGLE_DRIVE_APPROVAL_MODE,timeoutMs:p.GOOGLE_DRIVE_TIMEOUT_MS}))(Env.parse(env));}
export async function accessToken(env=process.env):Promise<string>{if(env.GOOGLE_DRIVE_ACCESS_TOKEN)return env.GOOGLE_DRIVE_ACCESS_TOKEN; if(!env.GOOGLE_CLIENT_ID||!env.GOOGLE_CLIENT_SECRET||!env.GOOGLE_REFRESH_TOKEN)throw new Error('Configure GOOGLE_DRIVE_ACCESS_TOKEN or OAuth client ID, client secret, and refresh token.'); const c=new OAuth2Client(env.GOOGLE_CLIENT_ID,env.GOOGLE_CLIENT_SECRET); c.setCredentials({refresh_token:env.GOOGLE_REFRESH_TOKEN}); const t=await c.getAccessToken(); if(!t.token)throw new Error('Unable to refresh Google OAuth access token.'); return t.token;}
export type Risk='READ'|'WRITE'|'HIGH_RISK'|'DESTRUCTIVE';
export function approve(risk:Risk,args:Record<string,unknown>,c:Config){if(risk==='READ')return; if(risk==='DESTRUCTIVE')throw new Error('Destructive tools are disabled.'); if(c.readOnly||!c.allowWrite)throw new Error('Write operations are disabled by connector policy.'); if(c.approvalMode==='required'){const a=args.approval as any;if(!a?.confirmed||typeof a.reason!=='string'||a.reason.trim().length<3)throw new Error('Explicit human approval is required.');} delete args.approval;}
export async function request(url:string,init:RequestInit,c:Config,retryRead=true):Promise<any>{for(let n=0;n<3;n++){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),c.timeoutMs);try{const r=await fetch(url,{...init,signal:ac.signal});const text=await r.text();if(r.ok){if(!text)return {};try{return JSON.parse(text)}catch{return text}} if((r.status===429||r.status>=500)&&retryRead&&n<2){const ra=Number(r.headers.get('retry-after')||0);await new Promise(x=>setTimeout(x,ra?ra*1000:250*2**n));continue;} if(r.status===401)throw new Error('Google OAuth authentication failed.');if(r.status===403)throw new Error('Google Drive permission/quota denied the request.');if(r.status===429)throw new Error('Google Drive rate limit reached.');throw new Error(`Google Drive error ${r.status}: ${text.slice(0,500)}`);}finally{clearTimeout(timer)}}throw new Error('Google Drive request failed after bounded retries.');}
